Machine translation v2
PaddlePaddle/book pull request #123
Opened 2017-03-04 13:58 UTC by jacquesqiao

2017-03-05 05:04 UTC, wangkuiyi requested changes
赞！写得很好呀。

我理解不需要新增一个README.api.md，而是应该覆盖之前的README.md吧？

一方面这样才能更新index.html，而且也只有覆盖才能让PR展示出diff？

通过查看diff，我们可以知道这个README.api.md和README.md差别在哪里，也才能对应修改 README.en.md。

2017-03-07 01:57 UTC, helinwang commented on machine_translation/README.md
考虑加一句说明这一节的代码都不需要用户自己写，已经包装成Python包裹，只要用户调用就行？我怕用户一上来就尝试使劲看接下来的两段数据处理代码，太累了。

2017-03-07 02:02 UTC, helinwang commented on machine_translation/README.md
> +   source_dict_dim = dict_size # 源语言字典维度
source_dict_dim会被初始化成main函数中的dict_size么，原来Python file level全局变量初始化是在main函数之后呀？

2017-03-07 05:39 UTC, helinwang commented on machine_translation/README.md
> +   2.1 传入已经在data_set中转换成one-hot vector表示的源语言序列$\mathbf{w}$，其类型为integer_value_sequence。
one-hot vector在这里似乎不是很恰当。我所知道的one-hot vector是类似于[0, 0, 1, 0, 0]这种。而这里其实是每个单词的index序列"hi good morning" -> [123, 50, 321]这种。
考虑改成："传入已经在data_set中转换成用每个单词在字典中的索引表示的..."

2017-03-07 05:49 UTC, jacquesqiao commented on machine_translation/README.md
> +   2.1 传入已经在data_set中转换成one-hot vector表示的源语言序列$\mathbf{w}$，其类型为integer_value_sequence。
好的

2017-03-07 05:51 UTC, jacquesqiao commented on machine_translation/README.md
> +   source_dict_dim = dict_size # 源语言字典维度
嗯，source_dict_dim和target_dict_dim会用在两个地方，一个是生成dataset的时候，作为词典大小，一个是定义输入数据的size：
    src_word_id = paddle.layer.data(
        name='source_language_word',
        type=paddle.data_type.integer_value_sequence(source_dict_dim))
以前的做法是预处理的时候生成的dict size是多少，后面就直接用了，现在改成预处理生成一个比较大的dict，但是真正转换数据的时候可以取前面data_size个数据作为dict，因为dict中的word是按照词频排序的。

2017-03-07 05:53 UTC, jacquesqiao commented on machine_translation/README.md
> +   2.1 传入已经在data_set中转换成one-hot vector表示的源语言序列$\mathbf{w}$，其类型为integer_value_sequence。
src_word_id = paddle.layer.data(
name='source_language_word',
type=paddle.data_type.integer_value_sequence(source_dict_dim))
实际上这句话把数据转成了one-hot vector，不过dataset确实不是生成one-hot格式的数据

2017-03-07 09:38 UTC, jacquesqiao commented on machine_translation/README.md
done

2017-03-07 19:12 UTC, helinwang approved these changes
LGTM.

2017-03-07 19:41 UTC, wangkuiyi approved these changes

2017-03-07 19:42 UTC, merged