Refine formula
PaddlePaddle/book pull request #137
Opened 2017-03-06 11:11 UTC by qingqing01

根据 @luotao1 和 @llxxxll 要求，更改了公式~

2017-03-06 19:08 UTC, wangkuiyi requested changes
赞！！

可否顺便也改一下英文版：README.en.md？这两个修改放在一个PR，将来比较好trace变化。

2017-03-07 05:18 UTC, wangkuiyi commented
另外， @qingqing01 你修改后的 README.md 里每一行末尾都有一个 ^M。我用这里[这个方法](http://its.ucsc.edu/unix-timeshare/tutorials/clean-ctrl-m.html) 给去掉了。

2017-03-07 05:31 UTC, wangkuiyi commented
哦。看到不是 @qingqing01 的问题。是develop branch里的README.md 本来就是行末有 ^M 的。

2017-03-07 05:58 UTC, wangkuiyi commented
我提一个新的PR，去掉Ctrl-M。merge之后，再rebase这个PR吧。

2017-03-07 06:18 UTC, qingqing01 commented
@wangkuiyi @luotao1  rebase了~

2017-03-07 06:34 UTC, luotao1 commented
LGTM

> 可否顺便也改一下英文版：README.en.md？这两个修改放在一个PR，将来比较好trace变化。

这一个段落是新的，英文版还没翻译。所以这个PR先merge了。 @wangkuiyi

2017-03-07 06:34 UTC, luotao1 approved these changes

2017-03-07 06:41 UTC, luotao1 commented on recognize_digits/README.md
> +o[0,0,0] = \sum x[0:3,0:3,0] * w_{0}[:,:,0]]  + \sum x[0:3,0:3,1] * w_{0}[:,:,1]]  +  \sum x[0:3,0:3,2] * w_{0}[:,:,2]] +  b_0 = 2
89行后面还需要换行。

2017-03-07 06:45 UTC, wangkuiyi approved these changes

2017-03-07 06:45 UTC, merged

2017-03-07 06:46 UTC, luotao1 commented on recognize_digits/README.md
> +图4给出一个卷积计算过程的示例图，输入图像大小为$H=5,W=5,D=3$，即$5x5$大小的3通道(RGB，也称作深度)彩色图像。这个示例图中包含两(用$K$表示)组卷积核，即图中$Filter W_0$和$Filter W_1$，在卷积计算中，通常对不同的输入通道采用不同的卷积核，如图示例中每组卷积核包含3($D$)个$3x3$(用$FXF$表示)大小的卷积核。另外，这个示例中卷积核在图像的
其中的`x`换成`\times`

2017-03-07 06:47 UTC, luotao1 commented on recognize_digits/README.md
> +b_0 & = 1\\\\
89-93行`=`改成`&=`，现在显示不对。

2017-03-07 06:47 UTC, wangkuiyi commented
@luotao1 OK. I created a followup issue https://github.com/PaddlePaddle/book/issues/141

2017-03-07 21:13 UTC, wangkuiyi commented
怪我没仔细看公式，就merge了。我发一个PR修复公式里的错误。