Refine image classification doc
PaddlePaddle/book pull request #146
Opened 2017-03-07 10:08 UTC by gangliao

Fix #138

2017-03-07 22:37 UTC, helinwang requested changes

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
> + `paddle.datasets` package encapsulates multiple public datasets, including `cifar`, `imdb`, `mnist`, `moivelens` and `wmt14`, etc. There's no need for us to manually donwload and preprocess CIFAR-10
donwload -> download

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
> +After issuing a command `python train.py`, trainning is starting immediately! The details will be unpacked by the following sessions to see how it works.
`trainning is starting immediately!` -> `training will start immediately.`

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
>  First we define VGG network. Since the image size and amount of CIFAR10 are relatively small comparing to ImageNet, we uses a small version of VGG network for CIFAR10. Convolution groups incorporate
`First` -> `First,`

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
> +Here is an example log after training for one pass. The average error rates are 0.6875 on training set and 0.8852 on validation set.
on training set -> on the training set
on validation set -> on the validation set

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
> +`feeding` is devoted to specify the correspondence between each yield record and `paddle.layer.data`. For instance,
is devoted to specify -> is devoted to specifying （devoted to something:)）
Or:
is used to specify

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
>  First we define VGG network. Since the image size and amount of CIFAR10 are relatively small comparing to ImageNet, we uses a small version of VGG network for CIFAR10. Convolution groups incorporate
we uses a -> we use a

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
>          The input to VGG main module is from data layer. `vgg_bn_drop` defines a 16-layer VGG network, with each convolutional layer followed by BN and dropout layers. Here is the definition in detai
from data layer -> from the data layer

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
有一句在原文里不在diff里，也请改一下吧：
between input and output are different -> between input and output is different

2017-03-07 22:37 UTC, helinwang commented on image_classification/README.en.md
> +As alluded to in section `Overview Models`, here we provide the implementations of both VGG and ResNet models.
```
`Overview Models` -> [Model Overview](#model-overview)
```

2017-03-07 22:43 UTC, helinwang commented on image_classification/README.en.md
> +First, we define the model parameters according to the previous model configuration `cost`.
define -> create

2017-03-07 22:43 UTC, helinwang commented on image_classification/README.en.md
> +### Construct Trainer
因为后面有个
```
# Create trainer
```
这里感觉也写成### Create Trainer比较合适。

2017-03-07 22:43 UTC, helinwang commented on image_classification/README.en.md
> +Callback function `event_handler` is used to track training and testing process that might be triggered once the action to which it is attached is executed.
这句话写得语法有点太复杂了，我隐隐觉得可能不对，但又说不出来哪里。
要不要考虑简单处理：
Callback function event_handler will be called during training when a pre-defined event happens.

2017-03-07 23:40 UTC, gangliao commented on image_classification/README.en.md
> + `paddle.datasets` package encapsulates multiple public datasets, including `cifar`, `imdb`, `mnist`, `moivelens` and `wmt14`, etc. There's no need for us to manually donwload and preprocess CIFAR-10
done

2017-03-07 23:40 UTC, gangliao commented on image_classification/README.en.md
> +After issuing a command `python train.py`, trainning is starting immediately! The details will be unpacked by the following sessions to see how it works.
download

2017-03-07 23:40 UTC, gangliao commented on image_classification/README.en.md
> +As alluded to in section `Overview Models`, here we provide the implementations of both VGG and ResNet models.
download

2017-03-07 23:41 UTC, gangliao commented on image_classification/README.en.md
>  First we define VGG network. Since the image size and amount of CIFAR10 are relatively small comparing to ImageNet, we uses a small version of VGG network for CIFAR10. Convolution groups incorporate
download

2017-03-07 23:41 UTC, gangliao commented on image_classification/README.en.md
>  First we define VGG network. Since the image size and amount of CIFAR10 are relatively small comparing to ImageNet, we uses a small version of VGG network for CIFAR10. Convolution groups incorporate
done

2017-03-07 23:41 UTC, gangliao commented on image_classification/README.en.md
>          The input to VGG main module is from data layer. `vgg_bn_drop` defines a 16-layer VGG network, with each convolutional layer followed by BN and dropout layers. Here is the definition in detai
done

2017-03-07 23:41 UTC, gangliao commented on image_classification/README.en.md
done

2017-03-07 23:42 UTC, gangliao commented on image_classification/README.en.md
> +`feeding` is devoted to specify the correspondence between each yield record and `paddle.layer.data`. For instance,
done

2017-03-07 23:42 UTC, gangliao commented on image_classification/README.en.md
> +Here is an example log after training for one pass. The average error rates are 0.6875 on training set and 0.8852 on validation set.
done

2017-03-07 23:43 UTC, gangliao commented on image_classification/README.en.md
> +First, we define the model parameters according to the previous model configuration `cost`.
done

2017-03-07 23:43 UTC, gangliao commented on image_classification/README.en.md
> +Callback function `event_handler` is used to track training and testing process that might be triggered once the action to which it is attached is executed.
done

2017-03-07 23:43 UTC, gangliao commented on image_classification/README.en.md
> +### Construct Trainer
done

2017-03-08 00:18 UTC, gangliao commented on image_classification/README.en.md
>      short = shortcut(ipt, ch_in, ch_out, stride)
@qingqing01  请确认一下 到底是之前写错了 还是我写错了

2017-03-08 00:19 UTC, gangliao commented on image_classification/README.en.md
>      short = shortcut(ipt, ch_in, ch_out, stride)
```
paddle.layer.addto(input=[tmp, short],
```

2017-03-08 03:23 UTC, gangliao commented on image_classification/README.en.md
>      short = shortcut(ipt, ch_in, ch_out, stride)
确认过了 新修改的是对的

2017-03-08 11:42 UTC, qingqing01 commented on image_classification/index.en.html
> +            reader=paddle.reader.batch(
paddle.reader.batch -> paddle.batch

2017-03-08 11:42 UTC, qingqing01 commented on image_classification/index.en.html
> +            reader_dict={'image': 0,
reader_dict -> feeding

2017-03-08 11:44 UTC, qingqing01 commented on image_classification/index.en.html
> +            reader_dict={'image': 0,
这两处同时更改下中文吧~

2017-03-08 11:55 UTC, gangliao commented on image_classification/index.en.html
> +            reader=paddle.reader.batch(
done

2017-03-08 11:55 UTC, gangliao commented on image_classification/index.en.html
> +            reader_dict={'image': 0,
done

2017-03-08 18:24 UTC, helinwang approved these changes
LGTM.

2017-03-08 18:24 UTC, merged