convert markdown to ipynb file and check them
PaddlePaddle/book pull request #150
Opened 2017-03-07 12:21 UTC by gongweibao

1.增加了一个convert_2_ipynb.sh，转换markdown文件
2.增加了检查转换成功的ipynbfile是否能够执行成功

2017-03-07 18:02 UTC, wangkuiyi requested changes

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +command -v go >/dev/null 2>&1 || { echo -e >&2 "${RED}I require go but it's not installed. Aborting.${NC}"; exit 1; }
> I require go but it's not intalled. Aborting

==>

> Please install Go https://golang.org/doc/install#install

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +	$GOPATH/bin/markdown-to-ipynb < $file > $name
`$GOPATH/bin/markdown-to-ipynb` ==> `/tmp/go/bin/markdown-to-ipynb`

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +tmpl_path=$(cd "$(dirname "$0")"; pwd)
`tmpl_path=$(dirname "$0")` 不行吗？

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +export GOPATH=$PWD/.tmpl/go_tool/
`GOPATH=/tmp/go go get -u github.com/wangkuiyi/ipynb/markdown-to-ipynb`

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +for file in `ls */README*.md`
`for ... ; do`

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +for file in `ls */README*.md`
`for i in */README*.md; do echo $i; done` 即可。不需要ls。

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +for file in `ls */README.ipynb`
不用ls。

因为你把 then 和 if 放在一行了，这里应该统一风格，done 和 for 可以放在一行。

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +if [ -z $TEST_ALL_README ]; then
```bash
if [[ ! -z $TEST_EMBEDDED_PYTHON_SCRIPTS ]]; then
  all code from L34 till the end of test
fi
```

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +mkdir -p $tmpl_path/test_ipynb
`$tmpl_path/test_ipynb` ==> `/tmp/book/tests`

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +    ipython nbconvert --to python $file_name --output=$dest_file_path
从 L38 到 L65 太冗长了。这里应该一行就行

```bash
ipython nbconvert --to python notebook.ipynb --stdout | python
```

2017-03-07 18:02 UTC, wangkuiyi commented on build.sh
> +.tmpl/convert_2_ipynb.sh
`.tmpl/convert_2_ipynb.sh` ==> `tools/convert-markdown-into-ipynb-and-test.sh`

2017-03-07 18:02 UTC, wangkuiyi commented on .tmpl/convert_2_ipynb.sh
> +if [ -z $TEST_ALL_README ]; then
实际上，我觉得不需要这个condition —— 直接测试就好了。

2017-03-08 00:58 UTC, gongweibao commented
惭愧，review比我的代码还要详细。。下次要搞得好看一点。。

2017-03-08 03:17 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +tmpl_path=$(cd "$(dirname "$0")"; pwd)
done

2017-03-08 03:23 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +command -v go >/dev/null 2>&1 || { echo -e >&2 "${RED}I require go but it's not installed. Aborting.${NC}"; exit 1; }
done

2017-03-08 03:24 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +export GOPATH=$PWD/.tmpl/go_tool/
done

2017-03-08 05:05 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +tmpl_path=$(cd "$(dirname "$0")"; pwd)
done

2017-03-08 05:05 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +for file in `ls */README*.md`
done

2017-03-08 05:05 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +for file in `ls */README*.md`
done

2017-03-08 05:05 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +	$GOPATH/bin/markdown-to-ipynb < $file > $name
done

2017-03-08 05:07 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +for file in `ls */README.ipynb`
done

2017-03-08 05:20 UTC, gongweibao commented on build.sh
> +.tmpl/convert_2_ipynb.sh
done

2017-03-08 06:19 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +if [ -z $TEST_ALL_README ]; then
done
由于test的时间很长，还是把condition保留下来

2017-03-08 06:20 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +mkdir -p $tmpl_path/test_ipynb
不再使用这个目录，直接用stdout

2017-03-08 06:20 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +    ipython nbconvert --to python $file_name --output=$dest_file_path
done

2017-03-08 06:21 UTC, gongweibao commented on .tmpl/convert_2_ipynb.sh
> +mkdir -p $tmpl_path/test_ipynb
done

2017-03-08 10:37 UTC, jacquesqiao requested changes

2017-03-08 10:37 UTC, jacquesqiao commented on tools/convert-markdown-into-ipynb-and-test.sh
> +    jupyter nbconvert --to python $(basename $file) --stdout | python
这个测试是需要手动触发对么

2017-03-08 10:37 UTC, jacquesqiao commented on pre-commit-hooks/convert_markdown_into_ipynb.sh
> +	/tmp/go/bin/markdown-to-ipynb < $file > ${file%.*}".ipynb"
本地写死到tmp下，应该也有问题，每次都需要手动下载一下，能否把go缓存到当前目录下的某个临时目录中？

2017-03-08 11:18 UTC, gongweibao commented on tools/convert-markdown-into-ipynb-and-test.sh
> +    jupyter nbconvert --to python $(basename $file) --stdout | python
手动触发，有跑不完的风险。

2017-03-08 11:20 UTC, gongweibao commented on pre-commit-hooks/convert_markdown_into_ipynb.sh
> +	/tmp/go/bin/markdown-to-ipynb < $file > ${file%.*}".ipynb"
这个我也正在找。。最好的办法是在pre-commit中像.travis.yml一样，检查之前先把它下载完毕。目前还没有找到。咨询了一下于洋。

2017-03-08 13:52 UTC, jacquesqiao approved these changes

2017-03-08 21:36 UTC, wangkuiyi approved these changes

2017-03-09 01:43 UTC, merged