Feature/refine frontpage
PaddlePaddle/book pull request #182
Opened 2017-03-08 08:28 UTC by reyoung

book.paddlepaddle.org主页

2017-03-08 13:27 UTC, llxxxll commented on index.html
> +                深度学习入门
因为left-menu里已经有标题了，是不是这里可以不用再显示这个选项？

2017-03-08 13:33 UTC, llxxxll commented on index.html
>      </script>
增加百度统计代码
```
<!-- Baidu Analystics -->
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "//hm.baidu.com/hm.js?b9a314ab40d04d805655aab1deee08ba";
  var s = document.getElementsByTagName("script")[0];
  s.parentNode.insertBefore(hm, s);
})();
</script>
```

2017-03-08 13:35 UTC, llxxxll approved these changes
先提交一版看看线上效果。

2017-03-09 00:21 UTC, wangkuiyi requested changes
Cannot display chapter text on my desktop with mac os sierra + Chrome.  I git-fetch && git-checkout  @reyoung 's work.

![screen shot 2017-03-08 at 4 20 10 pm](https://cloud.githubusercontent.com/assets/1548775/23730228/389b0542-041b-11e7-81aa-1a4a3a5c406b.png)

2017-03-09 02:41 UTC, ghost approved these changes

2017-03-09 02:43 UTC, wangkuiyi approved these changes

2017-03-09 05:22 UTC, merged