build book docker image
PaddlePaddle/book pull request #220
Opened 2017-03-18 07:49 UTC by gongweibao

打包book docker image

2017-03-18 07:57 UTC, gangliao commented on tools/build_docker.sh
> +	apt-get -y install gcc && \
不是很理解为什么需要gcc?

2017-03-18 08:11 UTC, gongweibao commented on tools/build_docker.sh
> +	apt-get -y install gcc && \
安装matplotlib这个东东的时候需要gcc

2017-03-18 15:25 UTC, helinwang commented
我需要做这些修改才能build通过：
```
+paddle_version=0.10.0rc2
 if [ $? -ne 0 ]; then
        echo 1>&2 "get paddle version error"
        exit 1
@@ -22,7 +23,7 @@ fi
 
 mkdir -p build
 cat > build/Dockerfile <<EOF
-FROM paddlepaddle/paddle:${paddle_version}
+FROM paddledev/paddle:${paddle_version}
 MAINTAINER PaddlePaddle Authors <paddle-dev@baidu.com>
 
 RUN apt-get install locales 
@@ -43,4 +44,4 @@ EOF
 
 #build docker image
 echo "paddle_version:"$paddle_version
-docker build -t paddlepaddle/book:${paddle_version}  -t paddlepaddle/book:latest  -f ./build/Dockerfile .
+docker build -t paddledev/book:${paddle_version}  -t paddledev/book:latest  -f ./build/Dockerfile .
```

2017-03-18 15:28 UTC, helinwang commented on tools/build_docker.sh
> +./tools/convert-markdown-into-ipynb-and-test.sh
这个需要改成这样吧
```bash
./pre-commit-hooks/convert_markdown_into_ipynb.sh $(find . -name "*.md")
```

2017-03-19 01:50 UTC, typhoonzero commented on tools/build_docker.sh
> +cur_path=$(dirname $(readlink -f $0))
`cur_path=$PWD`可以么？

2017-03-19 01:50 UTC, typhoonzero commented on tools/build_docker.sh
> +cd paddle && paddle_version=`git describe --abbrev=0 --tags` && cd ..
目前只能得到0.9的tag，应该给paddle 更新下tag了？

2017-03-19 02:30 UTC, typhoonzero commented on tools/build_docker.sh
> +CMD ["jupyter", "notebook", "--ip=0.0.0.0", "/book/"]
according to https://github.com/ipython/ipython/issues/7062 change to `CMD ["sh", "-c", "jupyter", "notebook", "--ip=0.0.0.0", "/book/"]` solves the kernel dead problem

2017-03-19 03:08 UTC, gongweibao commented on tools/build_docker.sh
> +cur_path=$(dirname $(readlink -f $0))
软连接可能有问题

2017-03-19 04:18 UTC, gongweibao commented
@helinwang, 勇峰建议的是paddlepaddle下。不过大家都用paddledev下了。我改一下。

2017-03-19 05:58 UTC, helinwang commented
@gongweibao 好的，先跟paddle主镜像一样放在paddledev吧，辛苦！

2017-03-19 10:52 UTC, gongweibao commented on tools/build_docker.sh
> +CMD ["jupyter", "notebook", "--ip=0.0.0.0", "/book/"]
check了一下，应该是：CMD ["sh", "-c", "jupyter notebook --ip=0.0.0.0 /book/"]

2017-03-19 10:52 UTC, gongweibao commented on tools/build_docker.sh
> +cd paddle && paddle_version=`git describe --abbrev=0 --tags` && cd ..
done

2017-03-19 16:33 UTC, wangkuiyi requested changes
赞！

还需要一个文档，`/README.md`，说明怎么用这个 build_docker.sh，包括需要的依赖（如何build paddledev/paddle）以及如何运行这个 book image。

2017-03-19 16:33 UTC, wangkuiyi commented on tools/build_docker.sh
> +if [ ${USE_MIRROR} ]; then
USE_MIRROR ==> USE_UBUNTU_REPO_MIRROR

2017-03-19 16:33 UTC, wangkuiyi commented on tools/build_docker.sh
> +  MIRROR_UPDATE="\\"
MIRROR_UPDATE ==> UPDATE_MIRROR_CMD

2017-03-19 16:33 UTC, wangkuiyi commented on tools/build_docker.sh
> +RUN apt-get install locales
下文中的 `RUN ${MIRROR_UPDATE}` 应该在这一行之前吧

2017-03-19 16:33 UTC, wangkuiyi commented on tools/build_docker.sh
> +FROM paddledev/paddle:${paddle_version}
这里应该是paddledev 还是 paddlepaddle ?

2017-03-19 22:08 UTC, helinwang requested changes
Please install python package `scipy` in the Dockerfile. Word2vec example requires `scipy` pacakge.

2017-03-20 01:44 UTC, gongweibao commented on tools/build_docker.sh
> +FROM paddledev/paddle:${paddle_version}
在群里简单讨论过。。。。我看大家都用的是paddledev下。就改成了这个。

2017-03-20 01:51 UTC, gongweibao commented on tools/build_docker.sh
> +RUN apt-get install locales
确实。改动bug的时候没把这个放到前边去。
done

2017-03-20 01:52 UTC, gongweibao commented on tools/build_docker.sh
> +if [ ${USE_MIRROR} ]; then
done

2017-03-20 02:37 UTC, gongweibao commented
>还需要一个文档，/README.md，说明怎么用这个 build_docker.sh，包括需要的依赖（如何build paddledev/paddle）以及如何运行这个 book image。
如何打包和使用book image，这个可以放到book的/README.md
paddledev/paddle image的打包是否就放一个链接在book的/README.md里边就可以了？@wangkuiyi

2017-03-20 04:40 UTC, helinwang commented on tools/build_docker.sh
> +cd paddle && git checkout develop && paddle_version=`git describe --abbrev=0 --tags` && cd ..
建议直接改成`paddle_version=0.10.0rc2`，因为要是paddle api不小心跟book不兼容，一直追踪最新的tag可能导致book有问题。不如一直放在稳定的版本（比如`0.10.0rc2`），等到需要调整版本的时候再更新。

2017-03-20 05:01 UTC, gongweibao commented on tools/build_docker.sh
> +cd paddle && git checkout develop && paddle_version=`git describe --abbrev=0 --tags` && cd ..
这个建议好。那我们就不用update paddle的代码了。

2017-03-20 05:54 UTC, wangkuiyi commented on tools/build_docker.sh
> +FROM paddledev/paddle:${paddle_version}
建议用paddlepaddle。和github上的账号保持一致。

2017-03-20 07:07 UTC, wangkuiyi commented on tools/build_docker.sh
> +paddle_version=0.10.0rc2
这里是不是还得改回去用tag来决定才行？

2017-03-20 07:08 UTC, wangkuiyi commented
> 如何打包和使用book image，这个可以放到book的/README.md
paddledev/paddle image的打包是否就放一个链接在book的/README.md里边就可以了？@wangkuiyi

是的。

2017-03-20 07:59 UTC, gongweibao commented on tools/build_docker.sh
> +paddle_version=0.10.0rc2
如果我们的book改的慢，而paddle改的快，book的程序可能就不match了？

2017-03-20 11:52 UTC, closed without merging

2017-03-20 11:53 UTC, gongweibao commented on tools/build_docker.sh
> +cur_path=$(dirname $(readlink -f $0))
改成了pwd -p的形式。因为mac不支持readlink -f