Add machine translation
PaddlePaddle/book pull request #23
Opened 2016-12-23 10:18 UTC by luotao1

resolve #9 
还未写完。

2016-12-26 08:32 UTC, schinger commented on machine_translation/README.md
> +即源语言句子的压缩表示由原来的$c$变成了$c_i$，同时$c_i$可以通过各个$h_i$的加权平均得到：$c_i=\sum _{j=1}^{T}\alpha _{ij}h_j$，$\alpha _{ij}$为权重。
\alpha _{ij} 的计算过程未说明

2016-12-26 08:32 UTC, schinger commented on machine_translation/README.md
> +### GRU模型
> ### GRU   
就行了吧。。GRU模型感觉怪怪的

2016-12-26 08:32 UTC, schinger commented on machine_translation/README.md
> +
从“数据准备”开始到此的篇幅是否过长。。

2016-12-26 08:32 UTC, schinger commented on machine_translation/README.md
> +1. Clear.的博客. http://blog.csdn.net/u011414416
博客、wikipedia作为参考文献好吗。。

2016-12-27 09:21 UTC, schinger reviewed
仅供参考

2016-12-27 09:21 UTC, schinger commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。利用神经网络的机器翻译系统大致分为两类：1）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块（见图1的左半部分），如翻译模型、语言模型、调序模型等。2）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言（见图1的右半部分），即端到端的神经网络机器翻译（Neural Machine Translation, NMT
是否可以在背景介绍里增加说明nmt属于更抽象的seq2seq问题，seq2seq问题还包含摘要，对话等问题，它们都可以用本章的模型解决。

2016-12-27 09:21 UTC, schinger commented on machine_translation/README.md
> +GRU（Gated Recurrent Unit，门控循环单元）是Cho等人在LSTM上提出的简化版本，如下图所示。GRU单元只有两个门，分别是重置门（Reset Gate）和更新门（Update Gate），用于控制记忆内容是否能继续保存下去。
快定稿时，是否可增加sentiment analysis那章中rnn的链接？因为grn也属于rnn的变体。

2016-12-27 09:21 UTC, schinger commented on machine_translation/README.md
> +图. 编码器-解码器框架
独热编码:) :)

2016-12-27 09:21 UTC, schinger commented on machine_translation/README.md
> +- 映射到低维语义空间的词向量：独热编码表示存在两个问题，1）生成的向量维度往往很大，容易造成维数灾难；2）无法刻画词与词之间的关系（如语义相似性，也就是无法很好地表达语义）。因此需再映射到低维的语义空间，由一个固定维度的稠密向量表示，称为词向量。记映射矩阵为$C\epsilon R^{K\times \left | V \right |}$，用$s_i=Cw_i$表示第$i$个词的词向量，向量
快定稿时，是否可增加word embedding那章的链接

2016-12-27 09:21 UTC, schinger commented on machine_translation/README.md
> +解码阶段的总体思路是：根据当前单词$u_i$，当前RNN隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$。然后用softmax归一化得到概率分布$p_{i+1}$，以此采样出单词$u_{i+1}$。不断重复上述操作，直到获得句子结束标记`<EOS>`或超过RNN循环次数为止。
根据当前单词$u_i$，当前RNN隐层状态$z_i$，还有c

2016-12-28 11:18 UTC, luotao1 commented on machine_translation/README.md
> +GRU（Gated Recurrent Unit，门控循环单元）是Cho等人在LSTM上提出的简化版本，如下图所示。GRU单元只有两个门，分别是重置门（Reset Gate）和更新门（Update Gate），用于控制记忆内容是否能继续保存下去。
这些链接等所有PR merge了一遍后，统一再加吧。PR之间不要互相等待。

2016-12-28 11:25 UTC, luotao1 commented on machine_translation/README.md
> +即源语言句子的压缩表示由原来的$c$变成了$c_i$，同时$c_i$可以通过各个$h_i$的加权平均得到：$c_i=\sum _{j=1}^{T}\alpha _{ij}h_j$，$\alpha _{ij}$为权重。
和 @lcy-seso 讨论后，\alpha _{ij} 的计算过程不在这里具体展开了。

2016-12-28 11:27 UTC, luotao1 commented on machine_translation/README.md
> +1. Clear.的博客. http://blog.csdn.net/u011414416
Done。已删除。

2016-12-28 11:28 UTC, luotao1 commented on machine_translation/README.md
> +### GRU模型
Done

2016-12-28 11:34 UTC, luotao1 commented on machine_translation/README.md
> +
可以先看看notebook的效果

2016-12-28 11:49 UTC, luotao1 commented on machine_translation/README.md
> +解码阶段的总体思路是：根据当前单词$u_i$，当前RNN隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$。然后用softmax归一化得到概率分布$p_{i+1}$，以此采样出单词$u_{i+1}$。不断重复上述操作，直到获得句子结束标记`<EOS>`或超过RNN循环次数为止。
Done

2016-12-29 02:42 UTC, luotao1 commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。利用神经网络的机器翻译系统大致分为两类：1）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块（见图1的左半部分），如翻译模型、语言模型、调序模型等。2）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言（见图1的右半部分），即端到端的神经网络机器翻译（Neural Machine Translation, NMT
Done

2016-12-29 05:46 UTC, Zrachel reviewed
已有内容修改需求

2016-12-29 05:46 UTC, Zrachel commented on machine_translation/README.md
> +- 另外有两个特殊表示：`<e>`表示句子的结尾，`unk`表示无法识别（即不在训练字典中）的单词。
`<unk>`

2016-12-29 05:46 UTC, Zrachel commented on machine_translation/README.md
> +理论上，RNN $t$时刻的输出编码了所有到$t$时刻之前的历史信息。然而，标准的神经网络通常都忽略了未来时刻的上下文信息。因此，如果能像访问历史上下文信息一样来访问未来上下文信息，很多序列学习任务都能从中获益。双向RNN就是解决这一问题的一种简单有效的方法，由Bengio等人在论文\[[1](#参考文献),[3](#参考文献)\]中提出。
未来时刻只指向下文信息

2016-12-29 05:46 UTC, Zrachel commented on machine_translation/README.md
> +- 用RNN压缩源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，最后得到的$h_T$就是整个源语言句子的压缩表示。
压缩表示->编码，后文中”压缩表示“也同样换成编码

2016-12-29 05:46 UTC, Zrachel commented on machine_translation/README.md
> +编码阶段使用双向GRU，即一个词的隐层状态不仅压缩了前面词的信息，还压缩了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次压缩源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},..
remove 括号

2016-12-29 05:46 UTC, Zrachel commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的压缩表示$c$、当前单词$u_i$和当前RNN隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$。然后用softmax归一化得到概率分布$p_{i+1}$，以此采样出单词$u_{i+1}$。不断重复上述操作，直到获得句子结束标记`<EOS>`或超过RNN循环次数为止。
当前单词$u_i$ -> 翻译出来的第$i$个单词$u_i$
当前RNN隐层状态$z_i$ -> $i$时刻RNN的隐层状态$z_i$

2016-12-29 05:46 UTC, Zrachel commented on machine_translation/README.md
> +#### 基于注意力机制的编码器
->基于双层RNN模型的编码器，把上面一段挪下来吧

2016-12-29 05:46 UTC, Zrachel commented on machine_translation/README.md
> +可见，源语言句子的压缩表示由原来的$c$变成了$c_i$，即针对每一个目标词$y_i$，都有一个特定的$c_i$与之对应。其中$c_i$可以通过各个$h_i$的加权平均得到：$c_i=\sum _{j=1}^{T}\mathbf{a}_{ij}h_j$，$\mathbf{a}_i=\left[ \mathbf{a}_{i1},\mathbf{a}_{i2},...,\mathbf{a}_{iT}
这里再解释一遍c吧，c表示context，c_t表示对第t个生成翻译的词y_t，都有一个context（上下文）向量，表示由当前生成词语$u_t$和所有源输入词$h_i$之间的关联$a_i$决定的一个向量。

2016-12-29 07:12 UTC, lcy-seso commented on machine_translation/README.md
> +本节依次介绍GRU，双向RNN模型，NMT中典型的“编码器-解码器”（Encoder-Decoder）框架和“注意力”（Attention）机制，以及集束搜索（Beam Search）算法。
GRU 这里第一次出现，应该把 49 行的 Gated Recurrent Unit 放在第一次出现的地方。

2016-12-29 07:12 UTC, lcy-seso commented on machine_translation/README.md
> +</p>
这些图，咱们后面是要重绘的对吗？这幅图太经典，几乎大家都会搜到，我们直接放在 PaddlePaddle 里面会不会不太合适？

2016-12-29 07:12 UTC, lcy-seso commented on machine_translation/README.md
> +
到第一个句号这句话，不太通顺。

2016-12-29 07:12 UTC, lcy-seso commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的压缩表示$c$、当前单词$u_i$和当前RNN隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$。然后用softmax归一化得到概率分布$p_{i+1}$，以此采样出单词$u_{i+1}$。不断重复上述操作，直到获得句子结束标记`<EOS>`或超过RNN循环次数为止。
这里解释了解码器的解码阶段，却一两句话解释解码器的编码训练过程。

2016-12-29 07:12 UTC, lcy-seso commented on machine_translation/README.md
> +编码阶段使用双向GRU，即一个词的隐层状态不仅压缩了前面词的信息，还压缩了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次压缩源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},..
“压缩”确实有点奇怪的感觉。“编码”就可以 。

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +- 另外有两个特殊表示：`<e>`表示句子的结尾，`unk`表示无法识别（即不在训练字典中）的单词。
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +本节依次介绍GRU，双向RNN模型，NMT中典型的“编码器-解码器”（Encoder-Decoder）框架和“注意力”（Attention）机制，以及集束搜索（Beam Search）算法。
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +</p>
后面会找设计师重画的

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +- 用RNN压缩源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，最后得到的$h_T$就是整个源语言句子的压缩表示。
Done，后面所有的“压缩”也换成了“编码”

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +编码阶段使用双向GRU，即一个词的隐层状态不仅压缩了前面词的信息，还压缩了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次压缩源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},..
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的压缩表示$c$、当前单词$u_i$和当前RNN隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$。然后用softmax归一化得到概率分布$p_{i+1}$，以此采样出单词$u_{i+1}$。不断重复上述操作，直到获得句子结束标记`<EOS>`或超过RNN循环次数为止。
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的压缩表示$c$、当前单词$u_i$和当前RNN隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$。然后用softmax归一化得到概率分布$p_{i+1}$，以此采样出单词$u_{i+1}$。不断重复上述操作，直到获得句子结束标记`<EOS>`或超过RNN循环次数为止。
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +#### 基于注意力机制的编码器
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +理论上，RNN $t$时刻的输出编码了所有到$t$时刻之前的历史信息。然而，标准的神经网络通常都忽略了未来时刻的上下文信息。因此，如果能像访问历史上下文信息一样来访问未来上下文信息，很多序列学习任务都能从中获益。双向RNN就是解决这一问题的一种简单有效的方法，由Bengio等人在论文\[[1](#参考文献),[3](#参考文献)\]中提出。
Done

2017-01-03 03:18 UTC, luotao1 commented on machine_translation/README.md
> +可见，源语言句子的压缩表示由原来的$c$变成了$c_i$，即针对每一个目标词$y_i$，都有一个特定的$c_i$与之对应。其中$c_i$可以通过各个$h_i$的加权平均得到：$c_i=\sum _{j=1}^{T}\mathbf{a}_{ij}h_j$，$\mathbf{a}_i=\left[ \mathbf{a}_{i1},\mathbf{a}_{i2},...,\mathbf{a}_{iT}
Done

2017-01-03 03:24 UTC, luotao1 commented
之前的意见已经全部修改完了

2017-01-05 11:16 UTC, Zrachel reviewed
先看着。。。

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +传统机器翻译，是让语言学家编写两种语言之间的转换规则，再将这些规则录入给计算机。但该方法对语言学家的要求非常高，并且，我们不可能知道一门语言究竟有多少隐含的使用规则，更何况两种甚至更多的语言。因此，传统机器翻译方法面临的主要挑战是无法得到一个完备的规则集合。
并且，我们不可能知道一门语言究竟有多少隐含的使用规则，
->
而且我们几乎无法总结一门语言会用到的所有规则

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。这类系统又大致分为两类：1）（见图1的左半部分）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块，如翻译模型、语言模型、调序模型等；2）（见图1的右半部分）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言，即端到端的神经网络机器翻译（Neural Machine Translation, NMT）。
如翻译模型、语言模型、调序模型等 
这里去掉翻译模型？都有了翻译模型还要统计机器翻译模块其他部分干嘛呢？或者指明 短语翻译模型？（我不确定具体指什么，查一下吧）

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。这类系统又大致分为两类：1）（见图1的左半部分）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块，如翻译模型、语言模型、调序模型等；2）（见图1的右半部分）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言，即端到端的神经网络机器翻译（Neural Machine Translation, NMT）。
1）（见图1的左半部分）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块，如翻译模型、语言模型、调序模型等； 
开头括号部分挪到句末分号前，2)同

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +当法英翻译的模型训练完毕后，以下面的两句法语为例：
有中英翻译的例子吗？法语没人看得懂啊。。。

另外展示一条就行，下面也不需要解释  第一行的“0”和第6行的“1”表示翻译第几条法语句子。

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +统计机器翻译（Statistical Machine Translation, SMT），其转化规则是由机器自动从大规模的语料中学习得到的，而非我们人主动提供规则。因此，它克服了传统方法面临的知识获取瓶颈问题，但仍然存在许多挑战：1）需要人为设计许多特征，但永远无法覆盖所有的语言规则；2）难以利用全局的特征；3）依赖于许多预处理环节，如词语对齐、中文分词、规则抽取、句法分析等，而每个环节的错误会
如词语对齐、中文分词、规则抽取、句法分析等
->
如词语对齐、分词（Tokenization）、句法分析、规则抽取等

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +统计机器翻译（Statistical Machine Translation, SMT），其转化规则是由机器自动从大规模的语料中学习得到的，而非我们人主动提供规则。因此，它克服了传统方法面临的知识获取瓶颈问题，但仍然存在许多挑战：1）需要人为设计许多特征，但永远无法覆盖所有的语言规则；2）难以利用全局的特征；3）依赖于许多预处理环节，如词语对齐、中文分词、规则抽取、句法分析等，而每个环节的错误会
段末引用这个：
Koehn P. Statistical machine translation[M]. Cambridge University Press, 2009.

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +GRU\[[1](#参考文献)\]是Cho等人在LSTM上提出的简化版本，如下图所示。GRU单元只有两个门，分别是重置门（Reset Gate）和更新门（Update Gate），用于控制记忆内容是否能继续保存下去。
首句加上
↓
我们已经在 情感分析 一章中介绍了循环神经网络(RNN)及长短时间记忆网络（LSTM）。 回忆一下LSTM中用输入门、遗忘门和输出门控制信息传送和网络的记忆单元。

2017-01-05 11:16 UTC, Zrachel commented on machine_translation/README.md
> +GRU\[[1](#参考文献)\]是Cho等人在LSTM上提出的简化版本，如下图所示。GRU单元只有两个门，分别是重置门（Reset Gate）和更新门（Update Gate），用于控制记忆内容是否能继续保存下去。
GRU介绍需要再加一些，如：
可以加上参考文献[1]中，第3页左栏最下面以In this formulation, when the reset gate is close开始的两三段话翻译总结下写到这里来。酱紫也可以有一些和LSTM的比较。

2017-01-05 12:30 UTC, Zrachel requested changes
模型概览 部分 修改建议

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +双向RNN的每一个训练序列，向前和向后分别是两个循环神经网络（RNN），而且都连接着一个输出层。这个结构提供给输出层：输入序列中每一个点完整的过去和未来的下文信息。下图展示的是一个按时间步展开的双向循环神经网络。该网络包含一个前向（forward）和一个后向（backward）RNN，其中有六个权值：输入到前向隐层和后向隐层（$w_1, w_3$），隐层到隐层自己（$w_2,w_5$），前向隐层
向前和向后分别是两个循环神经网络（RNN），而且都连接着一个输出层
->
分别在时间维顺序和逆序（即前向和后向地）输入一个循环神经网络（RNN），并将每个时刻的输出分别连接到输出层。

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +双向RNN的每一个训练序列，向前和向后分别是两个循环神经网络（RNN），而且都连接着一个输出层。这个结构提供给输出层：输入序列中每一个点完整的过去和未来的下文信息。下图展示的是一个按时间步展开的双向循环神经网络。该网络包含一个前向（forward）和一个后向（backward）RNN，其中有六个权值：输入到前向隐层和后向隐层（$w_1, w_3$），隐层到隐层自己（$w_2,w_5$），前向隐层
这个结构提供给输出层：输入序列中每一个点完整的过去和未来的下文信息。
-》
这样输出层的每个节点都包含了输入中当前时刻输入的过去和未来上下文信息。

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU
这句话删掉吧，在GRU中已经介绍了。

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
这里讲 压缩 比较奇怪，换成 映射或者编码 吧

下文同

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
解码阶段以概率的方式从中解码出整个目标序列
-》
解码阶段通过最大化预测序列概率，从中解码出整个目标序列

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +- 独热编码（one-hot coding，1-of-K coding）表示：将源语言句子$x=\left \{ x_1,x_2,...,x_T \right \}$的每个词表示成一个向量$w_i\epsilon R^{\left | V \right |},i=1,2,...,T$ （T暂不包括句子结束标记`<EOS>`）。这个向量的维度与词汇表大小$\left | V \right |$ 相
\epsilon  -> \in

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +- 独热编码（one-hot coding，1-of-K coding）表示：将源语言句子$x=\left \{ x_1,x_2,...,x_T \right \}$的每个词表示成一个向量$w_i\epsilon R^{\left | V \right |},i=1,2,...,T$ （T暂不包括句子结束标记`<EOS>`）。这个向量的维度与词汇表大小$\left | V \right |$ 相
（T暂不包括句子结束标记`<EOS>`） 
删掉这句吧，这里不用讲

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +- 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，最后得到的$h_T$就是整个源语言句子的编码。
解释下\varnothing表示RNN函数什么的

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
双向GRU 第一次出现，容易蒙
-》
编码阶段也可以使用双向RNN实现更复杂的句编码表示，具体可以用双向GRU实现，（去掉“具体来说”）

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息

这句去掉吧

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
类似得
-》
类似地

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的上下文向量（context vector）c、解码出来的第$i$个单词$u_i$和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，然后用softmax归一化得到概率分布$p_{i+1}$。训练模式时，根据$p_{i+1}$和目标语言词在字典中的标签计算代价，重复上述操作，直到目标语言序列中的所有词处理完毕。生成模式时，根据$p_
c->$c$

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的上下文向量（context vector）c、解码出来的第$i$个单词$u_i$和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，然后用softmax归一化得到概率分布$p_{i+1}$。训练模式时，根据$p_{i+1}$和目标语言词在字典中的标签计算代价，重复上述操作，直到目标语言序列中的所有词处理完毕。生成模式时，根据$p_
段首+：机器翻译任务中，解码阶段预测目标语言序列。模型训练的目标是最大化真实翻译目标语言序列的概率。总体思路是：每一时刻根据源语言句子的编码信息$c$、目标语言序列的第$i$个单词$u_i$和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，并通过`softmax`归一化得到目标语言序列的第$i$个单词的概率分布$p_{i+1}$。

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +其中$c=h_T$是源语言句子的上下文向量，$z_0$是一个全零的向量，$u_0$是源语言句子的结束标记`<EOS>`。
$u_0$是源语言句子的结束标记`<EOS>`
$u_0$不能是`<EOS>`吧, 是起始符号如`<s>`, 或者0什么的.

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +在上述框架中，由于编码阶段压缩成的固定维度的向量，需要包含源语言序列的所有信息，对于长句子而言很难达到的。因此，Bahdanau等人\[[3](#参考文献)\]引入注意力（Attention）机制，其基本思想是目标语言端的词，往往只和源语言端的部分词相关。下面介绍在注意力机制的解码器结构。
在上述框架中，由于编码阶段压缩成的固定维度的向量，需要包含源语言序列的所有信息，对于长句子而言很难达到的。
这句话有出处吗？
感觉attention要解决的问题不是因为encoding无法覆盖所有信息，而是源语言的句子中不同词有不同的重要程度。

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +在上述框架中，由于编码阶段压缩成的固定维度的向量，需要包含源语言序列的所有信息，对于长句子而言很难达到的。因此，Bahdanau等人\[[3](#参考文献)\]引入注意力（Attention）机制，其基本思想是目标语言端的词，往往只和源语言端的部分词相关。下面介绍在注意力机制的解码器结构。
其基本思想是目标语言端的词，往往只和源语言端的部分词相关。下面介绍在注意力机制的解码器结构。
这句话有出处吗？
不加attention的时候也是这个基本思想其实。。不太严谨的感觉。。

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +可见，源语言句子的上下文向量由原来的$c$变成了第$i$个$c_i$，即针对每一个待解码的词$u_i$，都有一个特定的$c_i$与之对应。$c_i$的计算公式如下：
即针对每一个待解码的词$u_i$

-》

即针对每一个目标语言中的词$u_i$

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +从公式中可以看出，注意力机制即是通过对各个$h_j$进行加权平均实现的，其中权重$a_{ij}$表示待解码的词$u_i$对每个源词语$h_i$不同程度的注意力。具体权重计算公式见\[[3](#参考文献)\]。
注意力机制即是通过对各个$h_j$进行加权平均实现的
-》
注意力机制是通过对各时刻编码器中RNN状态$h_j$进行加权平均实现的

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +从公式中可以看出，注意力机制即是通过对各个$h_j$进行加权平均实现的，其中权重$a_{ij}$表示待解码的词$u_i$对每个源词语$h_i$不同程度的注意力。具体权重计算公式见\[[3](#参考文献)\]。
其中权重$a_{ij}$表示待解码的词$u_i$对每个源词语$h_i$不同程度的注意力
-》
其中权重$a_{ij}$表示目标语言中的第$i$个词$u_i$对源语言中第j个词的注意力大小

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +从公式中可以看出，注意力机制即是通过对各个$h_j$进行加权平均实现的，其中权重$a_{ij}$表示待解码的词$u_i$对每个源词语$h_i$不同程度的注意力。具体权重计算公式见\[[3](#参考文献)\]。
具体权重计算公式见\[[3](#参考文献)\]
还是写下？

2017-01-05 12:30 UTC, Zrachel commented on machine_translation/README.md
> +集束搜索算法使用广度优先策略建立搜索树，在树的每一层，按照启发代价（Heuristic Cost）（本教程中，为生成词的概率）对节点进行排序，然后仅留下预先确定的个数（Beam Width，Beam Size，集束宽度）的节点。只有这些节点会在下一层继续扩展，其他节点就被剪掉了，也就是说保留了质量较高的节点，剪掉了质量较差的节点。因此，搜索所占用的空间和时间大幅减少，但缺点是可能存在最优解被丢弃
剪掉-剪枝

2017-01-05 15:32 UTC, Zrachel reviewed
数据、模型解释 部分 修改建议

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +  - `XXX`中的第$i$行 = `XXX.src`中的第$i$行 + '\t' + `XXX.trg`中的第$i$行。
`XXX`中的第$i$行内容为 `XXX.src`中的第$i$行 和`XXX.trg`中的第$i$行连接，用'\t'分隔。

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +- 创建训练数据的“源字典”和“目标字典”。每个字典都有**DICTSIZE**个单词，包括：词频最高的（DICTSIZE - 3）个单词，和3个特殊符号`<s>`（序列的开始）、`<e>`（序列的结束）和`<unk>`（未包含在字典中的单词）。
词频最高的->语料中词频最高的

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +- 创建训练数据的“源字典”和“目标字典”。每个字典都有**DICTSIZE**个单词，包括：词频最高的（DICTSIZE - 3）个单词，和3个特殊符号`<s>`（序列的开始）、`<e>`（序列的结束）和`<unk>`（未包含在字典中的单词）。
文中有的地方用`<e>`，有的地方用`<eos>`，需要统一

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +- `-m --mergeDict`：合并 “源字典”和“目标字典”，使得两个字典有相同的上下文
使得两个字典有相同的上下文 没懂
是说源字典和目标字典中词语标号没有重复 的意思吗？

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +2. 其次，使用初始化函数`hook`，分别定义了训练模式和应用（这里为生成）模式下的数据输入格式（`input_types`）。其中`src_dict_path`（源语言字典路径）、`trg_dict_path`（目标语言字典路径）和`is_generating`（训练或生成模式）是从模型配置中传入的对象，调用方式请见[训练模型配置说明](#训练模型配置说明)。
这里还是预先简单说一下训练模式和应用（生成）模式要传入网络的输入和输出吧，不然容易看晕了。。。比如为啥训练的时候还要多给一个tgt_nextword

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   - 在目标语言序列的每句话末尾补上`<s>`，作为目标语言的下一次词序列。
补上`<e>`，笔误了吧？

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   - 在目标语言序列的每句话末尾补上`<s>`，作为目标语言的下一次词序列。
下一次词序列是不是也笔误了？

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +2. 其次，实现基于注意力机制的编码器框架。分为三步：
encoder部分米有基于attention

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   2.1 传入已经在`dataprovider.py`转换成独热编码表示的源语言序列$\mathbf{w}$。
独热编码能用英文还是英文吧。。

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   3.1 对源语言序列编码后的结果，过一个前馈神经网络（Feed Forward Neural Network）。该层是3.3中`simple_attention`函数内部的一个计算步骤，但由于每个时间步该层的计算过程都一样，所以这里提取到外面单独计算以节省时间。
该层是3.3中`simple_attention`函数内部的一个计算步骤，但由于每个时间步该层的计算过程都一样，所以这里提取到外面单独计算以节省时间。
绕糊涂了容易，这句去掉吧。改成“得到源语言RNN状态$h$的映射”

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   3.2 取源语言序列编码后的最后一个词（即反向GRU的第一个词）传给解码阶段的RNN。即$\mathbf{c_0}=\mathbf{h_T}$。
3.2 构造解码器RNN的初始状态。由于解码器需要预测时序目标序列，但在0时刻并没有初始值，所以我们希望对其进行初始化。这里采用的是将源语言序列逆序编码后的最后一个状态进行非线性映射，作为该初始值。

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   3.3 定义解码阶段每一个时间步的RNN行为，即计算每一个时间步的隐层状态$z_i$和词概率$p_i$。
3.3 定义解码阶段每一个时间步的RNN行为，即根据当前时刻的上下文$c_i$、解码器隐层状态$z_i$和目标语言中第$i$个词$u_i$预测第$i+1$个词的概率$p_i$。

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +      - decoder_mem记录了前一个时间步的隐层状态$z_i$，其初始状态是decoder_boot，即$\mathbf{z_0}=\mathbf{c_0}$）。
去掉“，即$\mathbf{z_0}=\mathbf{c_0}$）”

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +4. 根据配置模式的不同，调用基于注意力机制的解码器框架。
4. 训练模式与生成模式下的解码器区别

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   4.1 定义解码器框架名字，和`gru_decoder_with_attention`函数的前两个输入。注意：这两个输入使用`StaticInput`，说明它们都是只读的memory，即4.2中的`recurrent_group`函数不会按时间步对它们拆解，而是引用整个输入。具体说明可见[StaticInput文档](https://github.com/PaddlePaddle/Padd
4.1 训练模式下的解码器

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   4.1 定义解码器框架名字，和`gru_decoder_with_attention`函数的前两个输入。注意：这两个输入使用`StaticInput`，说明它们都是只读的memory，即4.2中的`recurrent_group`函数不会按时间步对它们拆解，而是引用整个输入。具体说明可见[StaticInput文档](https://github.com/PaddlePaddle/Padd
这一节原有内容去掉。也最好不要涉及readonly memory和拆解。StaticInput就放那，用户真想琢磨的时候会去看代码的，现在讲这个可能会吓跑了。。。

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   4.3 应用模式下的调用：
4.1 应用（生成）模式下的解码器

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +   4.3 应用模式下的调用：
4.2 应用（生成）模式下的解码器

2017-01-05 15:32 UTC, Zrachel commented on machine_translation/README.md
> +本教程的BLEU评估命令如下（即默认使用`data/wmt14/gen/ntst14.trg`作为标准的翻译结果）：
如果有BLEU值结果的话，给一个？

2017-01-07 08:46 UTC, schinger reviewed
一些建议

2017-01-07 08:46 UTC, schinger commented on machine_translation/README.md
> +端到端的神经网络机器翻译是近几年兴起的一种全新的机器翻译方法。本章中，我们介绍了NMT中典型的“编码器-解码器”框架和“注意力”机制。由于NMT属于更抽象的Seq2Seq（Sequence to Sequence，序列到序列）问题，因此，Seq2Seq中的query改写（query rewriting）、图像描述（image captioning）等问题都可以用本教程的模型来解决。
图像描述（image captioning）不属于seq2seq问题。摘要，单轮对话属于

2017-01-07 08:46 UTC, schinger commented on machine_translation/README.md
> +### GRU
说明GRU属于RNN的扩展或变体，增加指向情感分析那章rnn的链接

2017-01-07 08:46 UTC, schinger commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
‘编码阶段将整个源序列压缩成一个固定维度的向量’  和下文中的描述‘编码阶段也可使用双向GRU... ...最后对于词$x_i$，通过连接两个GRU的结果得到它的隐层状态，即$h_i=\left [ \overrightarrow{h_i^T},\overleftarrow{h_i^T} \right ]^{T}$。 ’不一致， 建议修改表达方式。

2017-01-07 08:46 UTC, schinger commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
‘依次压缩源语言端词’，这一表达不太好吧。

2017-01-07 08:46 UTC, schinger commented on machine_translation/README.md
> +$$p\left ( u_i|u_{<i},\mathbf{x} \right )=softmax(W_sz_i+b_z)$$
上文都是$z_{i+1}$，$p_{i+1}$。这里又变成描述$u_{i}$，$z_{i}$，$p_{i}$

2017-01-10 09:18 UTC, luotao1 reviewed
意见已全部修改完毕，同时加上了之前忘记上传的eval_bleu.sh脚本

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +传统机器翻译，是让语言学家编写两种语言之间的转换规则，再将这些规则录入给计算机。但该方法对语言学家的要求非常高，并且，我们不可能知道一门语言究竟有多少隐含的使用规则，更何况两种甚至更多的语言。因此，传统机器翻译方法面临的主要挑战是无法得到一个完备的规则集合。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +统计机器翻译（Statistical Machine Translation, SMT），其转化规则是由机器自动从大规模的语料中学习得到的，而非我们人主动提供规则。因此，它克服了传统方法面临的知识获取瓶颈问题，但仍然存在许多挑战：1）需要人为设计许多特征，但永远无法覆盖所有的语言规则；2）难以利用全局的特征；3）依赖于许多预处理环节，如词语对齐、中文分词、规则抽取、句法分析等，而每个环节的错误会
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +统计机器翻译（Statistical Machine Translation, SMT），其转化规则是由机器自动从大规模的语料中学习得到的，而非我们人主动提供规则。因此，它克服了传统方法面临的知识获取瓶颈问题，但仍然存在许多挑战：1）需要人为设计许多特征，但永远无法覆盖所有的语言规则；2）难以利用全局的特征；3）依赖于许多预处理环节，如词语对齐、中文分词、规则抽取、句法分析等，而每个环节的错误会
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。这类系统又大致分为两类：1）（见图1的左半部分）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块，如翻译模型、语言模型、调序模型等；2）（见图1的右半部分）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言，即端到端的神经网络机器翻译（Neural Machine Translation, NMT）。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +当法英翻译的模型训练完毕后，以下面的两句法语为例：
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +### GRU
在GRU介绍中已补充。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +GRU\[[1](#参考文献)\]是Cho等人在LSTM上提出的简化版本，如下图所示。GRU单元只有两个门，分别是重置门（Reset Gate）和更新门（Update Gate），用于控制记忆内容是否能继续保存下去。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +双向RNN的每一个训练序列，向前和向后分别是两个循环神经网络（RNN），而且都连接着一个输出层。这个结构提供给输出层：输入序列中每一个点完整的过去和未来的下文信息。下图展示的是一个按时间步展开的双向循环神经网络。该网络包含一个前向（forward）和一个后向（backward）RNN，其中有六个权值：输入到前向隐层和后向隐层（$w_1, w_3$），隐层到隐层自己（$w_2,w_5$），前向隐层
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +双向RNN的每一个训练序列，向前和向后分别是两个循环神经网络（RNN），而且都连接着一个输出层。这个结构提供给输出层：输入序列中每一个点完整的过去和未来的下文信息。下图展示的是一个按时间步展开的双向循环神经网络。该网络包含一个前向（forward）和一个后向（backward）RNN，其中有六个权值：输入到前向隐层和后向隐层（$w_1, w_3$），隐层到隐层自己（$w_2,w_5$），前向隐层
Done. 改成：这样输出层的每个节点都包含了输入序列中当前时刻完整的过去和未来的下文信息。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
Done，下文的压缩全改了

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +- 独热编码（one-hot coding，1-of-K coding）表示：将源语言句子$x=\left \{ x_1,x_2,...,x_T \right \}$的每个词表示成一个向量$w_i\epsilon R^{\left | V \right |},i=1,2,...,T$ （T暂不包括句子结束标记`<EOS>`）。这个向量的维度与词汇表大小$\left | V \right |$ 相
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +- 独热编码（one-hot coding，1-of-K coding）表示：将源语言句子$x=\left \{ x_1,x_2,...,x_T \right \}$的每个词表示成一个向量$w_i\epsilon R^{\left | V \right |},i=1,2,...,T$ （T暂不包括句子结束标记`<EOS>`）。这个向量的维度与词汇表大小$\left | V \right |$ 相
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码阶段也可使用双向GRU，即一个词的隐层状态不仅编码了前面词的信息，还编码了后面词的信息。具体来说，前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似得，后向GRU按照$(x_T,x_{T-1},
已改成：依次编码源语言端词。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的上下文向量（context vector）c、解码出来的第$i$个单词$u_i$和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，然后用softmax归一化得到概率分布$p_{i+1}$。训练模式时，根据$p_{i+1}$和目标语言词在字典中的标签计算代价，重复上述操作，直到目标语言序列中的所有词处理完毕。生成模式时，根据$p_
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +2. 其次，实现基于注意力机制的编码器框架。分为三步：
Done，改成：，实现编码器框架

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +解码阶段的总体思路是：根据源语言句子的上下文向量（context vector）c、解码出来的第$i$个单词$u_i$和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，然后用softmax归一化得到概率分布$p_{i+1}$。训练模式时，根据$p_{i+1}$和目标语言词在字典中的标签计算代价，重复上述操作，直到目标语言序列中的所有词处理完毕。生成模式时，根据$p_
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +其中$c=h_T$是源语言句子的上下文向量，$z_0$是一个全零的向量，$u_0$是源语言句子的结束标记`<EOS>`。
和 @lcy-seso 确认过，这里是<eos>，表示源语言输入结束和解码开始

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +$$p\left ( u_i|u_{<i},\mathbf{x} \right )=softmax(W_sz_i+b_z)$$
已统一修改为 i+1 的表示。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +可见，源语言句子的上下文向量由原来的$c$变成了第$i$个$c_i$，即针对每一个待解码的词$u_i$，都有一个特定的$c_i$与之对应。$c_i$的计算公式如下：
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +从公式中可以看出，注意力机制即是通过对各个$h_j$进行加权平均实现的，其中权重$a_{ij}$表示待解码的词$u_i$对每个源词语$h_i$不同程度的注意力。具体权重计算公式见\[[3](#参考文献)\]。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +从公式中可以看出，注意力机制即是通过对各个$h_j$进行加权平均实现的，其中权重$a_{ij}$表示待解码的词$u_i$对每个源词语$h_i$不同程度的注意力。具体权重计算公式见\[[3](#参考文献)\]。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +集束搜索算法使用广度优先策略建立搜索树，在树的每一层，按照启发代价（Heuristic Cost）（本教程中，为生成词的概率）对节点进行排序，然后仅留下预先确定的个数（Beam Width，Beam Size，集束宽度）的节点。只有这些节点会在下一层继续扩展，其他节点就被剪掉了，也就是说保留了质量较高的节点，剪掉了质量较差的节点。因此，搜索所占用的空间和时间大幅减少，但缺点是可能存在最优解被丢弃
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +  - `XXX`中的第$i$行 = `XXX.src`中的第$i$行 + '\t' + `XXX.trg`中的第$i$行。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +- 创建训练数据的“源字典”和“目标字典”。每个字典都有**DICTSIZE**个单词，包括：词频最高的（DICTSIZE - 3）个单词，和3个特殊符号`<s>`（序列的开始）、`<e>`（序列的结束）和`<unk>`（未包含在字典中的单词）。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +- 创建训练数据的“源字典”和“目标字典”。每个字典都有**DICTSIZE**个单词，包括：词频最高的（DICTSIZE - 3）个单词，和3个特殊符号`<s>`（序列的开始）、`<e>`（序列的结束）和`<unk>`（未包含在字典中的单词）。
全部统一成`<e>`了

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +- `-m --mergeDict`：合并 “源字典”和“目标字典”，使得两个字典有相同的上下文
已修改：合并“源字典”和“目标字典”，即这两个字典的内容完全一样。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   - 在目标语言序列的每句话末尾补上`<s>`，作为目标语言的下一次词序列。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   - 在目标语言序列的每句话末尾补上`<s>`，作为目标语言的下一次词序列。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +2. 其次，使用初始化函数`hook`，分别定义了训练模式和应用（这里为生成）模式下的数据输入格式（`input_types`）。其中`src_dict_path`（源语言字典路径）、`trg_dict_path`（目标语言字典路径）和`is_generating`（训练或生成模式）是从模型配置中传入的对象，调用方式请见[训练模型配置说明](#训练模型配置说明)。
Done。讲了输入。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   2.1 传入已经在`dataprovider.py`转换成独热编码表示的源语言序列$\mathbf{w}$。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   3.1 对源语言序列编码后的结果，过一个前馈神经网络（Feed Forward Neural Network）。该层是3.3中`simple_attention`函数内部的一个计算步骤，但由于每个时间步该层的计算过程都一样，所以这里提取到外面单独计算以节省时间。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   3.2 取源语言序列编码后的最后一个词（即反向GRU的第一个词）传给解码阶段的RNN。即$\mathbf{c_0}=\mathbf{h_T}$。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   3.3 定义解码阶段每一个时间步的RNN行为，即计算每一个时间步的隐层状态$z_i$和词概率$p_i$。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +      - decoder_mem记录了前一个时间步的隐层状态$z_i$，其初始状态是decoder_boot，即$\mathbf{z_0}=\mathbf{c_0}$）。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +4. 根据配置模式的不同，调用基于注意力机制的解码器框架。
Done。改为”训练模式与生成模式下的解码器调用区别‘

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   4.1 定义解码器框架名字，和`gru_decoder_with_attention`函数的前两个输入。注意：这两个输入使用`StaticInput`，说明它们都是只读的memory，即4.2中的`recurrent_group`函数不会按时间步对它们拆解，而是引用整个输入。具体说明可见[StaticInput文档](https://github.com/PaddlePaddle/Padd
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +   4.1 定义解码器框架名字，和`gru_decoder_with_attention`函数的前两个输入。注意：这两个输入使用`StaticInput`，说明它们都是只读的memory，即4.2中的`recurrent_group`函数不会按时间步对它们拆解，而是引用整个输入。具体说明可见[StaticInput文档](https://github.com/PaddlePaddle/Padd
4.1 不变。4.2改为：训练模式下的解码器调用。4.3改为：生成模式下的解码器调用。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +端到端的神经网络机器翻译是近几年兴起的一种全新的机器翻译方法。本章中，我们介绍了NMT中典型的“编码器-解码器”框架和“注意力”机制。由于NMT属于更抽象的Seq2Seq（Sequence to Sequence，序列到序列）问题，因此，Seq2Seq中的query改写（query rewriting）、图像描述（image captioning）等问题都可以用本教程的模型来解决。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +本教程的BLEU评估命令如下（即默认使用`data/wmt14/gen/ntst14.trg`作为标准的翻译结果）：
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。这类系统又大致分为两类：1）（见图1的左半部分）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块，如翻译模型、语言模型、调序模型等；2）（见图1的右半部分）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言，即端到端的神经网络机器翻译（Neural Machine Translation, NMT）。
去掉了翻译模型

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +- 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，最后得到的$h_T$就是整个源语言句子的编码。
表示一个非线性激活函数，已修改。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[1](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列压缩成一个固定维度的向量，解码阶段以概率的方式从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现，但由于普通的RNN存在梯度消失和梯度爆炸问题，因此会引入LSTM或GRU。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +在上述框架中，由于编码阶段压缩成的固定维度的向量，需要包含源语言序列的所有信息，对于长句子而言很难达到的。因此，Bahdanau等人\[[3](#参考文献)\]引入注意力（Attention）机制，其基本思想是目标语言端的词，往往只和源语言端的部分词相关。下面介绍在注意力机制的解码器结构。
向 @lcy-seso 请教后，已重新修改。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +在上述框架中，由于编码阶段压缩成的固定维度的向量，需要包含源语言序列的所有信息，对于长句子而言很难达到的。因此，Bahdanau等人\[[3](#参考文献)\]引入注意力（Attention）机制，其基本思想是目标语言端的词，往往只和源语言端的部分词相关。下面介绍在注意力机制的解码器结构。
向 @lcy-seso 请教后，已重新修改。

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +从公式中可以看出，注意力机制即是通过对各个$h_j$进行加权平均实现的，其中权重$a_{ij}$表示待解码的词$u_i$对每个源词语$h_i$不同程度的注意力。具体权重计算公式见\[[3](#参考文献)\]。
Done

2017-01-10 09:18 UTC, luotao1 commented on machine_translation/README.md
> +GRU\[[1](#参考文献)\]是Cho等人在LSTM上提出的简化版本，如下图所示。GRU单元只有两个门，分别是重置门（Reset Gate）和更新门（Update Gate），用于控制记忆内容是否能继续保存下去。
Done

2017-01-10 09:53 UTC, Zrachel reviewed
背景介绍&效果展示

2017-01-10 09:53 UTC, Zrachel commented on machine_translation/README.md
> +喷气机制造商为了座位宽度的问题与利益攸关的大客户发生争执。
删除多余行

2017-01-10 09:53 UTC, Zrachel commented on machine_translation/README.md
>  如果设定显示翻译结果的条数（即[集束搜索算法](#集束搜索算法)的宽度）为3，生成的英语句子如下：
如果设定显示翻译结果的条数（即[集束搜索算法](#集束搜索算法)的宽度）为3，训练一段时间后，模型得到其英文翻译如下：

“训练一段时间后”主要是感觉。。下面这个翻译的结果太烂了，不好意思是说最终结果。。。

2017-01-10 09:53 UTC, Zrachel commented on machine_translation/README.md
> +以中英翻译（中文翻译到英文）的模型为例，当模型训练完毕时，如果输入如下中文句子：
以中英翻译（中文翻译到英文）的模型为例，输入如下中文句子：

2017-01-10 09:53 UTC, Zrachel commented on machine_translation/README.md
> +- 重置门（Reset Gate）：如果重置门关闭，会忽略掉历史信息，即历史不相干的信息不会影响未来的输出。
如果重置门关闭
是
如果重置门开启
吧？

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +我们已经在[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/README.md)一章中介绍了双向循环神经网络(bi-RNN)和其中的一种网络结构。这里介绍Bengio等人在论文\[[2](#参考文献),[4](#参考文献)\]中提出的另一种结构。
“(bi-RNN)和其中的一种网络结构。” 去掉

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +该双向RNN网络分别在时间维顺序和逆序（即前向和后向）输入一个RNN，并将每个时刻的输出分别连接到输出层。这样输出层的每个节点都包含了输入序列中当前时刻完整的过去和未来的下文信息。下图展示的是一个按时间步展开的双向RNN网络。该网络包含一个前向（forward）和一个后向（backward）RNN，其中有六个权值：输入到前向隐层和后向隐层（$w_1, w_3$），隐层到隐层自己（$w_2,w_5
这样输出层的每个节点都包含了输入序列中当
-》
这样每个时间步的输出节点都包含了输入序列中当

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +2. 映射到低维语义空间的词向量：one-hot vector表示存在两个问题，1）生成的向量维度往往很大，容易造成维数灾难；2）无法刻画词与词之间的关系（如语义相似性，也就是无法很好地表达语义）。因此，需再映射到低维的语义空间，由一个固定维度的稠密向量（称为词向量）表示。记映射矩阵为$C\epsilon R^{K\times \left | V \right |}$，用$s_i=Cw_i$表示
向量维度$K$通常取100-500之间。
如果有出处，请加引用；
如果没出处，建议删除；

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +3. 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，$\varnothing _\theta$是一个非线性激活函数，最后得到的$\mathbf{h}=\left \{ h_1,..., h_T \right \}$就是整个源语言句子的编码。注意：如果不使
就是整个源语言句子的编码
->
就是RNN依次读入源语言T个词的状态编码。

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +3. 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，$\varnothing _\theta$是一个非线性激活函数，最后得到的$\mathbf{h}=\left \{ h_1,..., h_T \right \}$就是整个源语言句子的编码。注意：如果不使
注意：如果不使用[注意力机制](#注意力机制)，需要将$\mathbf{h}$再编码成一个固定维度的向量，如可以直接取最后一个元素，或使用时间维上最大池化（max pooling）或平均池化（average pooling）操作得到所有元素的最大值或平均值，等。

这句话，删掉？或者改成：

整句话的向量表示可以采用$\mathbf{h}在最后一个时间步$T$的状态向量，或使用时间维上的池化（pooling）结果。

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +- 训练模式：目标是最大化真实翻译目标语言序列的概率，即根据$p_{i+1}$和目标语言词在字典中的标签计算代价，重复上述操作，直到目标语言序列中的所有词处理完毕。
目标语言词在字典中的标签
->
$u_{i+1}$

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +机器翻译任务中，解码阶段的总体思路是：每一个时刻，根据源语言句子的编码信息（又叫上下文向量，context vector）$c$、目标语言序列的第$i$个单词$u_i$和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，并通过`softmax`归一化得到目标语言序列的第$i+1$个单词的概率分布$p_{i+1}$。
这里还得改一下。
训练时，用的是 groundtruth 中目标语言序列的第$i$个单词；生成时，用的是目标语言序列生成的第$i$个单词

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +其中$\phi _{\theta '}$是一个非线性激活函数；$c=q\mathbf{h}$是源语言句子的上下文向量，在不使用[注意力机制](#注意力机制)时，如果[编码器](#编码器)的输出是源语言句子编码后的最后一个元素，则可以定义$c=h_T$；$u_i$是目标语言序列的第$i$个单词，$u_0$是源语言句子的结束标记`<e>`，表示源语言输入结束和解码开始；$z_i$是$i$时刻解码RN
结束标记`<e>`
->
开始标记`<s>`

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +如果编码阶段的输出是一个固定维度的向量，会带来以下三个问题：1）不论源语言序列的长度是5个词还是50个词，如果都用固定维度的向量去编码其中的语义和句法结构信息，对模型来说是一个非常高的要求，特别是对长句子序列而言；2）从直觉出发，当翻译目标语言时，我们并不需要知道整个源语言序列，而只要知道当前翻译到源语言的哪个位置和这个位置前后的一个上下文片段即可；3）任何时候都拿到源语言的所有信息，实际上也是
`1) 2) 3) `如果有引用，加引用；否则，感觉3）的说法不太准确。因为其实attention还是拿到了所有信息，只是做了加权

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +其中，align可以看作是一个对齐模型，用来衡量目标语言中第$i$个词和源语言中第$j$个词的匹配程度。具体而言，这个程度是通过解码RNN的第$i$个隐层状态$z_i$和源语言句子的第$j$个上下文片段$h_j$计算得到的。不同于传统的对齐模型：目标语言的每个词明确对应源语言的一个或多个词（hard alignment）。这里采用的是soft alignment，因此可以融入整个NMT框架，并通
align -》 $align$

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +集束搜索（[Beam Search](http://en.wikipedia.org/wiki/Beam_search)）是一种启发式图搜索算法，通常用在解空间较大的系统中，如机器翻译、语音识别等。原因是这些系统的数据集通常非常大，而且也没有唯一正确解，因此用最快的方法找到最接近正确的解才是系统的目标。
集束搜索（[Beam Search](http://en.wikipedia.org/wiki/Beam_search)）是一种启发式图搜索算法，用于在图或树中搜索有限集合中的最优扩展节点。在解空间非常大的系统中，内存无法装下图/树中所有展开的解，就用到了集束搜索。如在机器翻译任务中希望翻译“`<s>你好<e>`”，就算目标语言字典中只有3个词（`<s>, <e>, hello`），也可能生成无限句话（通过hello循环出现N次）。为了找到其中最好的翻译结果，我们采用集束搜索算法。

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +- `-m --mergeDict`：合并“源字典”和“目标字典”，即这两个字典的内容完全一样。
即这两个字典的内容完全一样
->
即使这两个字典的内容完全一样

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +   - 在目标语言序列的每句话末尾补上`<e>`，作为目标语言的下一个词序列。
说清楚是target_language_word还是target_language_next_word吧

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +      - decoder_inputs记录了$c_i$和当前目标词current_word（即$u_i$）。
decoder_inputs融合了$c_i$和当前目标词current_word（即$u_i$）的表示。

2017-01-10 12:37 UTC, Zrachel commented on machine_translation/README.md
> +      - 接着，使用目标语言的下一个词序列作为标签层lbl。
使用目标语言的下一个词序列作为标签层lbl
->
使用目标语言的下一个词序列作为标签层lbl，即预测目标词。

2017-01-13 05:38 UTC, lcy-seso reviewed
some suggestions for modification.

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +
"但该方法对语言学家的要求非常高" 第一个 “但”去掉更顺畅一些。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +
”统计机器翻译（Statistical Machine Translation, SMT），其转化规则是由机器自动从大规模的语料中学习得到的“
改成 “在统计机器翻译（Statistical Machine Translation, SMT）中，转化规则是由机器自动从大规模的语料中学习得到的”

“它克服了传统方法面临的知识获取瓶颈问题”，加一个 “的”， ”它克服了传统方法面临的知识获取瓶颈的问题“

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +
`<unk>`表示无法识别 ，改为： `<unk>`表示未登录词。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +我们已经在[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/README.md)一章中介绍了双向循环神经网络(bi-RNN)和其中的一种网络结构。这里介绍Bengio等人在论文\[[2](#参考文献),[4](#参考文献)\]中提出的另一种结构。
或者改为：”我们已经在语义角色标注一章中介绍了一种双向循环神经网络，这里介绍……“

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +该双向RNN网络分别在时间维顺序和逆序（即前向和后向）输入一个RNN，并将每个时刻的输出分别连接到输出层。这样输出层的每个节点都包含了输入序列中当前时刻完整的过去和未来的下文信息。下图展示的是一个按时间步展开的双向RNN网络。该网络包含一个前向（forward）和一个后向（backward）RNN，其中有六个权值：输入到前向隐层和后向隐层（$w_1, w_3$），隐层到隐层自己（$w_2,w_5
第一句话因为重复的词有点多，所以读着有点迷惑。。

”该双向RNN网络分别在时间维以顺序和逆序（即前向和后向）依次处理输入序列，并将每个时刻 RNN 的输出横向拼接成为最终的输出层“ （类似这样）

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +3. 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，$\varnothing _\theta$是一个非线性激活函数，最后得到的$\mathbf{h}=\left \{ h_1,..., h_T \right \}$就是整个源语言句子的编码。注意：如果不使
和睿卿意见基本一致。这里先不要提注意力机制。下面再引入。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +- 生成模式：目标是预测目标语言序列，即根据$p_{i+1}$采样出单词$u_{i+1}$，重复上述操作，直到获得句子结束标记`<e>`或超过句子的最大生成长度为止。
训练模式：目标是最大化下一个正确的源语言词的概率。
生成模式：目标是最大化生成序列的概率，但是这一次过程都是通过贪心法实现，并不能保证得到全局最优解。

nmt 的优化目标是基于词，而不是句子。这本身也是一个问题。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +其中$\phi _{\theta '}$是一个非线性激活函数；$c=q\mathbf{h}$是源语言句子的上下文向量，在不使用[注意力机制](#注意力机制)时，如果[编码器](#编码器)的输出是源语言句子编码后的最后一个元素，则可以定义$c=h_T$；$u_i$是目标语言序列的第$i$个单词，$u_0$是源语言句子的结束标记`<e>`，表示源语言输入结束和解码开始；$z_i$是$i$时刻解码RN
@Zrachel 这里确实是一种“有点饶”的写法。上面的本意应该是源语言的结束<e>，标志着目标语言的开始。
具体在paddle 配置里面执行逻辑不是这样的，而且和符号表示会对不上。应该改为：

$u_0$ 是目标语言句子的开始标记 <s>

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +如果编码阶段的输出是一个固定维度的向量，会带来以下三个问题：1）不论源语言序列的长度是5个词还是50个词，如果都用固定维度的向量去编码其中的语义和句法结构信息，对模型来说是一个非常高的要求，特别是对长句子序列而言；2）从直觉出发，当翻译目标语言时，我们并不需要知道整个源语言序列，而只要知道当前翻译到源语言的哪个位置和这个位置前后的一个上下文片段即可；3）任何时候都拿到源语言的所有信息，实际上也是
@Zrachel 我觉得没有问题。这个就是attention 的 motivation 。实际上，attention 计算出来的会是一个窗口，窗口之外的权值基本上都是 0 了。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +集束搜索算法使用广度优先策略建立搜索树，在树的每一层，按照启发代价（Heuristic Cost）（本教程中，为生成词的概率）对节点进行排序，然后仅留下预先确定的个数（Beam Width，Beam Size，集束宽度）的节点。只有这些节点会在下一层继续扩展，其他节点就被剪掉了，也就是说保留了质量较高的节点，剪枝了质量较差的节点。因此，搜索所占用的空间和时间大幅减少，但缺点是可能存在最优解被丢弃
本教程中，为生成词的概率 --> 本教程中，为生成词的 log 概率之和。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +
把`<unk>` 都改为未登录词吧。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +- `-m --mergeDict`：合并“源字典”和“目标字典”，即这两个字典的内容完全一样。
应该就是 “即”不是“即使”

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +- `train`、`test`和`gen`：分别包含了法英平行语料库的训练、测试和生成数据。其每个文件的每一行均分为两部分，前半部分是法语序列，后半部分是对应的英语序列。
“其每个文件的每一行均分为两部分，前半部分是法语序列，后半部分是对应的英语序列。”
这句话改为：

“其每个文件的每一行以“\t”分为2列，第一列是法语序列，第2列是对应的英语序列。”

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +   UNK_IDX = 2    #未包含在字典中的单词
UNK 都改成“未登录词”吧

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +   - 生成模式：有两个输入序列，其中“源语言序列”作为生成数据，“源语言序列编号”作为生成数据的编号（该输入非必须，可以省略）。
其中“源语言序列”作为生成数据 --> 其中“源语言序列”作为输入数据，原来那样写，很容易有歧义。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +   - 训练模式：有三个输入序列，其中“源语言序列”和“目标语言序列”作为训练数据，“目标语言的下一个词序列”作为标签数据。
其中“源语言序列”和“目标语言序列”作为训练数据，

这句话改为：其中“源语言序列”和“目标语言序列”作为输入数据，

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +1. 首先，定义数据集路径和源/目标语言字典路径，并用`is_generating`变量定义当前配置是训练模式（默认）还是应用模式。该变量接受从命令行传入的参数，使用方法见[应用命令与结果](#应用命令与结果)。
“是训练模式（默认）还是应用模式”，还是直接写成： “是训练模式（默认）还是生成模式”吧，直接没歧义。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +本教程使用默认的SGD随机梯度下降算法和Adam学习方法。在训练过程中，指定batch_size为50，学习率是5e-4；在应用过程中，batch_size为1（每次生成1个序列），学习率为0。
在应用过程中 --> 直接就叫：在生成过程中
要不要在这里写，也可以一次生成多个序列，不然，很多用户会认为只能一个一个生成。
生成时候的学习率随便设，没有用。这里应该就删掉这个学习率 0 ，容易有无解。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +```
learning_rate = 5e-4， 并不需要在生成时改变学习率，容易有误解。
而且，这个batch size 也可以不用改的。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +
我觉得“应用模式”很奇怪，在论文里和通常的参考资料里面，直接就叫做 “生成”，所以我们并不需要重新起一个名字。

推测是不是为了配合“应用模型”一节。这个模型应用的时候，也不是只能生成，还可以直接求概率。所以，叫“应用模式” 会不准确。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +由于机器翻译模型的训练非常耗时，我们在50个物理节点（每节点含有2颗6核CPU）的集群中，花了5天时间训练了16个pass，其中每个pass耗时7个小时。因此，我们提供了一个预训练好的模型（pass-00012）供大家直接下载使用。该模型大小为205MB，在所有16个模型中有最高的[BLEU评估](#BLEU评估)值26.92。下载并解压模型的命令如下：
预训练好的模型 --> 预先训练好的模型

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +
有一个 issue 里面也提到，现在这个 配置和 Bengio 论文不完全一样，要不在算softmax 概率这里加一句说明。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +- config_args：将命令行中的自定义参数传递给模型配置。`is_generating=1`表示当前为生成模式，`gen_trans_file="gen_result"`表示生成结果的存储文件。
这里写的是“生成模式”，还是把“应用模式”都改成生成模式吧。

2017-01-13 05:38 UTC, lcy-seso commented on machine_translation/README.md
> +
由于NMT属于更抽象的Seq2Seq --> NMT 是一个典型的 Seq2Seq 学习问题，

2017-01-16 07:30 UTC, luotao1 reviewed
已全部修改完

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +   UNK_IDX = 2    #未包含在字典中的单词
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +我们已经在[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/README.md)一章中介绍了双向循环神经网络(bi-RNN)和其中的一种网络结构。这里介绍Bengio等人在论文\[[2](#参考文献),[4](#参考文献)\]中提出的另一种结构。
按照 @lcy-seso 的进行修改了

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +该双向RNN网络分别在时间维顺序和逆序（即前向和后向）输入一个RNN，并将每个时刻的输出分别连接到输出层。这样输出层的每个节点都包含了输入序列中当前时刻完整的过去和未来的下文信息。下图展示的是一个按时间步展开的双向RNN网络。该网络包含一个前向（forward）和一个后向（backward）RNN，其中有六个权值：输入到前向隐层和后向隐层（$w_1, w_3$），隐层到隐层自己（$w_2,w_5
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +2. 映射到低维语义空间的词向量：one-hot vector表示存在两个问题，1）生成的向量维度往往很大，容易造成维数灾难；2）无法刻画词与词之间的关系（如语义相似性，也就是无法很好地表达语义）。因此，需再映射到低维的语义空间，由一个固定维度的稠密向量（称为词向量）表示。记映射矩阵为$C\epsilon R^{K\times \left | V \right |}$，用$s_i=Cw_i$表示
已删除。

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +3. 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，$\varnothing _\theta$是一个非线性激活函数，最后得到的$\mathbf{h}=\left \{ h_1,..., h_T \right \}$就是整个源语言句子的编码。注意：如果不使
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +3. 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，$\varnothing _\theta$是一个非线性激活函数，最后得到的$\mathbf{h}=\left \{ h_1,..., h_T \right \}$就是整个源语言句子的编码。注意：如果不使
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +- 生成模式：目标是预测目标语言序列，即根据$p_{i+1}$采样出单词$u_{i+1}$，重复上述操作，直到获得句子结束标记`<e>`或超过句子的最大生成长度为止。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +- 训练模式：目标是最大化真实翻译目标语言序列的概率，即根据$p_{i+1}$和目标语言词在字典中的标签计算代价，重复上述操作，直到目标语言序列中的所有词处理完毕。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +机器翻译任务中，解码阶段的总体思路是：每一个时刻，根据源语言句子的编码信息（又叫上下文向量，context vector）$c$、目标语言序列的第$i$个单词$u_i$和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，并通过`softmax`归一化得到目标语言序列的第$i+1$个单词的概率分布$p_{i+1}$。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +其中$\phi _{\theta '}$是一个非线性激活函数；$c=q\mathbf{h}$是源语言句子的上下文向量，在不使用[注意力机制](#注意力机制)时，如果[编码器](#编码器)的输出是源语言句子编码后的最后一个元素，则可以定义$c=h_T$；$u_i$是目标语言序列的第$i$个单词，$u_0$是源语言句子的结束标记`<e>`，表示源语言输入结束和解码开始；$z_i$是$i$时刻解码RN
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +如果编码阶段的输出是一个固定维度的向量，会带来以下三个问题：1）不论源语言序列的长度是5个词还是50个词，如果都用固定维度的向量去编码其中的语义和句法结构信息，对模型来说是一个非常高的要求，特别是对长句子序列而言；2）从直觉出发，当翻译目标语言时，我们并不需要知道整个源语言序列，而只要知道当前翻译到源语言的哪个位置和这个位置前后的一个上下文片段即可；3）任何时候都拿到源语言的所有信息，实际上也是
@Zrachel 这段是按照 @lcy-seso 的意见改的，因此先维持原状。

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +其中，align可以看作是一个对齐模型，用来衡量目标语言中第$i$个词和源语言中第$j$个词的匹配程度。具体而言，这个程度是通过解码RNN的第$i$个隐层状态$z_i$和源语言句子的第$j$个上下文片段$h_j$计算得到的。不同于传统的对齐模型：目标语言的每个词明确对应源语言的一个或多个词（hard alignment）。这里采用的是soft alignment，因此可以融入整个NMT框架，并通
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +集束搜索（[Beam Search](http://en.wikipedia.org/wiki/Beam_search)）是一种启发式图搜索算法，通常用在解空间较大的系统中，如机器翻译、语音识别等。原因是这些系统的数据集通常非常大，而且也没有唯一正确解，因此用最快的方法找到最接近正确的解才是系统的目标。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +集束搜索算法使用广度优先策略建立搜索树，在树的每一层，按照启发代价（Heuristic Cost）（本教程中，为生成词的概率）对节点进行排序，然后仅留下预先确定的个数（Beam Width，Beam Size，集束宽度）的节点。只有这些节点会在下一层继续扩展，其他节点就被剪掉了，也就是说保留了质量较高的节点，剪枝了质量较差的节点。因此，搜索所占用的空间和时间大幅减少，但缺点是可能存在最优解被丢弃
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +- `-m --mergeDict`：合并“源字典”和“目标字典”，即这两个字典的内容完全一样。
保持原来的“即”不变

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +- `train`、`test`和`gen`：分别包含了法英平行语料库的训练、测试和生成数据。其每个文件的每一行均分为两部分，前半部分是法语序列，后半部分是对应的英语序列。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +   - 训练模式：有三个输入序列，其中“源语言序列”和“目标语言序列”作为训练数据，“目标语言的下一个词序列”作为标签数据。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +   - 生成模式：有两个输入序列，其中“源语言序列”作为生成数据，“源语言序列编号”作为生成数据的编号（该输入非必须，可以省略）。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +   - 在目标语言序列的每句话末尾补上`<e>`，作为目标语言的下一个词序列。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +1. 首先，定义数据集路径和源/目标语言字典路径，并用`is_generating`变量定义当前配置是训练模式（默认）还是应用模式。该变量接受从命令行传入的参数，使用方法见[应用命令与结果](#应用命令与结果)。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +```
Done，也修改了对应的源码

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +本教程使用默认的SGD随机梯度下降算法和Adam学习方法。在训练过程中，指定batch_size为50，学习率是5e-4；在应用过程中，batch_size为1（每次生成1个序列），学习率为0。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +      - decoder_inputs记录了$c_i$和当前目标词current_word（即$u_i$）。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +      - 接着，使用目标语言的下一个词序列作为标签层lbl。
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +由于机器翻译模型的训练非常耗时，我们在50个物理节点（每节点含有2颗6核CPU）的集群中，花了5天时间训练了16个pass，其中每个pass耗时7个小时。因此，我们提供了一个预训练好的模型（pass-00012）供大家直接下载使用。该模型大小为205MB，在所有16个模型中有最高的[BLEU评估](#BLEU评估)值26.92。下载并解压模型的命令如下：
Done

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +- config_args：将命令行中的自定义参数传递给模型配置。`is_generating=1`表示当前为生成模式，`gen_trans_file="gen_result"`表示生成结果的存储文件。
全部改成生成模式了

2017-01-16 07:30 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-17 03:15 UTC, lcy-seso reviewed
example in section 2 is not appropriate.

2017-01-17 03:15 UTC, lcy-seso commented on machine_translation/README.md
> +
“传统机器翻译方法面临的主要挑战是无法得到一个完备的规则集合” 这句话不太合适，

“即使有了完备的规则集合，如何decoding也还是有挑战” from @pengli09

2017-01-17 03:15 UTC, lcy-seso commented on machine_translation/README.md
> +```text
这个例子这么干不合适，因为不是机器翻译出来的。
（1）中英翻译，中文应该给出分词的结果；
（2）这个例子里面，语序差别这么大，而且不是中文词和英文词对应过来，也就是说对齐也不是非常明显，这个机器很难翻译。

教程不仅仅是给学生看，如果是做相关研究的研究者看到这个例子。非常容易造成误解。

我们曾经训练过中英翻译，找相关同学要一个结果，或者就直接用英法翻译。这样放一个并不是机器翻译出来的结果。不合适。

2017-01-17 07:42 UTC, Zrachel commented on machine_translation/README.md
> +- 更新门（Update Gate）：将LSTM的输入门和遗忘门合并，用于控制历史信息对当前输出的影响。如果更新门接近1，会把历史信息传递下去。
更新门（Update Gate）：将LSTM中的输入门和遗忘门合并，用于控制历史信息对当前时刻隐层输出的影响。

2017-01-17 07:42 UTC, Zrachel commented on machine_translation/README.md
> +<p align="center">
line45前加：
一般来说，具有短距离依赖属性的序列，其重置门比较活跃，相反具有长距离依赖属性的序列，其更新门比较活跃。

2017-01-17 07:42 UTC, Zrachel commented on machine_translation/README.md
> +我们已经在[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/README.md)一章中介绍了一种双向循环神经网络，这里介绍Bengio等人在论文\[[2](#参考文献),[4](#参考文献)\]中提出的另一种结构。
句末加：
其目的是输入一个序列，得到其在每个时刻的特征表示，当输入为源语言的一个含N个词语的句子时，双向循环神经网络的输出为一个长N的序列，1~N间每个时刻用定长向量表示到该词的上下文语义信息。

这里不提和NMT的关系的话，读者会困惑。。

2017-01-17 07:42 UTC, Zrachel commented on machine_translation/README.md
> +### 编码器-解码器框架
是否改成“NMT的编码器-解码器框架”

2017-01-17 07:42 UTC, Zrachel commented on machine_translation/README.md
> +$$c_i=\sum _{j=1}^{T}\mathbf{a}_{ij}h_j, \mathbf{a}_i=\left[ \mathbf{a}_{i1},\mathbf{a}_{i2},...,\mathbf{a}_{iT}\right ]$$
上下要么都用$a_{ij}$，要么都用$\mathbf{a}_{ij}$，h也是。

2017-01-17 07:42 UTC, Zrachel commented on machine_translation/README.md
> +- 创建训练数据的“源字典”和“目标字典”。每个字典都有**DICTSIZE**个单词，包括：语料中词频最高的（DICTSIZE - 3）个单词，和3个特殊符号`<s>`（序列的开始）、`<e>`（序列的结束）和`<unk>`（未登录词）。
未登录词 改一下

2017-01-17 07:42 UTC, Zrachel commented on machine_translation/README.md
> +      - context通过调用`simple_attention`函数，实现公式$c_i=\sum {j=1}^{T}\mathbf{a}{ij}h_j$。其中，enc_vec是$h_j$，enc_proj是$h_j$的映射（见3.1），权重$\mathbf{a}{ij}$的计算已经封装在`simple_attention`函数中。
\mathbf{a}{ij}写错

2017-01-17 11:13 UTC, pengli09 commented on machine_translation/README.md
> +
"是用计算机来实现不同语言之间的翻译" -> "是用计算机来实现不同语言之间翻译的技术"

2017-01-17 12:53 UTC, pengli09 approved these changes

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +
建议将“传统机器翻译” -> “早期机器翻译系统多为基于规则的翻译系统”
“是让语言学家” -> “需要由语言学家”
“录入给” -> “录入”

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +
第一小句建议改为“为解决以上问题，统计机器翻译（Statistical Machine Translation, SMT）技术应运而生，在统计机器翻译技术中，”
"传统方法"  -> "基于规则的机器翻译系统"
“需要人为设计许多特征” -> "人为设计许多特征（feature）"
“但永远无法覆盖所有的语言规则” -> "但永远无法覆盖所有的语言现象"
“分词（Tokenization）” -> "分词或符号化（Tokenization）"，分词和Tokenization是两个不同的概念，前者一般指中日韩文字符串切成词的操作，后者多指英语等字母语言单词与标点、词缀等的切分过程

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。这类系统又大致分为两类：1）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块，如语言模型、调序模型等（见图1的左半部分）；2）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言，即端到端的神经网络机器翻译（Neural Machine Translation, NMT）（见图1的右半部分）。
“面对上述挑战，一个较好的解决方法是利用神经网络。这类系统又大致分为两类：”  -> “近年来深度学习技术的发展为上述挑战的解决提供了新的思路。将深度学习方法应用于机器翻译任务的方法大致分两类：”
“（Neural Machine Translation, NMT）” -> "（End-to-End Neural Machine Translation, End-to-End NMT）"
在“（见图1的右半部分）。”后面加上“后文简称为NMT模型。”

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +本教程主要介绍NMT模型，以及如何用PaddlePaddle来训练一个翻译模型。
"翻译模型" -> “NMT模型”，注意术语使用的一致性

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +- 右起第一列是生成的英语句子，右起第二列是该条英语句子的得分（从大到小），右起第三列是该条句子的序号。
右起是不是都改成左起，一般大家在看这段文本的时候肯定是从左向右看，但介绍时去是从右向左介绍，可能不太符合用户的阅读习惯
"（从大到小）" -> "（从大到小），分值越高越好"，同时第二个和第三个“右起”前的逗号改成分号吧

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +- 另外有两个特殊表示：`<e>`表示句子的结尾，`<unk>`表示未登录（即不在训练字典中）的单词。
"表示" -> "标志"
"表示未登录（即不在训练字典中）的单词" -> "表示未登录词（unknown word），即未在训练字典中出现的词"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +本节依次介绍GRU（Gated Recurrent Unit，门控循环单元），双向循环神经网络，NMT中典型的“编码器-解码器”（Encoder-Decoder）框架和“注意力”（Attention）机制，以及集束搜索（Beam Search）算法。
"双向循环神经网络" -> "双向循环神经网络（bi-directional recurrent neural network）"
"NMT" -> "NMT模型"
“编码器-解码器”、“注意力”的引号是否去掉？前后文字风格保持一致
“集束搜索（Beam Search）” -> "柱搜索（beam search）" ，机器翻译语境下习惯叫柱搜索，beam search并非专有名词，所以就不大写了吧

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +我们已经在[情感分析](https://github.com/PaddlePaddle/book/blob/develop/understand_sentiment/README.md)一章中介绍了循环神经网络(RNN)及长短时间记忆网络（LSTM）。相比于简单的RNN，LSTM增加了记忆单元、输入门、遗忘门及输出门，这些门及记忆单元组合起来大大提升了RNN处理远距离依赖问题的能力。
"(RNN)" -> 括号变成全角的，前后统一
"记忆单元、输入门、遗忘门及输出门" -> "记忆单元（memory cell）、输入门（input gate）、遗忘门（forget gate）及输出门（output gate）"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +- 更新门（Update Gate）：将LSTM的输入门和遗忘门合并，用于控制历史信息对当前输出的影响。如果更新门接近1，会把历史信息传递下去。
“Update Gate” -> "update gate"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +<p align="center">
Reset Gate -> reset gate

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +图2. GRU门控循环单元
"GRU门控循环单元" -> "GRU（门控循环单元）"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +我们已经在[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/README.md)一章中介绍了一种双向循环神经网络，这里介绍Bengio等人在论文\[[2](#参考文献),[4](#参考文献)\]中提出的另一种结构。
"Bengio等人" -> "Bengio团队"，两篇论文一作都不是Bengio，且Bengio署名位置也很靠后，而在这里只提Bengio，不太合适。所以改成Bengio团队弱化一下吧。

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +### 编码器-解码器框架
"该双向RNN网络" -> "该网络"，如果一定要用全称的话，也请使用“双向循环神经网络”，术语使用要保持一致
"顺序和逆序（即前向和后向）依次" -> "顺序和逆序——即前向（forward）和后向（backward）——依次"
"每个时刻" -> "每个时间步"
"横向拼接" -> "拼接"，“横向拼接”前面没有定义，加上“横向”这个修饰语反而容易让人产生那“纵向拼接是怎么做的“之类的不必要联想
”未来的下文信息“ -> "未来的上下文信息"
"下图展示的是一个按时间步展开的双向RNN网络" -> "下图展示的是一个按时间步展开的双向循环神经网络"
"该网络包含一个前向（forward）和一个后向（backward）RNN" -> "该网络包含一个前向和一个后向RNN"
"六个权值“ -> 是不是应该是权重矩阵？另外后文用w_i表示词向量了，这里要用别的符号，科学文献里比较忌讳的是在同一篇文章里用同一个符号表示不同的东西
"输入到前向隐层和后向隐层" -> "输入到前向隐层和后向隐层的权重矩阵"
“隐层到隐层自己” -> "隐层到隐层自己的权重矩阵"
"前向隐层和后向隐层到输出层" -> "前向隐层和后向隐层到输出层的权重矩阵"
"没有信息流" -> "没有连接"，不要额外引入没有定义的新概念

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +### 编码器-解码器框架
"图3. 按时间步展开的双向RNN网络" -> "图3. 按时间步展开的双向循环神经网络"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[2](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列编码成一个向量，解码阶段通过最大化预测序列概率，从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现。
"解决一个" -> "解决由一个"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +1. one-hot vector（独热向量）表示：将源语言句子$x=\left \{ x_1,x_2,...,x_T \right \}$的每个词表示成一个向量$w_i\epsilon R^{\left | V \right |},i=1,2,...,T$。这个向量的维度与词汇表大小$\left | V \right |$ 相同，并且只有一个维度上有值1（该位置对应该词在词汇表中的位置），其余
"one-hot vector（独热向量）表示"这处有点怪，或者就不加中文翻译，或者此处及后者都使用中文翻译
"每个词表示成一个向量" -> "每个词$x_i$表示成一个列向量"，隐式解释x_i表示什么，以及强调列向量，方便后文第2点中使用
“这个向量” -> "向量$w_i$"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +2. 映射到低维语义空间的词向量：one-hot vector表示存在两个问题，1）生成的向量维度往往很大，容易造成维数灾难；2）无法刻画词与词之间的关系（如语义相似性，也就是无法很好地表达语义）。因此，需再映射到低维的语义空间，由一个固定维度的稠密向量（称为词向量）表示。记映射矩阵为$C\epsilon R^{K\times \left | V \right |}$，用$s_i=Cw_i$表示
“one-hot vector”见上文评论，进行统一
"1）生成的向量维度往往很大，容易造成维数灾难；2）无法刻画词与词之间的关系（如语义相似性，也就是无法很好地表达语义）。"：第1点不成立，因为映射成词向量之后参数比one-hot vector还多，并没有解决这个问题；第2点里“无法”换成“难于”，无法这个词太过绝对了，而且给个例子吧，例如科大=[0,1,0,0]，科技大学=[0,0,1,0]，两个向量内积为0，但事实上很相关
"需再映射到" -> "需再将one-hot vector映射到"，中间插了长段别的话，因此需要把宾语再重复一下，以避免混淆

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +3. 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，$\varnothing _\theta$是一个非线性激活函数，最后得到的$\mathbf{h}=\left \{ h_1,..., h_T \right \}$就是RNN依次读入源语言$T$个词的状态
"源语言$T$个词的状态编码" -> "源语言$T$个词的状态编码序列"
"池化结果" -> "池化（pooling）结果"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +第3步也可以使用双向RNN实现更复杂的句编码表示，具体可以用双向GRU实现。前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似地，后向GRU按照$(x_T,x_{T-1},...,x_1)$的顺序依
"双向RNN" -> "双向循环神经网络"
“类似地” -> "类似的"
"连接两个GRU" -> "拼接两个GRU"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +机器翻译任务中，解码阶段的总体思路是：每一个时刻，根据源语言句子的编码信息（又叫上下文向量，context vector）$c$、$u_i$（训练模式是真实目标语言序列的第$i$个词，生成模式是生成的第$i$个目标语言序列单词）和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，并通过`softmax`归一化得到目标语言序列的第$i+1$个单词的概率分布$p_{i+1
$c$、$u_i$上文都没有定义吧？
"（训练模式是真实目标语言序列的第$i$个词，生成模式是生成的第$i$个目标语言序列单词）"这句话不要放在这里吧，没读过论文的，在这里看到这句话会不知所云，影响理解

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +- 训练模式：目标是最大化下一个正确的源语言词的概率，即再根据$p_{i+1}$和$u_{i+1}$计算代价，然后重复上述操作，直到目标语言序列中的所有词处理完毕。
前加过渡性语句，点出“训练模式”和“生成模式”都是指什么

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +- 生成模式：目标是最大化生成序列的概率，即再根据$p_{i+1}$采样出单词$u_{i+1}$，然后重复上述操作，直到获得句子结束标记`<e>`或超过句子的最大生成长度为止。由于生成时的每一步都是通过贪心法实现的，因此并不能保证得到全局最优解。
这一段最好放到beam search之后讲，放在这里读者完全没有概念，会晕掉的

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +如果编码阶段的输出是一个固定维度的向量，会带来以下三个问题：1）不论源语言序列的长度是5个词还是50个词，如果都用固定维度的向量去编码其中的语义和句法结构信息，对模型来说是一个非常高的要求，特别是对长句子序列而言；2）从直觉出发，当翻译目标语言时，我们并不需要知道整个源语言序列，而只要知道当前翻译到源语言的哪个位置和这个位置前后的一个上下文片段即可；3）任何时候都拿到源语言的所有信息，实际上也是
Attention -> attention

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +如果编码阶段的输出是一个固定维度的向量，会带来以下三个问题：1）不论源语言序列的长度是5个词还是50个词，如果都用固定维度的向量去编码其中的语义和句法结构信息，对模型来说是一个非常高的要求，特别是对长句子序列而言；2）从直觉出发，当翻译目标语言时，我们并不需要知道整个源语言序列，而只要知道当前翻译到源语言的哪个位置和这个位置前后的一个上下文片段即可；3）任何时候都拿到源语言的所有信息，实际上也是
感觉第2、3点这样讲的确实容易引起争论
第2点和3点是否合并成一点更好，即“直觉上，当人类翻译一句话时，会对与当前要被译出的译文更相关的源语言片段给予更多关注，且关注点会随着翻译的进行而进行改变。而固定维度的向量则相当于任何时刻都对源语言所有信息给予了同等程度的关注，是不合理的。”

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +其中，$align$可以看作是一个对齐模型，用来衡量目标语言中第$i$个词和源语言中第$j$个词的匹配程度。具体而言，这个程度是通过解码RNN的第$i$个隐层状态$z_i$和源语言句子的第$j$个上下文片段$h_j$计算得到的。不同于传统的对齐模型：目标语言的每个词明确对应源语言的一个或多个词（hard alignment）。这里采用的是soft alignment，因此可以融入整个NMT框架，
"不同于传统的对齐模型：目标语言的每个词明确对应源语言的一个或多个词（hard alignment）。这里采用的是soft alignment，因此可以融入整个NMT框架，并通过反向传播算法求梯度以及更新参数。" -> "传统的对齐模型中，目标语言的每个词明确对应源语言的一个或多个词（hard alignment）；而在注意力模型中采用的是soft alignment，即任何两个目标语言和源语言词间均存在一定的关联，而关联强度是由模型计算得到的实数，因此可以融入整个NMT框架，并通过反向传播算法进行训练。" ，原文感觉两句衔接有点怪。

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +### 集束搜索算法
柱搜索算法

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +集束搜索（[Beam Search](http://en.wikipedia.org/wiki/Beam_search)）是一种启发式图搜索算法，用于在图或树中搜索有限集合中的最优扩展节点，通常用在解空间非常大的系统（如机器翻译、语音识别）中，原因是内存无法装下图或树中所有展开的解。如在机器翻译任务中希望翻译“`<s>你好<e>`”，就算目标语言字典中只有3个词（`<s>`, `<e>`, `h
"集束搜索（[Beam Search]）" -> "柱搜索（[beam search]"
"我们可采用集束搜索算法。" -> "我们可采用柱搜索算法。"

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +集束搜索算法使用广度优先策略建立搜索树，在树的每一层，按照启发代价（Heuristic Cost）（本教程中，为生成词的log概率之和）对节点进行排序，然后仅留下预先确定的个数（Beam Width，Beam Size，集束宽度）的节点。只有这些节点会在下一层继续扩展，其他节点就被剪掉了，也就是说保留了质量较高的节点，剪枝了质量较差的节点。因此，搜索所占用的空间和时间大幅减少，但缺点是可能存在最
"集束搜索算法" -> "柱搜索算法"
"（Heuristic Cost）" -> "（heuristic cost）"
"（Beam Width，Beam Size，集束宽度）" -> "（文献中通常称为“beam width"，"beam size"，"柱宽度"等）"
"但缺点是可能存在最优解被丢弃" -> "但缺点是无法保证一定获得最优解"，原句缺宾语

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +       beam_size=3 # # 集束算法中的宽度
柱搜索

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +   3.1 对源语言序列编码后的结果（见2.3），过一个前馈神经网络（Feed Forward Neural Network），得到其映射。
“见2.3”加链接？

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +2. Cho K, Van Merriënboer B, Gulcehre C, et al. [Learning phrase representations using RNN encoder-decoder for statistical machine translation](https://arxiv.org/abs/1406.1078)[J]. arXiv preprint arX
请引用正式发表的论文
Cho K, Van Merriënboer B, Gulcehre C, et al. [Learning phrase representations using RNN encoder-decoder for statistical machine translation](http://www.aclweb.org/anthology/D/D14/D14-1179.pdf)[C]//Proceedings of the 2014 Conference on Empirical Methods in Natural Language Processing (EMNLP), 2014: 1724-1734.

2017-01-17 12:53 UTC, pengli09 commented on machine_translation/README.md
> +4.  Bahdanau D, Cho K, Bengio Y. [Neural machine translation by jointly learning to align and translate](https://arxiv.org/abs/1409.0473)[J]. arXiv preprint arXiv:1409.0473, 2014.
Bahdanau D, Cho K, Bengio Y. [Neural machine translation by jointly learning to align and translate](https://arxiv.org/abs/1409.0473)[C]//Proceedings of ICLR 2015, 2015.

2017-01-18 09:37 UTC, luotao1 reviewed
意见已全部修改

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +面对上述挑战，一个较好的解决方法是利用神经网络。这类系统又大致分为两类：1）仍以统计机器翻译系统为框架，只是利用神经网络来改进其中的关键模块，如语言模型、调序模型等（见图1的左半部分）；2）不再以统计机器翻译系统为框架，而是直接用神经网络将源语言映射到目标语言，即端到端的神经网络机器翻译（Neural Machine Translation, NMT）（见图1的右半部分）。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +本教程主要介绍NMT模型，以及如何用PaddlePaddle来训练一个翻译模型。
全文已统一修改

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +```text
已更换

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +- 右起第一列是生成的英语句子，右起第二列是该条英语句子的得分（从大到小），右起第三列是该条句子的序号。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +- 另外有两个特殊表示：`<e>`表示句子的结尾，`<unk>`表示未登录（即不在训练字典中）的单词。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +本节依次介绍GRU（Gated Recurrent Unit，门控循环单元），双向循环神经网络，NMT中典型的“编码器-解码器”（Encoder-Decoder）框架和“注意力”（Attention）机制，以及集束搜索（Beam Search）算法。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +我们已经在[情感分析](https://github.com/PaddlePaddle/book/blob/develop/understand_sentiment/README.md)一章中介绍了循环神经网络(RNN)及长短时间记忆网络（LSTM）。相比于简单的RNN，LSTM增加了记忆单元、输入门、遗忘门及输出门，这些门及记忆单元组合起来大大提升了RNN处理远距离依赖问题的能力。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +- 更新门（Update Gate）：将LSTM的输入门和遗忘门合并，用于控制历史信息对当前输出的影响。如果更新门接近1，会把历史信息传递下去。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +<p align="center">
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +图2. GRU门控循环单元
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +我们已经在[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/README.md)一章中介绍了一种双向循环神经网络，这里介绍Bengio等人在论文\[[2](#参考文献),[4](#参考文献)\]中提出的另一种结构。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +### 编码器-解码器框架
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +编码器-解码器（Encoder-Decoder）\[[2](#参考文献)\]框架用于解决一个任意长度的源序列到另一个任意长度的目标序列的变换问题。即编码阶段将整个源序列编码成一个向量，解码阶段通过最大化预测序列概率，从中解码出整个目标序列。编码和解码的过程通常都使用RNN实现。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +1. one-hot vector（独热向量）表示：将源语言句子$x=\left \{ x_1,x_2,...,x_T \right \}$的每个词表示成一个向量$w_i\epsilon R^{\left | V \right |},i=1,2,...,T$。这个向量的维度与词汇表大小$\left | V \right |$ 相同，并且只有一个维度上有值1（该位置对应该词在词汇表中的位置），其余
one hot vector去掉中文了。其余已修改。

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +2. 映射到低维语义空间的词向量：one-hot vector表示存在两个问题，1）生成的向量维度往往很大，容易造成维数灾难；2）无法刻画词与词之间的关系（如语义相似性，也就是无法很好地表达语义）。因此，需再映射到低维的语义空间，由一个固定维度的稠密向量（称为词向量）表示。记映射矩阵为$C\epsilon R^{K\times \left | V \right |}$，用$s_i=Cw_i$表示
> 第1点不成立，因为映射成词向量之后参数比one-hot vector还多

这里意思是映射到低维语义空间的词向量，那参数应该比one-hot vector少吧

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +3. 用RNN编码源语言词序列：这一过程的计算公式为$h_i=\varnothing _\theta \left ( h_{i-1}, s_i \right )$，其中$h_0$是一个全零的向量，$\varnothing _\theta$是一个非线性激活函数，最后得到的$\mathbf{h}=\left \{ h_1,..., h_T \right \}$就是RNN依次读入源语言$T$个词的状态
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +第3步也可以使用双向RNN实现更复杂的句编码表示，具体可以用双向GRU实现。前向GRU按照词序列$(x_1,x_2,...,x_T)$的顺序依次编码源语言端词，并得到一系列隐层状态$(\overrightarrow{h_1},\overrightarrow{h_2},...,\overrightarrow{h_T})$。类似地，后向GRU按照$(x_T,x_{T-1},...,x_1)$的顺序依
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +如果编码阶段的输出是一个固定维度的向量，会带来以下三个问题：1）不论源语言序列的长度是5个词还是50个词，如果都用固定维度的向量去编码其中的语义和句法结构信息，对模型来说是一个非常高的要求，特别是对长句子序列而言；2）从直觉出发，当翻译目标语言时，我们并不需要知道整个源语言序列，而只要知道当前翻译到源语言的哪个位置和这个位置前后的一个上下文片段即可；3）任何时候都拿到源语言的所有信息，实际上也是
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +$$c_i=\sum _{j=1}^{T}\mathbf{a}_{ij}h_j, \mathbf{a}_i=\left[ \mathbf{a}_{i1},\mathbf{a}_{i2},...,\mathbf{a}_{iT}\right ]$$
都改成$a_{ij}$了，h除了单个的h用了粗体，其他都没有，单个的粗体表示是向量。

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +其中，$align$可以看作是一个对齐模型，用来衡量目标语言中第$i$个词和源语言中第$j$个词的匹配程度。具体而言，这个程度是通过解码RNN的第$i$个隐层状态$z_i$和源语言句子的第$j$个上下文片段$h_j$计算得到的。不同于传统的对齐模型：目标语言的每个词明确对应源语言的一个或多个词（hard alignment）。这里采用的是soft alignment，因此可以融入整个NMT框架，
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +### 集束搜索算法
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +集束搜索（[Beam Search](http://en.wikipedia.org/wiki/Beam_search)）是一种启发式图搜索算法，用于在图或树中搜索有限集合中的最优扩展节点，通常用在解空间非常大的系统（如机器翻译、语音识别）中，原因是内存无法装下图或树中所有展开的解。如在机器翻译任务中希望翻译“`<s>你好<e>`”，就算目标语言字典中只有3个词（`<s>`, `<e>`, `h
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +集束搜索算法使用广度优先策略建立搜索树，在树的每一层，按照启发代价（Heuristic Cost）（本教程中，为生成词的log概率之和）对节点进行排序，然后仅留下预先确定的个数（Beam Width，Beam Size，集束宽度）的节点。只有这些节点会在下一层继续扩展，其他节点就被剪掉了，也就是说保留了质量较高的节点，剪枝了质量较差的节点。因此，搜索所占用的空间和时间大幅减少，但缺点是可能存在最
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +       beam_size=3 # # 集束算法中的宽度
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +   3.1 对源语言序列编码后的结果（见2.3），过一个前馈神经网络（Feed Forward Neural Network），得到其映射。
见2.3这里加不了链接

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +      - context通过调用`simple_attention`函数，实现公式$c_i=\sum {j=1}^{T}\mathbf{a}{ij}h_j$。其中，enc_vec是$h_j$，enc_proj是$h_j$的映射（见3.1），权重$\mathbf{a}{ij}$的计算已经封装在`simple_attention`函数中。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +2. Cho K, Van Merriënboer B, Gulcehre C, et al. [Learning phrase representations using RNN encoder-decoder for statistical machine translation](https://arxiv.org/abs/1406.1078)[J]. arXiv preprint arX
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +4.  Bahdanau D, Cho K, Bengio Y. [Neural machine translation by jointly learning to align and translate](https://arxiv.org/abs/1409.0473)[J]. arXiv preprint arXiv:1409.0473, 2014.
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +我们已经在[语义角色标注](https://github.com/PaddlePaddle/book/blob/develop/label_semantic_roles/README.md)一章中介绍了一种双向循环神经网络，这里介绍Bengio等人在论文\[[2](#参考文献),[4](#参考文献)\]中提出的另一种结构。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +- 训练模式：目标是最大化下一个正确的源语言词的概率，即再根据$p_{i+1}$和$u_{i+1}$计算代价，然后重复上述操作，直到目标语言序列中的所有词处理完毕。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +- 生成模式：目标是最大化生成序列的概率，即再根据$p_{i+1}$采样出单词$u_{i+1}$，然后重复上述操作，直到获得句子结束标记`<e>`或超过句子的最大生成长度为止。由于生成时的每一步都是通过贪心法实现的，因此并不能保证得到全局最优解。
Done

2017-01-18 09:37 UTC, luotao1 commented on machine_translation/README.md
> +机器翻译任务中，解码阶段的总体思路是：每一个时刻，根据源语言句子的编码信息（又叫上下文向量，context vector）$c$、$u_i$（训练模式是真实目标语言序列的第$i$个词，生成模式是生成的第$i$个目标语言序列单词）和$i$时刻RNN的隐层状态$z_i$，计算出下一个隐层状态$z_{i+1}$，并通过`softmax`归一化得到目标语言序列的第$i+1$个单词的概率分布$p_{i+1
Done

2017-01-19 02:42 UTC, Zrachel approved these changes

2017-01-19 02:43 UTC, Zrachel approved these changes

2017-01-19 02:43 UTC, Zrachel approved these changes

2017-01-19 03:07 UTC, merged