Builddockerimage3
PaddlePaddle/book pull request #245
Opened 2017-03-21 08:56 UTC by gongweibao

#241

2017-03-21 09:28 UTC, typhoonzero commented on .tools/build_docker.sh
> +  echo 2>&1 "Check the cache_data_path:${cache_data_path}"
直接`echo "${cache_data_path} does not exist."`更简洁点吧

2017-03-21 09:32 UTC, typhoonzero requested changes

2017-03-21 09:32 UTC, typhoonzero commented on .tools/build_docker.sh
> +RUN mv /book/${cache_data_path}/* /root/${cache_data_path}/ && rm -rf /book/${cache_data_path}
并没有执行所有的book来下载数据啊，和 #241 描述的不一样？

2017-03-21 10:42 UTC, gongweibao commented on .tools/build_docker.sh
> +  echo 2>&1 "Check the cache_data_path:${cache_data_path}"
done

2017-03-21 10:46 UTC, gongweibao commented on .tools/build_docker.sh
> +RUN mv /book/${cache_data_path}/* /root/${cache_data_path}/ && rm -rf /book/${cache_data_path}
下载耗费的时间挺长的，经常不成功，所以分成了两个部分。那个还没有处理完，后边提交。

2017-03-22 01:04 UTC, wangkuiyi requested changes

2017-03-22 01:04 UTC, wangkuiyi commented on .tools/build_docker.sh
> +  echo 2>&1 "Check the cache_data_path:${cache_data_path}"
如果要让 echo 输出到 stderr，应该是 `echo foo 1>&2` 或者 `>&2 echo foo`。这里的 `2>&1` 是什么意思呢？

2017-03-22 01:04 UTC, wangkuiyi commented on .tools/build_docker.sh
> +if [ ${COPY_CACHE_DATA} ] && [ ! -d $cache_data_path ];  then
这里为什么需要检查 `COPY_CACHE_DATA`  ？ 我理解无论如何 build_docker.sh 都应该下载数据？

2017-03-22 01:04 UTC, wangkuiyi commented on .tools/convert-markdown-into-ipynb-and-test.sh
> +GOPATH=~/.cache/go go get -u github.com/wangkuiyi/ipynb/markdown-to-ipynb
为什么要把Go安装到.cache 目录里？这个不符合一般规则呀。

2017-03-22 01:04 UTC, wangkuiyi commented on .tools/build_docker.sh
> +cat >> build/Dockerfile << EOF3
这里不需要创建一个Dockerfile文件，因为 Dockerfile的内容是可以通过管道传递给 `docker build` 命令的。比如  `cat Dockerfile | docker build -t something`即可。

2017-03-22 01:04 UTC, wangkuiyi commented on .tools/build_docker.sh
> +latest_label=latest
这个东西叫tag，不叫label。

而且这里用 paddle_version 做tag就好了吧？为什么需要一个新的变量呢？

2017-03-22 08:10 UTC, typhoonzero approved these changes
LGTM.

2017-03-22 08:20 UTC, gongweibao commented on .tools/build_docker.sh
> +if [ ${COPY_CACHE_DATA} ] && [ ! -d $cache_data_path ];  then
done

2017-03-22 08:20 UTC, gongweibao commented on .tools/build_docker.sh
> +  echo 2>&1 "Check the cache_data_path:${cache_data_path}"
done

2017-03-22 08:21 UTC, gongweibao commented on .tools/build_docker.sh
> +latest_label=latest
测试的时候好改动。
改成tag:done

2017-03-22 08:22 UTC, gongweibao commented on .tools/convert-markdown-into-ipynb-and-test.sh
> +GOPATH=~/.cache/go go get -u github.com/wangkuiyi/ipynb/markdown-to-ipynb
改成~/.go下。
done

2017-03-22 10:04 UTC, gongweibao commented on .tools/build_docker.sh
> +cat >> build/Dockerfile << EOF3
试了一下，结果不行，docker的command COPY找不到context path。[这个](https://github.com/docker/docker/issues/27393)貌似社区正在修正，还没有加入到版本中。

2017-03-22 10:05 UTC, wangkuiyi commented on .tools/build_docker.sh
> +cat >> build/Dockerfile << EOF3
了解了。赞！

2017-03-22 10:07 UTC, wangkuiyi approved these changes

2017-03-22 10:07 UTC, wangkuiyi commented on .tools/build_docker.sh
> +latest_tag=latest
latest_tag => book_tag ?

2017-03-22 10:07 UTC, wangkuiyi commented on .tools/cache_dataset.py
> +#!/bin/env python
这段代码将来会被 @Yancey1989 的那个办法替换吧？

2017-03-22 10:30 UTC, gongweibao commented on .tools/cache_dataset.py
> +#!/bin/env python
对。这是第一个解决方案。
测试过程中发现一些问题，正在修正中。

2017-03-22 10:32 UTC, gongweibao commented on .tools/build_docker.sh
> +latest_tag=latest
done

2017-03-22 10:42 UTC, merged

2017-03-22 11:25 UTC, Yancey1989 commented on .tools/cache_dataset.py
> +#!/bin/env python
会的，那个PR在https://github.com/PaddlePaddle/Paddle/pull/1687