add tutorial of recommender system.
PaddlePaddle/book pull request #26
Opened 2016-12-25 11:51 UTC by livc

2016-12-27 07:38 UTC, Zrachel reviewed
已有内容改进需求

2016-12-27 07:38 UTC, Zrachel commented on recommender_system/README.md
> +#### 字段配置文件
这段整体有点乱，希望在####字段配置文件之前说明：
整个预处理过程分为处理输入用户、电影特征和将数据分为训练、测试集两部分。
在处理输入用户、电影特征这部分中，得到每个字段（movies/users）的字段配置文件，将其转化为可以解析数据集的meta文件，然后用meta文件解析数据集为python对象并序列化。
在分割训练、测试集部分中，根据`ratings.dat`将数据分为两部分，分别用来进行模型训练和测试。

2016-12-27 07:38 UTC, Zrachel commented on recommender_system/README.md
> +根据数据规模的不同，该数据集也有很多不同的版本。这里我们用 [MovieLens 百万数据集（ml-1m）](http://files.grouplens.org/datasets/movielens/ml-1m.zip)作为示例，其中包含6,000 位用户对 4,000 部电影的 1,000,000 条评价。该数据集于 2003 年 2 月发布。
“1,000,000 条评价”, 说一下分数有1,2,3,4,5这五个离散分数值。

2016-12-27 07:38 UTC, Zrachel commented on recommender_system/README.md
> +### 训练器配置文件
去掉### 训练器配置文件，下面这块内容都属于模型结构

2016-12-27 07:38 UTC, Zrachel commented on recommender_system/README.md
> +该示例的神经网络配置文件  `trainer_config.py` 如下所示：
下面的config加一些分段注释，如 https://github.com/Zrachel/book/tree/add_w2v/word2vec中的样子

2016-12-27 07:38 UTC, Zrachel commented on recommender_system/README.md
> +在文件 `trainer_config.py` 中，我们仅仅是将每个特征种类映射到一个特征向量中：
以下这段，在上面代码中分段说明

2016-12-27 07:38 UTC, Zrachel commented on recommender_system/README.md
> +Prediction Score is 3.13
说一下，注意这里的分数不是dataprovider归一化后的得分，而是预测的最终得分结果。

2016-12-27 07:38 UTC, Zrachel commented on recommender_system/README.md
> +## 背景介绍
需要加速哈~ 背景介绍需要一些调研，还挺费时间的。

2016-12-29 12:54 UTC, schinger commented on recommender_system/README.md
> +## 背景介绍
嗯，背景介绍和模型概览写起来最花时间

2017-01-03 06:35 UTC, schinger commented on recommender_system/README.md
> +### 受限玻尔兹曼机与推荐系统
下面的实验是用的RBM吗？ @Zrachel

2017-01-03 10:53 UTC, luotao1 commented
模型配置能否再简化下，现在if else分支太多了。

2017-01-06 04:25 UTC, Zrachel commented on recommender_system/README.md
> +### 受限玻尔兹曼机与推荐系统
不是，livc已经同意重新写这一段了

2017-01-06 07:52 UTC, Zrachel requested changes
修改建议。

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供用户满足兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。
将用户感兴趣的信息或商品推荐给用户。
->
将用户感可能兴趣的信息或商品推荐给用户。

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供用户满足兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。
主动提供用户满足兴趣和需求的信息
->
主动提供满足用户兴趣和需求的信息

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供用户满足兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。
段尾加：
个性化推荐可以用在很多领域，如电商购物和feed流推荐。

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +传统的推荐系统方法主要有：
段首加：
可以想见，最简单的推荐策略是当今热点，比如某宝爆款。再比如希望加入个性化信息，就是浏览过的某宝爆款，或者浏览过的某条消息。 问题是，商品和新闻这么多，大多都是没有浏览过的，而且浏览过的可能已经买过或不再需要了。那么怎样推荐才合适呢？

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +
给每种方法加1-3篇参考文献

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +- 基于内容推荐（Content-based Recommendation）：利用商品的内容描述，抽象出有意义的特征，计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。基于内容的推荐简单直接，不需要依据其他用户对商品的评价，同时可以比较商品间的相似度，但它要求得到商品的显示属性，对于没有任何行为的新用户存在冷启动的问题。
这个是不是叫content-based filtering? 不确定

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +- 基于内容推荐（Content-based Recommendation）：利用商品的内容描述，抽象出有意义的特征，计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。基于内容的推荐简单直接，不需要依据其他用户对商品的评价，同时可以比较商品间的相似度，但它要求得到商品的显示属性，对于没有任何行为的新用户存在冷启动的问题。
对于没有任何行为的新用户存在冷启动的问题。

-》

对于没有任何行为的新用户同样存在冷启动的问题。

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +深度学习具有优秀的自动提取特征的能力，能够学习多层次的抽象特征表示，并对异质或跨域的内容信息进行学习，解决推荐系统常见的冷启动问题。
深度学习不能解决冷启动问题吧？
如果可以，望注明出处。

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +```
在推荐系统中，我们可以根据所有电影的推荐得分排序，推荐给用户可能感兴趣的电影。

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +此教程我们使用[MovieLens 数据集](http://grouplens.org/datasets/movielens/)。该数据集包含一些用户信息、电影信息以及电影评分，由 GroupLens Research 实验室搜集整理。
加入wiki中的解释并附上参考文献吧。
"当一个新的用户进入MovieLens，他需对15部电影评分，评分范围为1-5分，评分间隔为0.5分。当用户查看意图电影是，MovieLens的推荐系统将根据用户以往的评分预测其对该电影的评分。"

https://zh.wikipedia.org/wiki/MovieLens

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +#### 处理输入特征
-》
`#### 数据文件序列化`

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +define_py_data_sources2(
代码没贴全，meta定义没有

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +这里我们设置了 batch size、学习率，使用 RMSProp 优化方法。
这里我们设置了 batch size、网络初始学习率，并设置RMSProp 优化方法为自适应学习率策略。

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +          if type_name == 'id':
同一个函数的代码要放在同一个代码段。

原本的1,2,3可以用注释

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +
代码没贴全吧，没给出cost，也没有介绍

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +在训练了几轮以后，你可以对模型进行评估，得到最好轮次下的模型。运行下面命令即可：
得到最好轮次下的模型。
->
得到最好轮次的模型。这可以通过选择最小训练误差的一轮参数得到，

2017-01-06 07:52 UTC, Zrachel commented on recommender_system/README.md
> +本章介绍了传统的推荐系统方法以及深度学习技术在推荐系统的应用，并使用 MovieLens 数据集训练神经网络模型。推荐系统正逐步成为深度学习技术最重要的应用领域之一。
并以电影推荐为例，用神经网络训练了一个个性化推荐模型。后面再加点。。。。

2017-01-06 08:38 UTC, luotao1 reviewed
代码不要放在src目录下，请挪出来。

2017-01-06 08:38 UTC, luotao1 commented on recommender_system/src/preprocess.sh
> +python config_generator.py config.json > meta_config.json
22行，meta_config.json是生成出来的话，版本库里就不要放这个文件了

2017-01-06 08:42 UTC, Zrachel reviewed
关于代码，需要精简。

2017-01-06 08:42 UTC, Zrachel commented on recommender_system/src/trainer_config.py
> +def construct_feature(name):
不要把不同type的实现写在一个函数里，太乱了。请参照其他demo的config，将此段代码写得易懂。

2017-01-06 08:42 UTC, Zrachel commented on recommender_system/README.md
> +首先安装 Python 第三方库（推荐使用 Virtualenv）：
处理输入特征这一节，不用写这么多的，其实用户也不care，只需给出，
通过以下命令，可以将数据转换为python序列化格式。
```bash
python preprocess.py
```

即可。

2017-01-06 08:45 UTC, livc commented on recommender_system/src/trainer_config.py
> +def construct_feature(name):
ok, 这份代码是之前就有的哈，我修改下。

2017-01-07 11:08 UTC, schinger reviewed
建议

2017-01-07 11:08 UTC, schinger commented on recommender_system/README.md
> +在网络技术不断发展和电子商务规模不断扩大的背景下，商品数量和种类快速增长，用户需要花费大量时间才能找到自己想买的商品，这就是信息超载（Information Overload）问题。为了解决这个难题，个性化（Personalized）推荐系统（Recommender System）应运而生。
信息超载，个性化 没必要加括弧及英文名

2017-01-07 11:08 UTC, schinger commented on recommender_system/README.md
> +## 模型概览
这章论述paddlepaddle中所实现的推荐系统的模型

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供用户满足兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。
done

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供用户满足兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。
done

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供用户满足兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。
done

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +在网络技术不断发展和电子商务规模不断扩大的背景下，商品数量和种类快速增长，用户需要花费大量时间才能找到自己想买的商品，这就是信息超载（Information Overload）问题。为了解决这个难题，个性化（Personalized）推荐系统（Recommender System）应运而生。
done

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +传统的推荐系统方法主要有：
done

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +- 基于内容推荐（Content-based Recommendation）：利用商品的内容描述，抽象出有意义的特征，计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。基于内容的推荐简单直接，不需要依据其他用户对商品的评价，同时可以比较商品间的相似度，但它要求得到商品的显示属性，对于没有任何行为的新用户存在冷启动的问题。
根据 [Wikipedia_Recommender_system](https://en.wikipedia.org/wiki/Recommender_system#Content-based_filtering)，已改成 Content-based filtering

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +- 基于内容推荐（Content-based Recommendation）：利用商品的内容描述，抽象出有意义的特征，计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。基于内容的推荐简单直接，不需要依据其他用户对商品的评价，同时可以比较商品间的相似度，但它要求得到商品的显示属性，对于没有任何行为的新用户存在冷启动的问题。
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +深度学习具有优秀的自动提取特征的能力，能够学习多层次的抽象特征表示，并对异质或跨域的内容信息进行学习，解决推荐系统常见的冷启动问题。
已补上出处。

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +```
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +## 模型概览
因为下面代码并不是某篇论文的实现，所以在模型概览中会介绍两种业内模型。 @Zrachel

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +### 受限玻尔兹曼机与推荐系统
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +此教程我们使用[MovieLens 数据集](http://grouplens.org/datasets/movielens/)。该数据集包含一些用户信息、电影信息以及电影评分，由 GroupLens Research 实验室搜集整理。
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +#### 处理输入特征
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +首先安装 Python 第三方库（推荐使用 Virtualenv）：
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +这里我们设置了 batch size、学习率，使用 RMSProp 优化方法。
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +在训练了几轮以后，你可以对模型进行评估，得到最好轮次下的模型。运行下面命令即可：
done

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +define_py_data_sources2(
done

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +          if type_name == 'id':
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/src/preprocess.sh
> +python config_generator.py config.json > meta_config.json
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +## 背景介绍
done.

2017-01-08 05:20 UTC, livc commented on recommender_system/README.md
> +本章介绍了传统的推荐系统方法以及深度学习技术在推荐系统的应用，并使用 MovieLens 数据集训练神经网络模型。推荐系统正逐步成为深度学习技术最重要的应用领域之一。
done.

2017-01-08 07:57 UTC, Zrachel reviewed
关于code的问题

2017-01-08 07:57 UTC, Zrachel commented on recommender_system/README.md
> +执行 `./src/preprocess.sh` 即可。
1. 目前的代码中都没有src文件夹，请自行确认代码正确性；
2. 后来paddlepaddle 项目中有fix bug, 请自行pull最新代码；

2017-01-08 10:52 UTC, livc commented on recommender_system/README.md
> +执行 `./src/preprocess.sh` 即可。
done.

2017-01-12 10:21 UTC, Zrachel reviewed
背景介绍部分

2017-01-12 10:21 UTC, Zrachel commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户可能感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供满足用户兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。个性化推荐可以用在很多
个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它可以用在很多领域，如电影、音乐、电商和 Feed 流推荐等， 通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户可能感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供满足用户兴趣和需求的信息。

2017-01-12 10:21 UTC, Zrachel commented on recommender_system/README.md
> +- 协同过滤推荐[1]（Collaborative Filtering Recommendation）：协同过滤推荐技术是推荐系统中应用最广泛的技术之一。它一般使用 *K*近邻法（*k*-*NN*）收集并分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度或距离，利用目标用户的最近邻居用户对商品评价的加权评价值来预测目标用户对特定商品的喜好程度。协同过滤可以给用户推荐未购买过的新产品，缺
它一般使用 *K*近邻法（*k*-*NN*）收集并分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度或距离，利用目标用户的最近邻居用户对商品评价的加权评价值来预测目标用户对特定商品的喜好程度。
->
对于给用户推荐商品来说，它收集并分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度或距离，使用 *K*近邻法（*k*-*NN*）利用目标用户的相似用户对商品评价的加权评价值来预测目标用户对特定商品的喜好程度。

2017-01-12 10:21 UTC, Zrachel commented on recommender_system/README.md
> +- 协同过滤推荐[1]（Collaborative Filtering Recommendation）：协同过滤推荐技术是推荐系统中应用最广泛的技术之一。它一般使用 *K*近邻法（*k*-*NN*）收集并分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度或距离，利用目标用户的最近邻居用户对商品评价的加权评价值来预测目标用户对特定商品的喜好程度。协同过滤可以给用户推荐未购买过的新产品，缺
[1] -> [\[1\]](#参考文献)

2017-01-12 10:21 UTC, Zrachel commented on recommender_system/README.md
> +- 基于内容过滤[2]（Content-based Filtering）：利用商品的内容描述，抽象出有意义的特征，计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。基于内容的推荐简单直接，不需要依据其他用户对商品的评价，同时可以比较商品间的相似度，但它要求得到商品的显示属性，对于没有任何行为的新用户同样存在冷启动的问题。
同时可以比较商品间的相似度，但它要求得到商品的显示属性，
->
而是通过商品属性进行商品相似度度量，从而推荐给用户所感兴趣商品的相似商品。

2017-01-12 12:44 UTC, Zrachel reviewed
你先看着，模型概览问题比较多

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +在构造推荐系统之前，我们先来了解一些业内模型。
->这里我们介绍一下YouTube的视频推荐、基于RNN的商品推荐和我们实现的融合推荐模型。

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +在排名模型中，特征根据贡献单个值还是多个值的集合被分为单价（univalent）特征和多价（multivalent）特征。例如，视频 ID 是单价特征，对应的多价特征就是用户最近看过的 N 个视频的 ID 集合。
之前写 2. 排序网络(ranking network)

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +![](image/YouTube_Overview.png)
图片都要标号

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +候选生成网络从用户的  YouTube 活动历史中提取信息，然后从视频库中检索出几百个与用户相关的视频输出。系统把推荐问题视为极多种类别的多分类问题。
之前写 1. 候选网络(candidate network)

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +候选生成网络从用户的  YouTube 活动历史中提取信息，然后从视频库中检索出几百个与用户相关的视频输出。系统把推荐问题视为极多种类别的多分类问题。
->候选生成网络从用户的  YouTube 活动历史中提取信息(user history and context)，然后从视频库中检索出几百个与用户相关的视频输出，并对这些视频分类，分类类别是视频库中所有视频的ID，这确实会是一个非常大的多类分类。

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +![](image/YouTube_Overview.png)
所有图。。。缩小到正常大小。。
如`<img src="img/YouTube_Overview.png" width="50%">`

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +如下图所示，深度候选生成模型将嵌入的稀疏特征取平均后和一些稠密特征连接在一起，转换成适合隐藏层输入的固定宽度的向量。所有隐藏层是全连接的。在训练中，在取样的 softmax 输出上，使用梯度下降对交叉熵代价函数进行最小化。在服务中，使用近似最近邻（approximate nearest neighbor ）查询来生成成百上千的候选视频推荐。
->
如图x所示为候选模型。输入有"观影记录"、"搜索记录"等稀疏特征，还有用户年龄、性别等稠密特征。 稀疏特征以观影记录为例，用ID序列的形式输入，即一个用户观影记录中的N个电影分别通过ID映射到N个特征向量，并求均值，就得到了观影特征watch vector。将稀疏特征分别映射为特征向量，并和稠密特征拼接，就得到了一个由各种特征组合而成的大特征向量。通过多次全连接和非线性映射(以ReLU作为激活函数)，可以由该特征输出分类到各个类别的概率。

2017-01-12 12:44 UTC, Zrachel commented on recommender_system/README.md
> +YouTube 是世界上最大的视频上传、分享、发现的网站，YouTube 推荐系统为超过 10 亿用户从不断增长的视频库内个性化定制内容。系统由两个神经网络组成：一个用于生成候选视频，另一个用于排名。系统结构如下图所示[5]：
[5]是死链接，请链接https://static.googleusercontent.com/media/research.google.com/zh-CN//pubs/archive/45530.pdf

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户可能感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供满足用户兴趣和需求的信息。一般来说，个性化推荐比一般化的推荐更能吸引用户点击或购买。个性化推荐可以用在很多
done.

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +- 协同过滤推荐[1]（Collaborative Filtering Recommendation）：协同过滤推荐技术是推荐系统中应用最广泛的技术之一。它一般使用 *K*近邻法（*k*-*NN*）收集并分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度或距离，利用目标用户的最近邻居用户对商品评价的加权评价值来预测目标用户对特定商品的喜好程度。协同过滤可以给用户推荐未购买过的新产品，缺
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +- 协同过滤推荐[1]（Collaborative Filtering Recommendation）：协同过滤推荐技术是推荐系统中应用最广泛的技术之一。它一般使用 *K*近邻法（*k*-*NN*）收集并分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度或距离，利用目标用户的最近邻居用户对商品评价的加权评价值来预测目标用户对特定商品的喜好程度。协同过滤可以给用户推荐未购买过的新产品，缺
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +- 基于内容过滤[2]（Content-based Filtering）：利用商品的内容描述，抽象出有意义的特征，计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。基于内容的推荐简单直接，不需要依据其他用户对商品的评价，同时可以比较商品间的相似度，但它要求得到商品的显示属性，对于没有任何行为的新用户同样存在冷启动的问题。
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +在构造推荐系统之前，我们先来了解一些业内模型。
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +![](image/YouTube_Overview.png)
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +候选生成网络从用户的  YouTube 活动历史中提取信息，然后从视频库中检索出几百个与用户相关的视频输出。系统把推荐问题视为极多种类别的多分类问题。
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +YouTube 是世界上最大的视频上传、分享、发现的网站，YouTube 推荐系统为超过 10 亿用户从不断增长的视频库内个性化定制内容。系统由两个神经网络组成：一个用于生成候选视频，另一个用于排名。系统结构如下图所示[5]：
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +在排名模型中，特征根据贡献单个值还是多个值的集合被分为单价（univalent）特征和多价（multivalent）特征。例如，视频 ID 是单价特征，对应的多价特征就是用户最近看过的 N 个视频的 ID 集合。
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +候选生成网络从用户的  YouTube 活动历史中提取信息，然后从视频库中检索出几百个与用户相关的视频输出。系统把推荐问题视为极多种类别的多分类问题。
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +![](image/YouTube_Overview.png)
done

2017-01-12 14:27 UTC, livc commented on recommender_system/README.md
> +如下图所示，深度候选生成模型将嵌入的稀疏特征取平均后和一些稠密特征连接在一起，转换成适合隐藏层输入的固定宽度的向量。所有隐藏层是全连接的。在训练中，在取样的 softmax 输出上，使用梯度下降对交叉熵代价函数进行最小化。在服务中，使用近似最近邻（approximate nearest neighbor ）查询来生成成百上千的候选视频推荐。
done

2017-01-14 13:26 UTC, schinger commented on recommender_system/README.md
> +可以想见，最简单的推荐策略是当今热点，比如某宝爆款。再比如希望加入个性化信息，就是浏览过的某宝爆款，或者浏览过的某条消息。 问题是，商品和新闻这么多，大多都是没有浏览过的，而且浏览过的可能已经买过或不再需要了。那么怎样推荐才合适呢？
这一小段重新组织下，它也和下一段的衔接不太好。  直接删去也行

2017-01-14 13:26 UTC, schinger commented on recommender_system/README.md
> +根据数据规模的不同，该数据集也有很多不同的版本。这里我们用 [MovieLens 百万数据集（ml-1m）](http://files.grouplens.org/datasets/movielens/ml-1m.zip)作为示例，其中包含 6,000 位用户对 4,000 部电影的 1,000,000 条评价。该数据集于 2003 年 2 月发布。当一个新的用户进入 MovieLens ，他需
意图电影？  修改下说法

2017-01-14 13:26 UTC, schinger commented on recommender_system/README.md
> +    :参数 meta: meta file 对象，通过 trainer_config 传递(记录了电影和用户的特征)
:参数对象: global object. It will passed to process routine.
 :类型对象: object

这是什么东西？？？

2017-01-14 13:26 UTC, schinger commented on recommender_system/README.md
> +    # header 是一个 [USE_SEQ_OR_NOT?, SlotType] 的 list
header 是一个 [USE_SEQ_OR_NOT?, SlotType] 的 list   ？？？？

2017-01-14 13:26 UTC, schinger commented on recommender_system/README.md
> +预测程序将读取用户的输入，然后输出预测分数（注意这里的分数不是 dataprovider 归一化后的得分，而是预测的最终得分结果）。
删去：（注意这里的分数不是 dataprovider 归一化后的得分，而是预测的最终得分结果）

2017-01-14 13:26 UTC, schinger commented on recommender_system/README.md
> +本章介绍了传统的推荐系统方法、 YouTube 的深度神经网络推荐系统和基于 RNN 的推荐系统模型，并以电影推荐为例，使用神经网络训练了一个个性化推荐模型。推荐系统几乎涵盖了电商系统、社交网络，广告推荐，搜索引擎等领域的方方面面，而在图像处理、自然语言处理等领域已经发挥重要作用的深度学习技术，也将在推荐系统领域大放异彩。
“和基于 RNN 的推荐系统模型”已经删去的，这里的还没删

2017-01-14 14:14 UTC, schinger requested changes
### 数据预处理
### 提供数据给 PaddlePaddle

这两节的问题很严重，建议完全理解代码及相关paddle文档说明（如[PyDataProvider2](http://www.paddlepaddle.org/doc_cn/ui/data_provider/index.html)）之后，认真修改。

2017-01-14 14:14 UTC, schinger commented on recommender_system/README.md
> +整个预处理过程分为处理输入用户、电影特征（数据文件序列化）和将数据分为训练、测试集两部分。执行 `./preprocess.sh` 即可。
“处理输入用户、电影特征”  不通

2017-01-14 14:14 UTC, schinger commented on recommender_system/README.md
> +本章介绍了传统的推荐系统方法、 YouTube 的深度神经网络推荐系统和基于 RNN 的推荐系统模型，并以电影推荐为例，使用神经网络训练了一个个性化推荐模型。推荐系统几乎涵盖了电商系统、社交网络，广告推荐，搜索引擎等领域的方方面面，而在图像处理、自然语言处理等领域已经发挥重要作用的深度学习技术，也将在推荐系统领域大放异彩。
“推荐系统几乎涵盖了电商系统、社交网络，广告推荐，搜索引擎等领域的方方面面，而在图像处理、自然语言处理等领域已经发挥重要作用的深度学习技术，也将在推荐系统领域大放异彩。”  这句话并不是很好的总结

2017-01-14 14:19 UTC, schinger commented on recommender_system/README.md
> +- use_seq: `dataprovider.py` 中的数据是否为序列模式。
obj.slots和use_seq 在下面的代码里面有对应吗？在哪里设置了？

2017-01-14 14:20 UTC, schinger commented on recommender_system/README.md
> +- use_seq: `dataprovider.py` 中的数据是否为序列模式。
好好修改，明天是deadline了

2017-01-15 04:31 UTC, Zrachel reviewed
代码部分需要加说明。

2017-01-15 04:31 UTC, Zrachel commented on recommender_system/README.md
> +- \_\_list\_to\_map\_\_ : 定义输出格式，将 list 转为 map。
line133-134 不要写在外面，挪到代码里以注释形式出现；

2017-01-15 04:31 UTC, Zrachel commented on recommender_system/README.md
> +            for i, each_meta in enumerate(movie_meta):
给line 171,174,177加注释

2017-01-15 04:31 UTC, Zrachel commented on recommender_system/README.md
> +   movie_id = data_layer('movie_id', size=movie_meta[0]['max'])
在“1. 定义参数维度和数据输入。”后面给每个网络输入加注释，比如genres是什么意思，就很难猜.

2017-01-15 04:31 UTC, Zrachel commented on recommender_system/README.md
> +   对于电影名称，我们将其展开成向量后，输入 [`text_conv_pool`](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/networks.html#text-conv-pool) 层，该层完成了 文本输入 => 上下文投影 => 全连接 => 池化 => 输出 的流程。
我们将其展开成向量后
-》
我们将其映射成向量后

2017-01-15 04:31 UTC, Zrachel commented on recommender_system/README.md
> +   对于电影名称，我们将其展开成向量后，输入 [`text_conv_pool`](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/networks.html#text-conv-pool) 层，该层完成了 文本输入 => 上下文投影 => 全连接 => 池化 => 输出 的流程。
一个个特征说，而不是只说电影名称的处理方法。相同处理方法（如都是embedding）的特征可以一起说。

2017-01-15 04:31 UTC, Zrachel commented on recommender_system/README.md
> +
一个个特征解释

2017-01-15 04:31 UTC, Zrachel commented on recommender_system/README.md
> +           regression_cost(
通篇没有提到网络cost。

2017-01-16 11:18 UTC, Zrachel reviewed
youtube模型

2017-01-16 11:18 UTC, Zrachel commented on recommender_system/README.md
> +候选生成网络将推荐问题建模为一个类别数极大的多类分类问题：使用观看历史（视频id）、搜索词记录（search tokens）、人口学信息（如地理位置、用户登录设备）等特征，对视频库中所有视频进行多分类，得到每一类别的分类结果，即每一个视频的推荐概率，最终输出概率较高的几百个视频。对于用户$U$和历史信息$C$，预测$t$时刻用户要观看的视频$\omega_t$为视频$i$的概率为：
候选生成网络将推荐问题建模为一个类别数极大的多类分类问题：对于一个Youtube用户，使用其观看历史（视频id）、搜索词记录（search tokens）、人口学信息（如地理位置、用户登录设备）等特征，对视频库中所有视频进行多分类……

2017-01-16 11:18 UTC, Zrachel commented on recommender_system/README.md
> +将观看视频记录（视频ID）及搜索词记录这类历史信息映射为向量后取平均值得到定长表示，同时输入人口学特征（地理位置等）以优化新用户的推荐效果，将二值特征（如性别，是否登录）和连续特征（如用户年龄）归一化处理到[0, 1]，最后，引入视频存在时间（example age）这一特征，使视频流行度的数学分布更贴近真实数据。接下来将所有特征表示拼接为一个很长的向量并输入给多个非线形变换层（这里应用的是全连
最高层的非线形变换得到的即是$u$
->
最高层的非线形变换得到的即是该用户的兴趣特征$u$

2017-01-16 11:18 UTC, Zrachel commented on recommender_system/README.md
> +考虑到 softmax 分类类别数极多，为了保证一定的计算效率，在训练阶段使用负样本类别采样将实际计算的类别数缩小至数千；在推荐（服务）阶段，忽略 softmax 的归一化计算（不影响结果），将类别打分问题简化为点积（dot product）空间中的最近邻（nearest neighbor）搜索问题，取与$u$最近的$N$个视频作为生成的候选。
推荐（服务）阶段
->
推荐（预测）阶段

2017-01-16 11:18 UTC, Zrachel commented on recommender_system/README.md
> +如图3所示，其结构类似于候选生成网络，但是它的目标是对候选进行更细致的打分排序。类似于传统的广告排序中的特征抽取方法，这里也构造了大量的用于视频排序的相关特征。离散特征和连续特征的处理方式类似于候选生成网络，不同之处是排序网络的顶部是一个加权逻辑回归（weighted logistic regression），它对所有候选视频进行打分，从高到底排序后返回给用户[[7](#参考文献)]。
去掉“如图3所示”
经讨论决定去掉图3，太重复性了，只用文字描述网络输入特征和网络结构就ok

重新理顺文字，重新给下面的图标号。

2017-01-16 11:24 UTC, Zrachel reviewed
融合推荐模型

2017-01-16 11:24 UTC, Zrachel commented on recommender_system/README.md
> +在用户特征中，有用户ID，性别，职业，年龄四个属性。我们将用户 ID 输入嵌入层（embedding layer），映射为维度大小为256的稠密向量（dense vector）表示，然后输入全连接层，同时对其他三个属性也做类似的处理。最后将四个属性的特征表示拼接起来输入到一个全连接层内，其结果即是用户特征的最终表示（UserFusion），它融合了用户的四个属性信息。
最后将四个属性的特征表示拼接起来输入到一个全连接层内
->
最后将四个属性的特征表示分别全连接并相加

下面电影特征 的说法也做一下相应修改

2017-01-16 11:24 UTC, Zrachel commented on recommender_system/README.md
> +在电影特征中，有电影ID，电影类型ID，电影名称三个属性。我们对电影 ID 以类似用户ID的方式进行处理，电影类型ID 将被以向量的形式直接输入全连接层。对于电影名称，我们用文本卷积神经网络对其进行处理，得到其定长向量表示。最后将三个属性的特征表示拼接起来输入到全连接层作为电影特征的最终表示（MovieFusion）。
文本卷积神经网络
->
文本卷积神经网络（详见[第5章](https://github.com/PaddlePaddle/book/blob/develop/understand_sentiment/README.md)中的介绍）

2017-01-16 11:24 UTC, Zrachel commented on recommender_system/README.md
> +得到电影和用户的向量表示后，计算二者的余弦相似度作为推荐系统的打分。
本句话末尾加“最后，用该相似度打分和用户真实打分的差异的平方作为该回归模型的损失函数。”

2017-01-16 13:50 UTC, Zrachel commented on recommender_system/README.md
> +这里我们介绍一下 YouTube 的视频推荐和我们实现的融合推荐模型。
这里我们介绍一下
->
本章中，我们首先介绍YouTube的视频推荐系统，然后介绍我们实现的融合推荐模型。

2017-01-16 13:50 UTC, Zrachel commented on recommender_system/README.md
> +YouTube 是世界上最大的视频上传、分享和发现网站，YouTube 推荐系统为超过 10 亿用户从不断增长的视频库中推荐个性化的内容。系统由两个神经网络组成：候选生成网络和排序网络。候选生成网络从百万量级的视频库中生成上百个候选，排序网络对候选进行打分排序，输出排名最高的数十个结果。系统结构如图1所示[[7](#参考文献)]：
系统由两个神经网络组成
->
整个系统由两个神经网络组成

2017-01-16 13:50 UTC, Zrachel commented on recommender_system/README.md
> +YouTube 是世界上最大的视频上传、分享和发现网站，YouTube 推荐系统为超过 10 亿用户从不断增长的视频库中推荐个性化的内容。系统由两个神经网络组成：候选生成网络和排序网络。候选生成网络从百万量级的视频库中生成上百个候选，排序网络对候选进行打分排序，输出排名最高的数十个结果。系统结构如图1所示[[7](#参考文献)]：
系统结构如图1所示[[7](#参考文献)]：
->
系统结构如图1所示：

PS: 本文中的图片我们都会重绘，不用加参考文献了

2017-01-16 13:50 UTC, Zrachel commented on recommender_system/README.md
> +将观看视频记录（视频ID）及搜索词记录这类历史信息映射为向量后取平均值得到定长表示，同时输入人口学特征（地理位置等）以优化新用户的推荐效果，将二值特征（如性别，是否登录）和连续特征（如用户年龄）归一化处理到[0, 1]，最后，引入视频存在时间（example age）这一特征，使视频流行度的数学分布更贴近真实数据。接下来将所有特征表示拼接为一个很长的向量并输入给多个非线形变换层（这里应用的是全连
“使视频流行度的数学分布更贴近真实数据。” 这个描述不太清晰，改成"可以部分程度上表现视频流行度"？

2017-01-17 03:32 UTC, Zrachel commented on recommender_system/README.md
> +   将电影 ID 输入嵌入层（embedding layer），映射为维度大小为 256 的向量表示后输入全连接层。电影类型 ID 以 one-hot dense 形式输入，直接连入全连接层。对于电影名称，我们将其映射成向量后，输入 [`text_conv_pool`](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/
整段
->
对于电影的属性，将电影 ID 和电影类型分别映射到其对应的特征隐层（256维）。对电影名称，一个ID序列表示的词语序列，输入卷积层后，将得到每个时间窗口的特征（序列特征），然后通过在时间维度降采样得到固定维度的特征，整个过程在[`text_conv_pool`](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/networks.html#text-conv-pool) 实现。

2017-01-17 03:32 UTC, Zrachel commented on recommender_system/README.md
> +   将用户ID，性别，职业，年龄四个属性以类似电影 ID 的方式进行处理，然后同样将这四个属性分别全连接并相加形成用户特征的最终表示。
以类似电影 ID 的方式进行处理
->
分别映射到其特征隐层

2017-01-17 03:32 UTC, Zrachel commented on recommender_system/README.md
> +```shell
贴新的

2017-01-17 03:32 UTC, Zrachel commented on recommender_system/README.md
> +```shell
贴新的

2017-01-17 03:32 UTC, Zrachel commented on recommender_system/README.md
> +在用户特征中，有用户ID，性别，职业，年龄四个属性。我们将用户 ID 输入嵌入层（embedding layer），映射为维度大小为256的稠密向量（dense vector）表示，然后输入全连接层，同时对其他三个属性也做类似的处理。最后将四个属性的特征表示分别全连接并相加，其结果即是用户特征的最终表示（UserFusion），它融合了用户的四个属性信息。
改为把UserFusion提到段首，即“UserFusion：。。。。”
下一段的MovieFusion同理

2017-01-17 03:32 UTC, Zrachel commented on recommender_system/README.md
> +将观看视频记录（视频ID）及搜索词记录这类历史信息映射为向量后取平均值得到定长表示，同时输入人口学特征（地理位置等）以优化新用户的推荐效果，将二值特征（如性别，是否登录）和连续特征（如用户年龄）归一化处理到[0, 1]，最后，引入视频存在时间（example age）这一特征，使视频流行度的数学分布更贴近真实数据。接下来将所有特征表示拼接为一个很长的向量并输入给多个非线形变换层（这里应用的是全连
可以部分程度上表现视频流行度与发布时间的关系

2017-01-17 09:49 UTC, luotao1 requested changes
1. 候选生成网络中的公式解释的不是很清楚，可以不放么？ @Zrachel @schinger 
2. 文中的三幅图，经过手绘后有所调整，因此对应的描述也要调整。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +在网络技术不断发展和电子商务规模不断扩大的背景下，商品数量和种类快速增长，用户需要花费大量时间才能找到自己想买的商品，这就是信息超载问题。为了解决这个难题，个性化推荐系统（Recommender System）应运而生。
为了解决这个难题，推荐系统（Recommender System）应运而生。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +个性化推荐系统是信息过滤系统（Information Filtering System）的子集，它可以用在很多领域，如电影、音乐、电商和 Feed 流推荐等， 通过分析、挖掘用户行为，发现用户的个性化需求与兴趣特点，将用户可能感兴趣的信息或商品推荐给用户。与传统的搜索引擎不同，推荐系统不需要用户准确地描述出自己的需求，而是根据分析历史行为建模，主动提供满足用户兴趣和需求的信息。
1. 等。推荐系统通过XXX
2. 与搜索引擎不同，推荐系统（这里把传统去掉，因为推荐系统和搜索引擎有本质区别）

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +- 协同过滤推荐（Collaborative Filtering Recommendation）：对于给用户推荐商品来说，协同过滤收集并分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度，利用目标用户的相似用户对商品评价的加权评价值来预测目标用户对特定商品的喜好程度。协同过滤可以给用户推荐未浏览过的新产品，缺点是对于没有任何行为的新用户存在冷启动的问题，其次是由于用户与商品之间的交互数
协同过滤推荐（Collaborative Filtering Recommendation）：该方法收集分析用户历史行为、活动、偏好，计算一个用户与其他用户的相似度，利用目标用户的相似用户对商品评价的加权评价值，来预测目标用户对特定商品的喜好程度。优点是可以给用户推荐未浏览过的新产品；缺点是对于没有任何行为的新用户存在冷启动的问题，同时也存在用户与商品之间的交互数据不够多造成的稀疏问题，会导致模型难以找到相近用户。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +- 基于内容过滤[[1](#参考文献)]（Content-based Filtering）：利用商品的内容描述，抽象出有意义的特征，计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。基于内容的推荐简单直接，不需要依据其他用户对商品的评价，而是通过商品属性进行商品相似度度量，从而推荐给用户所感兴趣商品的相似商品，但是对于没有任何行为的新用户同样存在冷启动的问题。
基于内容过滤推荐[[1](#参考文献)]（Content-based Filtering Recommendation）：该方法利用商品的内容描述，抽象出有意义的特征，通过计算用户的兴趣和商品描述之间的相似度，来给用户做推荐。优点是简单直接，不需要依据其他用户对商品的评价，而是通过商品属性进行商品相似度度量，从而推荐给用户所感兴趣商品的相似商品；缺点是对于没有任何行为的新用户同样存在冷启动的问题。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +其中协同过滤是推荐系统中应用最广泛的技术之一，它又可以分为多个子类，分别是基于用户的推荐 (User-Based Recommendation)[[3](#参考文献)] ， 基于物品的推荐 (Item-Based Recommendation)[[4](#参考文献)]，基于社交网络关系的推荐(Social-Based Recommendation)[[5](#参考文献)]，基于模型的推荐(Mod
其中协同过滤是应用最广泛的技术之一，它又可以分为多个子类：基于用户 （User-Based）的推荐[[3](#参考文献)] ， 基于物品（Item-Based）的推荐[[4](#参考文献)]，基于社交网络关系（Social-Based）的推荐[[5](#参考文献)]，基于模型（Model-based的推荐等。1994年明尼苏达大学推出的GroupLens 系统[[3](#参考文献)]一般被认为是推荐系统成为一个相对独立的研究方向的标志。（最后一句不用修改）

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +深度学习具有优秀的自动提取特征的能力，能够学习多层次的抽象特征表示，并对异质或跨域的内容信息进行学习，可以一定程度上处理推荐系统特定的冷启动问题[[6](#参考文献)]。本教程主要介绍个性化推荐的深度学习模型，以及如何使用 PaddlePaddle 实现模型。
1. 特定的冷启动问题-》冷自动问题，不要加“特定的”吧
2. PaddlePaddle前后空格去掉。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +Prediction Score is 3.12
27-30行可以去掉，展示一个例子即可。另外要说明下分数的范围，分数越高越好还是越低越好。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +本章中，我们首先介绍 YouTube 的视频推荐系统[[7](#参考文献)]，然后介绍我们实现的融合推荐模型。
35,37,39行中YouTube和“10”前后多余空格去掉

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +#### 候选生成网络(Candidate Generation Network)
46行和66行用中文括号

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +候选生成网络将推荐问题建模为一个类别数极大的多类分类问题：对于一个Youtube用户，使用其观看历史（视频id）、搜索词记录（search tokens）、人口学信息（如地理位置、用户登录设备）等特征，对视频库中所有视频进行多分类，得到每一类别的分类结果，即每一个视频的推荐概率，最终输出概率较高的几百个视频。对于用户$U$和历史信息$C$，预测$t$时刻用户要观看的视频$\omega_t$为视频
1. 得到每一类别的分类结果（即每一个视频的推荐概率），
2. （换行）对用户$U$及其历史信息$C$，预测$t$时刻该用户要观看的视频$\omega_t$为视频$i$的概率为：

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +- $v_j\in \mathbb{R}^N$是id为$j$的候选视频的向量表示
1. 52-56合并成一行，中间用；隔开。
2. 历史信息是C，55行和公式里面都没有C，直接出来了v
3. id为$j$的候选视频：意思不是很明显，id是视频id，视频id=j的候选视频是什么意思呢？

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +考虑到 softmax 分类类别数极多，为了保证一定的计算效率，在训练阶段使用负样本类别采样将实际计算的类别数缩小至数千；在推荐（预测）阶段，忽略 softmax 的归一化计算（不影响结果），将类别打分问题简化为点积（dot product）空间中的最近邻（nearest neighbor）搜索问题，取与$u$最近的$N$个视频作为生成的候选。
考虑到softmax分类的类别数非常多，为了保证一定的计算效率：1）训练阶段，使用负样本类别采样将实际计算的类别数缩小至数千；2）推荐（预测）阶段，忽略 softmax的归一化计算（不影响结果），将类别打分问题简化为点积（dot product）空间中的最近邻（nearest neighbor）搜索问题，取与$u$最近的$N$个视频作为生成的候选。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +将观看视频记录（视频ID）及搜索词记录这类历史信息映射为向量后取平均值得到定长表示，同时输入人口学特征（地理位置等）以优化新用户的推荐效果，将二值特征（如性别，是否登录）和连续特征（如用户年龄）归一化处理到[0, 1]，然后引入视频存在时间（example age）这一特征，可以从部分程度上表现视频流行度与发布时间的关系。接下来将所有特征表示拼接为一个很长的向量并输入给多个非线形变换层（这里应用
请根据 @Zrachel 的手绘图，重新整理58行。
1. 观看视频记录（视频ID），在48行中的描述是“观看历史（视频id）”，请统一
2. （example age）删掉，中文图里没有example age

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +得到电影和用户的向量表示后，计算二者的余弦相似度作为推荐系统的打分。最后，用该相似度打分和用户真实打分的差异的平方作为该回归模型的损失函数。
根据 @Zrachel 的手绘图，重新整理融合推荐模型这章
1. UserFusion和MovieFusion在图中已经没了，所以要去掉
2. “将用户 ID 输入嵌入层（embedding layer），映射为维度大小为256的稠密向量（dense vector）表示”这句表示不好，特别是嵌入层， @Zrachel 看下怎么描述
3. （详见第5章）去掉“的介绍”

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +- README: 数据集的详细描述
97-100请使用中文冒号，统一修改格式为`电影ID::电影名称::电影类型`

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +执行下面的命令就可以预处理数椐：
110和112行合并：

其次，在预处理过程中，我们将字段配置文件`data/config.json`转化为meta配置文件`meta_config.json`，并生成对应的meta文件`meta.bin`，以完成数据文件的序列化。然后再将生成的数据集`ratings.dat`分为训练集、测试集两部分，它们的地址写入`train.list`和`test.list`。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +- train.list 和 test.list: 训练集和测试集文件列表。
1. 127行去掉
2. 124-128行英文单词前后多余的空格去掉。
3. “如何”不用加粗
5. 训练集和测试集的文件地址列表

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +    del kwargs
146行代码删掉可以么

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +import common_utils
136行改成`from common_utils import meta_to_header`，这样147和150行可以简化，对应修改源代码

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +def __list_to_map__(lst):  # 定义输出格式，将 list 转为 map
`# 将list转为map`
注释里去掉“定义输出格式”，因为就是一个list转成map的函数

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +    settings.meta = meta
请在147-155内对应位置注释：定义电影特征、用户特征和评分数据的输入格式。另外要介绍输入格式是什么？

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +            # 将评分放缩到[-2, +2]范围内的整数
将评分从[1, 5]放缩到[-2, +2]范围内的整数 “放缩”这个词不是很好， @Zrachel 你觉得呢。这里没有scale，只是平移

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +加载 Meta 文件并定义通过 `define_py_data_sources2` 从 dataprovider 中读入数据：
加载`meta.bin`文件并定义通过`define_py_data_sources2`从dataprovider中读入数据：

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +这里我们设置了 batch size、网络初始学习率，并设置RMSProp 优化方法为自适应学习率策略。
网络初始学习率和RMSProp自适应优化方法。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +融合模型配置结构如下：
227行去掉

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +   最后将三个属性的特征表示分别全连接并相加，结果即是电影特征的最终表示。
1. 248-250行的注释对应写在下面的代码里吧。原来的英文注释去掉（源代码可以不改）
2. 246行和267行的末尾是句号

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +   将用户ID，性别，职业，年龄四个属性分别映射到其特征隐层，然后同样将这四个属性分别全连接并相加形成用户特征的最终表示。
269行的注释写在下面的代码里吧。原来的英文注释去掉（源代码可以不改）

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +1. 定义参数维度和数据输入。
定义数据输入和参数维度。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +    --test_all_data_in_one_period=true \	# 每个训练周期训练一次所有数据。否则每个训练周期测试												  batch_size 个 batch 的数据。
317行“否则每个训练周期测试”和“batch_size 个 batch 的数据”中有好多空格，请去掉。另外去掉batch_size和batch前后的空格

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +如果训练过程启动成功的话，输出应该类似如下：
成功的输入类似如下：

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +在训练了几轮以后，你可以对模型进行评估，通过选择最小训练误差的一轮参数得到最好轮次的模型。运行下面命令即可：
在训练了几轮以后，您可以对模型进行评估。运行以下命令，可以通过选择最小训练误差的一轮参数得到最好轮次的模型。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +你将看到：
您将看到

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +然后，你可以预测任何用户对于任何一部电影的评价，运行下面命令即可：
预测任何用户对于任何一部电影评价的命令如下：

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +用户预测的命令行界面如下：
362-364合成一行。
预测程序将读取用户的输入，然后输出预测分数。您会看到如下命令行界面：

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +Prediction Score is 3.12
去掉370-303行，只有一个例子即可

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +   if not is_predict:
298-301行缩进的不是特别好看，因此分开写吧。对应修改源代码
```
lbl=data_layer('rating', size=1)
cost=regression_cost(input=similarity, label=lbl)
outputs(cost)
```

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +   训练中通过`data_layer`读入评分数据，采用 `regression_cost` 作为损失函数计算回归误差代价，并作为网络的输出。预测阶段定义网络的输出为余弦相似度。
292行注释写在下面代码中
```
# 训练时，采用 `regression_cost` 作为损失函数计算回归误差代价，并作为网络的输出。
# 预测时，网络的输出即为余弦相似度。
```

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +1. [Peter Brusilovsky](https://en.wikipedia.org/wiki/Peter_Brusilovsky) (2007). *The Adaptive Web*. p. 325. [ISBN](https://en.wikipedia.org/wiki/International_Standard_Book_Number) [978-3-540-72078-2
第一个参考文献的ISBN可以去掉吧。

2017-01-17 09:49 UTC, luotao1 commented on recommender_system/README.md
> +本章介绍了传统的推荐系统方法和 YouTube 的深度神经网络推荐系统，并以电影推荐为例，使用神经网络训练了一个个性化推荐模型。推荐系统几乎涵盖了电商系统、社交网络，广告推荐，搜索引擎等领域的方方面面，而在图像处理、自然语言处理等领域已经发挥重要作用的深度学习技术，也将在推荐系统领域大放异彩。
本章介绍了传统的推荐系统方法和YouTube的深度神经网络推荐系统，并以电影推荐为例，使用PaddlePaddle训练了一个个性化推荐神经网络模型。推荐系统几乎涵盖了电商系统、社交网络、广告推荐、搜索引擎等领域的方方面面，而在图像处理、自然语言处理等领域已经发挥重要作用的深度学习技术，也将会在推荐系统领域大放异彩。

2017-01-17 14:54 UTC, Zrachel commented on recommender_system/README.md
> +            # 将评分放缩到[-2, +2]范围内的整数
"平移"？
将评分从[1, 5]平移到[-2, +2]的范围内，以便和融合推荐模型在scale=2的cos相似度输出进行比较

2017-01-18 08:35 UTC, luotao1 reviewed
公式部分请 @Zrachel 再把关下。其余都是小问题。

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +            # 将评分放缩到[-2, +2]范围内的整数
同意 @Zrachel 的意见

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +其中协同过滤是应用最广泛的技术之一，它又可以分为多个子类：基于用户 （User-Based）的推荐[[3](#参考文献)] ， 基于物品（Item-Based）的推荐[[4](#参考文献)]，基于社交网络关系（Social-Based）的推荐[[5](#参考文献)]，基于模型（Model-based的推荐等。1994年明尼苏达大学推出的GroupLens 系统[[3](#参考文献)]一般被认为是
1. 15行第一句话，几个“基于XXX”之间用顿号
2. Model-based缺了一个括号
3. GroupLens多了一个空格

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +其中，$V$表示视频库集合，大小在数百万量级；$u\in \mathbb{R}^N$是用户及相应历史信息的向量表示；$v_j\in \mathbb{R}^N$是ID为$j$的视频的向量表示。
这段公式存在的问题：
1. 等号左边有C，右边没C
2. 小u和大U是一个意思，所以小u应该是属于大U集合，现在小u属于R_N集合，也没解释R和N是什么。
3. 小v和大V是一个意思，所以50行解释的时候，两个要放在一起介绍。现在v_j和u的介绍位置换一下。
4. v_i*u代表什么呢？两个向量的点积么 @Zrachel 之前提过“这个公式主要表示user和video的特征的内积的softmax”，希望对这个公式先有个通俗的说明，在放公式。不然理解起来有点困难。

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +考虑到softmax分类的类别数非常多，为了保证一定的计算效率：1）训练阶段，使用负样本类别采样将实际计算的类别数缩小至数千；2）推荐（预测）阶段，忽略 softmax的归一化计算（不影响结果），将类别打分问题简化为点积（dot product）空间中的最近邻（nearest neighbor）搜索问题，取与$u$最近的$N$个视频作为生成的候选。
1. softmax前面有空格
2. 取与$u$最近的$N$个视频，是取N么？我看图里是topk

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +将观看历史（视频ID）及搜索词记录这类历史信息映射为向量后取平均值得到定长表示，同时输入人口学特征（地理位置等）以优化新用户的推荐效果，将二值特征（如性别，是否登录）和连续特征（如用户年龄）归一化处理到[0, 1]。接下来将所有特征表示拼接为一个很长的向量并输入给多个非线形变换层（这里应用的是全连接的 ReLU）处理。最高层的非线形变换得到的即是$u$，最后将其输入给 softmax 做分类，如
1. “二值特征（如性别，是否登录）和连续特征（如用户年龄）”这个放到44行里面讲。
2. 52行改成：
首先，将观看历史及搜索词记录这类历史信息，映射为向量后取平均值得到定长表示；同时，输入人口学特征以优化新用户的推荐效果，并将二值特征和连续特征归一化处理到[0, 1]范围。接下来，将所有特征表示拼接为一个向量（用很长感觉不专业，去掉吧），并输入给非线形多层感知器（MLP，详见[识别数字](https://github.com/PaddlePaddle/book/blob/develop/recognize_digits/README.md)教程）处理。最后，训练时将MLP的输出给softmax做分类，预测时XXX（请 @Zrachel 补充。图2显示了候选生成网络结构。

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +其次，在预处理过程中，我们将字段配置文件`data/config.json`转化为meta配置文件`meta_config.json`，并生成对应的meta文件`meta.bin`，以完成数据文件的序列化。然后再将`ratings.dat`分为训练集、测试集两部分，把它们的地址写入`train.list`和`test.list`。
其次在预处理`./preprocess.sh`过程中，

去掉107-109行

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +    # 加载 meta 文件
201行注释应该放在200行之前

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +   # 电影 ID 和电影类型分别映射到其对应的特征隐层（256维）。
ID前后空格去掉

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +```
这段注释的位置能否前移一点，这样不会出现拖动条了

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +排序网络的结构类似于候选生成网络，但是它的目标是对候选进行更细致的打分排序。类似于传统的广告排序中的特征抽取方法，这里也构造了大量的用于视频排序的相关特征（如视频 ID、上次观看时间等）。离散特征和连续特征的处理方式类似于候选生成网络，不同之处是排序网络的顶部是一个加权逻辑回归（weighted logistic regression），它对所有候选视频进行打分，从高到底排序后将分数较高的一些视
第一句不变，第二句开始修改：
和传统广告排序中的特征抽取方法类似，这里也构造了大量的用于视频排序的相关特征（如视频 ID、上次观看时间等）。这些特征的处理方式和候选生成网络类似，XXX，它会对XXX，然后XXX

2017-01-18 08:35 UTC, luotao1 commented on recommender_system/README.md
> +得到电影和用户的向量表示后，计算二者的余弦相似度作为推荐系统的打分。最后，用该相似度打分和用户真实打分的差异的平方作为该回归模型的损失函数。
在下文的电影推荐系统中：
1. 首先，使用用户特征和电影特征作为神经网络的输入，其中：
   - 用户特征融合了四个属性信息，分别是用户ID、性别、职业和年龄。
   - 电影特征融合了三个属性信息，分别是电影ID、电影类型ID和电影名称。
2. 对用户特征，将用户ID映射为维度大小为256的向量表示，输入全连接层，并对其他三个属性也做类似的处理。然后将四个属性的特征表示分别全连接并相加。
3. 对电影特征，将电影ID以类似用户ID的方式进行处理，电影类型ID以向量的形式直接输入全连接层，电影名称用文本卷积神经网络（详见[第5章](https://github.com/PaddlePaddle/book/blob/develop/understand_sentiment/README.md)）得到其定长向量表示。然后将三个属性的特征表示分别全连接并相加。
4. 得到用户和电影的向量表示后，计算二者的余弦相似度作为推荐系统的打分。最后，用该相似度打分和用户真实打分的差异的平方作为该回归模型的损失函数。

2017-01-18 11:31 UTC, Zrachel commented on recommender_system/README.md
> +考虑到softmax分类的类别数非常多，为了保证一定的计算效率：1）训练阶段，使用负样本类别采样将实际计算的类别数缩小至数千；2）推荐（预测）阶段，忽略 softmax的归一化计算（不影响结果），将类别打分问题简化为点积（dot product）空间中的最近邻（nearest neighbor）搜索问题，取与$u$最近的$N$个视频作为生成的候选。
改成k吧

2017-01-18 11:31 UTC, Zrachel commented on recommender_system/README.md
> +将观看历史（视频ID）及搜索词记录这类历史信息映射为向量后取平均值得到定长表示，同时输入人口学特征（地理位置等）以优化新用户的推荐效果，将二值特征（如性别，是否登录）和连续特征（如用户年龄）归一化处理到[0, 1]。接下来将所有特征表示拼接为一个很长的向量并输入给多个非线形变换层（这里应用的是全连接的 ReLU）处理。最高层的非线形变换得到的即是$u$，最后将其输入给 softmax 做分类，如
预测时XXX：
预测时求MLP的输出（即当前用户的综合特征）与所有视频的相似度，并取得分最高的k个作为候选生成网络的筛选结果，其中相似度由用户特征和视频特征的点积得到。

2017-01-18 11:49 UTC, Zrachel commented on recommender_system/README.md
> +
用公式表示，对于一个用户$U$，预测此刻用户要观看的视频$\omega$为视频$i$的概率为：

$$P(\omega=i|u)=\frac{e^{v_{i}u}}{\sum_{j \in V}e^{v_{j}u}}$$

其中$u$为$U$的特征表示，$V$为视频库集合，$v_i$为视频库中第$i$个视频的特征表示，$u$和$v_i$为长度相等的向量，其点积可以通过全连接层实现。


以上这段话和line52交换位置。

2017-01-18 12:27 UTC, luotao1 approved these changes

2017-01-18 12:27 UTC, luotao1 commented on recommender_system/README.md
> +用公式表示，对于一个用户$U$，预测此刻用户要观看的视频$\omega$为视频$i$的概率为：
对于一个用户$U$，预测此刻用户要观看的视频$\omega$为视频$i$的概率公式为：

2017-01-18 12:27 UTC, luotao1 commented on recommender_system/README.md
> +其中$u$为$U$的特征表示，$V$为视频库集合，$v_i$为视频库中第$i$个视频的特征表示，$u$和$v_i$为长度相等的向量，其点积可以通过全连接层实现。
其中$u$为用户$U$的特征表示，$V$为视频库集合，$v_i$为视频库中第$i$个视频的特征表示。$u$和$v_i$为长度相等的向量，两者点积可以通过全连接层实现。

2017-01-18 12:27 UTC, luotao1 commented on recommender_system/README.md
> +考虑到softmax分类的类别数非常多，为了保证一定的计算效率：1）训练阶段，使用负样本类别采样将实际计算的类别数缩小至数千；2）推荐（预测）阶段，忽略softmax的归一化计算（不影响结果），将类别打分问题简化为点积（dot product）空间中的最近邻（nearest neighbor）搜索问题，取与$u$最近的$K$个视频作为生成的候选。
K不要大写，换成小写吧。图中是小写吧。

2017-01-18 12:33 UTC, Zrachel approved these changes

2017-01-19 02:15 UTC, schinger approved these changes

2017-01-19 02:16 UTC, merged

2017-01-19 02:38 UTC, livc commented
@Zrachel @luotao1 @schinger 辛苦各位的 review，非常感谢！ ：）