first PR for recognize_digits
PaddlePaddle/book pull request #27
Opened 2016-12-25 15:49 UTC by dayhaha

first PR, not finished yet. 
resolve #4

2016-12-27 11:35 UTC, schinger requested changes

2016-12-27 11:35 UTC, schinger commented on recognize_digits/README.md
> +通过`img = data_layer(name='pixel', size=data_size)`我们得到图片数据，而为了进行计算，该表示方法实际上将28X28的二
模型概览里面尽量不放代码，如`img = data_layer(name='pixel', size=data_size)`

2016-12-27 11:35 UTC, schinger commented on recognize_digits/README.md
> +$$ net_j = \sum_j W_{i,j}x_j + b_i $$
net_i 吧

2016-12-27 11:35 UTC, schinger commented on recognize_digits/README.md
> +<center> ![](./image/softmax_regression.png) </center>
此图能和上面的公式对应起来吗？图里面的x0等有角标的符号能否写成公式，如：$x_0$

2016-12-27 11:35 UTC, schinger commented on recognize_digits/README.md
> +####原理介绍：
公式需要更严谨一些

2016-12-29 09:10 UTC, luotao1 commented
recognize_digits/data/raw_data/下的4个ubyte文件都不用上传，请删除。

2016-12-29 09:21 UTC, luotao1 requested changes
Conv_layer.png太大了，代码修改后请同步文档中的代码。

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/data/draw_data.py
> +        n = 10000
n =60000 if "train" in filename else 10000

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/data/generate_list.py
> +o.close()
这个文件可以不需要。直接写train.list和test.list即可。或者在get_mnist_data.sh里面用echo命令写。

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/data/get_mnist_data.sh
> +#!/usr/bin/env sh
缺copyright

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/data/test.list
> +./data/raw_data/t10k
test.list和train.list两个文件是生成的，也不需要放入代码库。

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/src/cnn_mnist.py
> +#pool2 = img_pool_layer(input=conv2, pool_size=2, stride=2, num_channels=50)
注释掉的代码可以删去

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/src/mnist_provider.py
> +from paddle.trainer.PyDataProvider2 import *
缺copyright

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/src/mnist_provider.py
> +        n = 10000
n = 60000 if "train" in filename else 10000

2016-12-29 09:21 UTC, luotao1 commented on recognize_digits/src/train.sh
> +log=cnn_train.log
config, output, log不用单独列出，注释掉的代码请删去

2016-12-30 07:49 UTC, dayhaha commented on recognize_digits/src/train.sh
> +log=cnn_train.log
done

2016-12-30 07:49 UTC, dayhaha commented on recognize_digits/src/mnist_provider.py
> +        n = 10000
done

2016-12-30 07:49 UTC, dayhaha commented on recognize_digits/src/mnist_provider.py
> +from paddle.trainer.PyDataProvider2 import *
done

2016-12-30 07:49 UTC, dayhaha commented on recognize_digits/src/cnn_mnist.py
> +#pool2 = img_pool_layer(input=conv2, pool_size=2, stride=2, num_channels=50)
done

2016-12-30 07:49 UTC, dayhaha commented on recognize_digits/data/test.list
> +./data/raw_data/t10k
done

2016-12-30 07:49 UTC, dayhaha commented on recognize_digits/data/get_mnist_data.sh
> +#!/usr/bin/env sh
done

2016-12-30 07:49 UTC, dayhaha commented on recognize_digits/data/generate_list.py
> +o.close()
done

2016-12-30 07:50 UTC, dayhaha commented on recognize_digits/data/draw_data.py
> +        n = 10000
done

2016-12-30 07:50 UTC, dayhaha commented on recognize_digits/README.md
> +<center> ![](./image/softmax_regression.png) </center>
这个不太好改，之后可以看能不能用更好的画图软件重新画一个。

2016-12-30 07:50 UTC, dayhaha commented on recognize_digits/README.md
> +$$ net_j = \sum_j W_{i,j}x_j + b_i $$
done

2016-12-30 07:50 UTC, dayhaha commented on recognize_digits/README.md
> +通过`img = data_layer(name='pixel', size=data_size)`我们得到图片数据，而为了进行计算，该表示方法实际上将28X28的二
done

2016-12-30 07:54 UTC, dayhaha commented
主要内容已经完成，公式部分可能需要变得更加严谨一些。

2016-12-30 08:13 UTC, luotao1 commented on recognize_digits/README.md
> +<center> ![](./image/softmax_regression.png) </center>
图得和公式对应，画的不好看没关系，后面有设计师帮忙画。

2017-01-03 04:29 UTC, Zrachel requested changes

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +MNIST数据库作为一个简单的计算机视觉数据集，包含一系列如下的手写数字:
line 16 连上 line 21的第一句话“其同时包含每张图片的标签，标签告诉我们图像中包含的数字是什么。例如，上面的图片中对应的标签为[3, 4, 7, 0, 4, 1, 1, 4, 3, 1]”，放到背景介绍第二段（line9处），然后再加上介绍MNIST数据集哪年发布的；是由很多writers一起写的所以有不同patterns；经历了传统图像识别方法和基于神经网络的学习方法热潮，在http://yann.lecun.com/exdb/mnist/中可以看到各个时代的方法和结果；Lecun还基于这份数据集用LeNet5提出可以用于邮政编码的识别（website：http://yann.lecun.com/exdb/lenet/，Paper： Backpropagation applied to handwritten zip code recognition）；

我语言组织不好，总之意思就是希望让背景介绍更有趣，读者能了解更多历史。
另外一定要放上源网页的参考：http://yann.lecun.com/exdb/mnist/，并简单解释下网页中的结果。（test error）

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +该数据库的提供者Yann LeCun，他早起在手写字符识别上做了很多研究，在研究过程中
这段话和下一段交换位置，变为第三段

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +我们意图并不是展示一个对于此类问题的完美的模型，而是会首先给出一个简单的模型，然后逐步深入的优化模型，让初学者感受复杂的模型是如何带来效
这段话改为：
本章中，我们希望通过简单的模型带大家入门利用神经网络进行图像识别，并逐步深入进行模型优化。

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +给予MNIST数据，我们希望训练一个分类器f，对于每张给定的图片数据x，预测结果为f(x)，应该尽可能准确的接近真实label。
给予-基于
label - 标签(label)。

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +这是一个多分类问题，在神经网络中，多分类问题一般用softmax函数来作为输出，因此最简单的神经网络分类器就是一层输
"因此"前后没有因果关系。
这句话改为：
神经网络中通常使用`softmax`函数计算多分类问题中，每一类的概率。为了熟悉`softmax`函数，我们定义最简单的多分类网络：将输入层经过一个线性映射得到的特征，直接通过`softmax`函数进行多分类。

后面的函数，都加函数引号, 如这个评注所示。

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +$$ softmax(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}} $$
讲清楚softmax：在神经网络中，多分类问题一般用`softmax`函数来作为输出。对于有`N`个类别的多分类问题，指定`N`个输出节点，`N`维输入特征经过`softmax`将归一化为`N`个[0,1]范围内的实数值，分别表示该样本属于这`N`个类别的概率。

另外，$$包含的公式只有上下各空一行，才能在实现自成一行，下同，希望修改。

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +<img src="image/Conv_layer.png"><br/>
这个图不太明了，用这个图吧。。。
http://image.baidu.com/search/detail?ct=503316480&z=undefined&tn=baiduimagedetail&ipn=d&word=convolution%20layer&step_word=&ie=utf-8&in=&cl=2&lm=-1&st=undefined&cs=4012706518,1892940049&os=2479727483,4092764151&simid=0,0&pn=9&rn=1&di=196052014650&ln=189&fr=&fmq=1483414374710_R&fm=&ic=undefined&s=undefined&se=&sme=&tab=0&width=&height=&face=undefined&is=0,0&istype=0&ist=&jit=&bdtype=11&spn=0&pi=0&gsm=0&objurl=http%3A%2F%2Fi.dimg.cc%2F9a%2F9b%2Fc8%2F2a%2Ff5%2F2a%2F2b%2F93%2Fc5%2Fab%2Fbb%2F73%2F44%2F20%2F2b%2F6c.jpg&rpstart=0&rpnum=0&adpicid=0&ctd=1483414382100^3_1349X601%1

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +内的数，取最大值来代表这个区域，从而得到输出层。池化层的主要作用是减少网络的参数，从而能够减小计算量，并且能够
指明pooling有不同种类, max pooling, mean pooling...

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +首先是用Paddle的PyDataProvider2来为模型导入数据，如 `src/mnist_provider.py` 中所示：
所有paddle换成PaddlePaddle

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +    # following code not shown here
所有code都贴过啦吧，不用管篇幅长短

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +- 首先配置数据，如上给出在训练过程中，训练(train_list)和测试数据集(test_list)的位置，
代码说明都统一写在一段代码的前面。

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +将配置脚本 `./src/train.sh` 一下部分进行修改：
以下部分

2017-01-03 04:29 UTC, Zrachel commented on recognize_digits/README.md
> +<img src="image/softmax_train_log.png"><br/>
给CNN也补上类似的training log图吧，另外这几张图的大小都缩小到原来的1/2~2/3吧。

2017-01-03 06:18 UTC, schinger requested changes

2017-01-03 06:18 UTC, schinger commented on recognize_digits/README.md
> +本教程作为入门教程，希望给初学者讲述机器学习和Paddle的入门知识。在该教程中，我们会训练一个模型，该模型会扫描给定的图片，然后给出对应的标签。
Paddle->PaddlePaddle

2017-01-03 06:18 UTC, schinger commented on recognize_digits/README.md
> +给予MNIST数据，我们希望训练一个分类器f，对于每张给定的图片数据x，预测结果为f(x)，应该尽可能准确的接近真实label。
我们希望训练一个分类器$f$，对于每张给定的图片数据$x$，预测结果为$f(x)$   
尽量用公式表示。

2017-01-03 06:18 UTC, schinger commented on recognize_digits/README.md
> +值。在分类问题中，我们一般采用交叉熵代价损失函数(cross entropy)。
全书中第一次介绍softmax，建议可以把其损失函数公式写出来

2017-01-03 06:18 UTC, schinger commented on recognize_digits/README.md
> +### 卷积神经网络(Convolutional Neural Network, CNN)
建议增加这一节的公式描述（convolution，pooling）

2017-01-03 06:19 UTC, schinger commented on recognize_digits/README.md
> +给予MNIST数据，我们希望训练一个分类器f，对于每张给定的图片数据x，预测结果为f(x)，应该尽可能准确的接近真实label。
下同

2017-01-04 02:51 UTC, dayhaha commented
之前不小心上传了多余的文件，此次提交只是删除多余文件。  根据review的修改在下一次commit会传上来。

2017-01-04 05:30 UTC, luotao1 requested changes
1. 请按照[中文教程撰写统一标准](https://github.com/PaddlePaddle/book/wiki/中文教程撰写统一标准)，重新组织：数据准备、模型配置说明、训练模型、 应用模型这几章。其中softmax，mlp和cnn的训练命令、评估和预测命令都类似，不用分开介绍。另外，这三个识别准确率的提升，要放在一起强调展示。
2. 一段话不用分几行写，现在每行后面有空格，造成显示时出现空格。请调整成一行。
3. 除了config和dataprovider需要全部贴出来外，其他脚本不用贴代码。
4. src目录取消了，将其中的代码挪出来，并相应修改文档内容。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +该数据库的提供者Yann LeCun，他早起在手写字符识别上做了很多研究，在研究过程中
4,5,6行合并成一段。不然显示时，”则“与”有“，”因此“与”常常“，中间都有空格。下同。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +MNIST数据库作为一个简单的计算机视觉数据集，包含一系列如下的手写数字:
该数据库的提供者Yann LeCun，早先在手写字符识别上做了很多研究，并在研究过程中提出了卷积神经网络，大幅度地提高了手写字符的识别能力，也因此成为了深度学习领域的奠基人之一。如今的深度学习领域，卷积神经网络占据了至关重要的地位，从最早Yann LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet等。现在的卷积神经网络核心与LeNet类似，但它们在网络结构上要复杂很多，有了更多的组织技巧，如GoogLeNet的Inception模块、以及为了防止过拟合的正则和BatchNorm等等方法。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +本教程作为入门教程，希望给初学者讲述机器学习和PaddlePaddle的入门知识。在该教程中，我们会训练一个模型，该模型会扫描给定的图片，然后给出对应的标签。
1. 21行和22行中间空一行。
2. ”本教程作为入门教程，希望给初学者讲述机器学习和PaddlePaddle的入门知识“这句话去掉，因为这里不讲机器学习，也不会讲PaddlePaddle的入门知识。
3. 22行和25行连在一起，重新组织下。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +## 模型概览
这章小标题改为：
### Softmax回归
### 多层感知器(Multilayer Perceptron, MLP)
### 卷积神经网络(Convolutional Neural Network, CNN)
### 常见的激活函数

把问题说明挪到Softmax回归前面，就是模型概览需要一个综述的话。先介绍问题说明，然后说这章从最简单的softmax回归开始介绍、逐步深入。不然这里得看完全部的模型，才知道softmax,mlp,cnn之间的递进关系。另外，把激活函数专门拿出来介绍，不用放在mlp里面。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +####原理介绍：
所有的原理介绍标题可以去掉了。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +其拟合能力有限。因此，为了达到更好的识别效果，我们可以考虑在输入层和输出层中间加上若干个隐藏层。
61行和62行中间空一行。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +在该网络层中，我们有输入X($x_i(i=0,1,2,...,n-1)$)，输出标签Y($y_i(i=0,1,2,..9)$)，为了表示方便，以下我们都直接
$X=(x_0, x_1, ..., x_{n_1})$，统一修改Y。这里就直接用向量表示吧。
这里格式修改为（比全部连在一起看起来方便）：
- 输入XXX，输出标签XXX
- 经过第一层网络，XXX，
- 经过第二次网络，XXX
- 最后，经过输出层，XXX

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +$$ tanh(x) = 2sigmoid(2x) - 1 $$
82行应该换一行，和83行显示在同一行中。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +一个二维的activation map。每个特定的卷积核都能得到特定的activation map，如有的卷积核可能对识别边角，有的可能识别
1. activation map有中文么。
2. 94行，结果前面的逗号是英文逗号，改成中文逗号。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +#### 网络结构LeNet
LeNet网络

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +经过两次卷积->采样，然后再经过全连接，最后的输出层是softmax分类层。
这里的采样是池化层吧。建议和前面的层名统一。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +上面的网络是典型的LeNet结构，是卷积神经网络鼻祖Yann LeCun最早提出的模型。从图上我们可以看出，从输入的二维图像，
”是卷积神经网络鼻祖Yann LeCun最早提出的模型“可以去掉，因为前面说过了。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +我们首先下载 <a href="http://yann.lecun.com/exdb/mnist/">MNIST</a>数据库,该数据库是手写字符识别常用的数据库。在 `demo/mnist` 目录中执行以下命令，进行下载：
1. 该数据库前面的逗号是英文逗号，改成中文逗号
2. 已经不是`demo/mnist`目录了

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +train-labels-idx1-ubyte     训练数据标签，60,000条数据
130-133，用表格表示

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +MNIST的每条数据可以分为两部分：手写字符图片和对应的标签。图片是28X28的像素矩阵，而标签则对应着0~9的10个数字，我们随机选取训练集中的10张图片进行绘制，并给出选取图片对应的标签，绘制脚本为为 `./data/draw_data.py`。
1. 绘制脚本为，多了一个为
2. 下面的绘制脚本不用粘贴出来

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +## 数据准备
### 数据下载与介绍
包括现在的数据下载，数据说明，按顺序往下写即可，不用再列”1. 解压缩“， ”2. 数据格式“（现在显示的也不对）
### 提供数据给PaddlePaddle
介绍mnist_provider.py

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +将下载下来的数据进行gzip解压，可以在文件夹 `demo/mnist/data/raw_data` 中找到以下文件：
1. 不在文件夹`demo/mnist/data/raw_data`，现在文件夹都为book下面的了。
2. gzip解压命令可以放在get_mnist_data.sh脚本里面。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +## 模型配置说明
请按照https://github.com/PaddlePaddle/book/wiki/中文教程撰写统一标准 重新组织目录：
### 数据定义
### 算法配置
### 模型结构

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +以上封装完成了神经网络的数据层(data_layer)的工作，这样就可以通过调用数据层data_layer的方式来获取数据：
191-200行不需要了

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +## 参考文献
参考文献太少了

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +label = data_layer(name='label', size=label_size)	 # 获取标签
data layer这些应该放在网络结构中

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +    # following code not shown here
@Zrachel 的意思是：config都要贴，其他脚本不用贴

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +###训练过程
## 训练模型
将三个网络的训练都放在训练模型这章，也不用分开介绍，就是config,output,log不一样。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +python -m paddle.utils.plotcurve -i $log > plot.png
353行的plot.png得贴出来，作为结果。如果有3个模型的plot.png更好了，可以比较看下结果的区别。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +参数意义分别为：
356-363每行后面都要加标点

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +用脚本 `./src/plot_error.py` 可以画出训练过程中的误差变化曲线：
plot_error.py脚本不用贴

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +#### 评估过程
## 应用模型
### 评估预训练的模型
### 预测命令与结果

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +......
这段日志删掉，换成有打印cost这种的

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +```python
脚本不需要贴出来

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +从上面的过程中，我们了解到了机器学习的基本知识，softmax回归、多层感知器和卷积神经网络都是最基础的机器学习模型，而复杂的神经网络
”机器学习的基本知识“可以去掉，因为没讲。

2017-01-04 05:30 UTC, luotao1 commented on recognize_digits/README.md
> +模型的时候，要认识到新模型相对于其他模型来说效果提升的关键之处。此外，在体验用PaddlePaddle搭建模型识别MNIS图片的同时
MNIST少了一个T

2017-01-04 05:55 UTC, luotao1 commented
请补充.gitignore文件

2017-01-04 05:56 UTC, dayhaha commented
我在.gitignore里面把自身忽略了。。  那我改一下，把自身忽略删除吧。

2017-01-04 12:43 UTC, dayhaha commented
根据以上意见进行了修改 @luotao1  @Zrachel  @schinger ，还有以下三个部分待完善。
1. 问题说明部分。
2. 参考文献部分。
3. 公式的补充和规范。

2017-01-11 13:13 UTC, dayhaha commented
已根据review完成修改，其中 CNN的公式部分感觉内容较多，写少了无法确切的表达含义，就没有列出来，只给出了参考地址。

2017-01-13 03:57 UTC, Zrachel reviewed
About figure result

2017-01-13 03:57 UTC, Zrachel commented on recognize_digits/README.md
> +Best pass is 00047, error is 0.473053, which means predict get error as 0.343894
请check代码看下是否应该是这样的？
Best pass is 00047, training set Avgcost is 0.473053, testing set Avgcost is 0.343894
The classification accuracy on 什么set is 89.49%

因为感觉看图，如果是error不太对啊。。。

2017-01-13 04:39 UTC, dayhaha commented on recognize_digits/README.md
> +Best pass is 00047, error is 0.473053, which means predict get error as 0.343894
恩对，这里是应该改一下，确实容易引起歧义， 我把README和相应的代码改一下。

2017-01-13 06:12 UTC, luotao1 requested changes
除了模型概览和总结那部分还没看，其他的都看了，主要问题：
1. 三个配置文件请合成一个：原因是三个配置文件的大部分都是一样的，而且以后notebook是用一份py来跑。
2. 训练模型那章的结构要调整下，具体可以看comments，三个误差图中要加上测试误差的曲线。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +<td> [LeCun et al. 1998] (http://yann.lecun.com/exdb/publis/index.html#lecun-98) </td>
42行改为：`[LeCun et al. 1998](http://yann.lecun.com/exdb/publis/index.html#lecun-98) `，就是去掉中间的空格，这样后面的链接不会显示。另外这个表格中都是LeCun et al. 1998，是不是粘贴错了

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +当我们学习编程的时候，编写的第一个程序一般是实现打印"Hello World"。而就像编程语言有"Hello World"，机器学习则有 [MNIST](http://yann.lecun.com/exdb/mnist/) 数据库。MNIST数据库是手写字符，属于机器学习中典型的图像分类问题，而由于其问题简单，数据集完备，因此常常被作为机器学习入门的教程。
当我们学习编程的时候，编写的第一个程序一般是实现打印"Hello World"。而机器学习（或深度学习）的入门教程，一般都是[MNIST](http://yann.lecun.com/exdb/mnist/) 数据库上的手写识别问题。原因是手写识别问题属于典型的图像分类问题，比较简单，同时MNIST数据集也很完备。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +其同时包含每张图片的标签，标签告诉我们图像中包含的数字是什么。例如，上面的图片中对应的标签为[3, 4, 7, 0, 4, 1, 1, 4, 3, 1]。该数据有60,000条数据的训练集，10,000条数据的测试集。其是更大的数据集NIST的一个子集。MNIST数据集中的数字经过了大小归一化和图片居中的处理。 MNIST数据集从NIST的Special Database 3和Special D
MNIST数据库作为一个简单的计算机视觉数据集，包含一系列如图1所示的手写数字图片和对应的标签。图片是28X28的像素矩阵，而标签则对应着0~9的10个数字。每张图片都经过了大小归一化和居中处理。（这里图1可以找设计师p一下，把标签也弄进去。 @Zrachel ）

MNIST数据集是从NIST（NIST要有链接）的Special Database 3（SD-3）和Special Database 1（SD-1）构建而来。由于SD-3是由美国人口调查局的员工进行标注，SD-1是由美国高中生进行标注，因此SD-3比SD-1更干净也更容易识别。Yann LeCun等人从SD-1和SD-3中各取一半作为MNIST的训练集（60000条数据）和测试集（10000条数据），其中训练集来自250位不同的标注员，而且训练集和测试集的标注员也完全不相同。

你再顺一下。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +MNIST数据库作为一个简单的计算机视觉数据集，包含一系列如下的手写数字:
第6行和11行合并，统一放在图的前面。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +<img src="image/mnist_example_image.png"><br/>
图缩小，`<img src="image/flowers.png" width="400" ><br/> `，具体数值你调一下

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +该数据库的提供者Yann  LeCun，早先在手写字符识别上做了很多研究，并在研究过程中提出了卷积神经网络，大幅度地提高了手写字符的识别能力，也因此成为了深度学习领域的奠基人之一。如今的深度学习领域，卷积神经网络占据了至关重要的地位，从最早Yann LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet等。现在的卷积神经网络核心与LeNet类似，但
如GoogLeNet的Inception模块、以及为了防止过拟合的正则和BatchNorm等等方法。这里正则和BN方法都是为了防止拟合么？

@Zrachel 因为Inception模块和BN都在图像分类中介绍，要加个链接么

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +7. 卷积神经网络(Convolutional nets)
17-25行去掉。因为没有展开讲，所以不用1个1行来突出显示。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +我们要介绍的Softmax回归，多层感知器和卷积神经网络就分别对应上面的1、6和7分类器，以下为表格中相关的部分：
27行、“Yann LeCunn关于[MNIST数据库] (http://yann.lecun.com/exdb/mnist/) 的网站中介绍多种分类器加上多种预处理方法对于该数据库识别效果的表格。”和97行放在一起，重新组织。（对表格的描述统一放在表格上面，不要上下都讲）

http://yann.lecun.com/exdb/mnist/ 这个链接对应的不是“MNIST数据库”这个词。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
表格中分类器和预处理这两列的英文全部改成中文。像2-layer NN，是属于多层感知器吧。300HU，HU代表什么？分类器的名字希望更简洁清晰点。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +本章中，我们希望通过简单的模型带大家入门利用神经网络进行图像识别，并逐步深入进行模型优化。
99行不通顺，简单的模型指什么？请修改。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +基于MNIST数据，我们希望训练一个分类器 $f$，对于每张给定的图片数据 $X$ ，预测结果为 $ Y = f(x) $ ，应该尽可能准确的接近真实标签L。
1. X、x、Y，大小写不统一。整个模型概览的公式描述都要统一
2. 基于MNIST数据，我们希望训练一个分类器 $f$，对于每张给定的图片数据 $X$ ，预测结果$Y = f(x)$ 都应该尽可能准确地接近真实标签$L$。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +- 我们首先下载 <a href="http://yann.lecun.com/exdb/mnist/">MNIST</a>数据库,该数据库是手写字符识别常用的数据库。执行以下命令，进行下载：
下载MNIST数据并解压缩的命令如下：（gzip命令也写进get_mnist_data.sh脚本里，不要让用户再一个个解压缩了，同时去掉最前面的“-”，这节的三个“-”都去掉）

我看脚本里面会生成train.list和test.list，那么在这里也要简单介绍下，可以这样说：并将训练集和测试集的地址分别写入train.list 和 test.list两个文件中，供PaddlePaddle读取。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +- 将下载下来的数据进行 `gzip` 解压，可以在文件夹 `data/raw_data` 中找到以下文件：
可以在文件夹 `data/raw_data` 中看到以下文件：

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +<center>
248和257可以去掉，这里表格无法居中。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +|train-labels-idx1-ubyte|  训练数据标签，60,000条数据 |
两条train应该放在前面，一般都是先讲训练再讲测试。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +-     MNIST的每条数据可以分为两部分：手写字符图片和对应的标签。图片是28X28的像素矩阵，而标签则对应着0~9的10个数字，我们随机选取训练集中的10张图片进行绘制，并给出选取图片对应的标签，绘制脚本为 `./data/draw_data.py`。
1. 260行-268行可以全部去掉。这部分在之前的背景介绍里讲过了。
2. 绘制脚本是用来做什么呢？而且上传的文件里面没有draw_data.py。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +(具体的过程见 `PaddlePaddle_root_path/python/paddle/trainer/PyDataProvider2.py`，从而方便以PaddlePaddle DataProvider对象的形式进行调用。
272-275行改成：
我们使用Python接口传递数据给系统，下面 dataprovider.py 针对CIFAR10数据给出了完整示例。

几点要求：
1. 需要解释下input_types中的pixel和label，是两个输入，一个是图片的28*28像素矩阵，一个是标签有10类。语句请自行组织。
2. 这里可以不要用cache么？用cache还得解释。
3. 贴出来的代码里面的英文注释换成中文（源代码可以不改）。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +    l = open(labelf, "rb")
284-287行请缩减成
```
f = open(filename + "-images-idx3-ubyte", "rb") #打开图片文件
l = open(filename + "-labels-idx1-ubyte", "rb") #打开标签文件
```

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +        n = 10000
```
n =60000 if if "train" in filename else 10000
```
用于缩减代码，请修改对应源代码

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +    l.read(8)
289-290需要注释，为什么没要跳过16个字节和8个字节

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +    labels = numpy.fromfile(l, 'ubyte', count=n).astype("int")
298-301行每行都要注释

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +首先配置数据，如上给出在训练过程中，训练(train_list)和测试数据集(test_list)的位置，指定数据提供模块(module)函数，目标函数(obj)代表在module中提供数据的函数。
在模型配置中，定义通过 define_py_data_sources2 函数从 dataprovider 中读入数据， 如果该配置文件用于预测，则不需要数据定义部分。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +####################Data Configuration ##################
318,319行去掉

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +######################Algorithm Configuration #############
355行去掉

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +的速度，影响着网络的训练收敛速度有关系，训练方法( `learning_method` )代表训练过程在更新权重时采用动量优化器( `MomentumOptimizer` )，其中参数0.9代表动量优化每次保持前一次速度的0.9倍，正则化( `regularization` )是防止网络过拟合的一种手段，此处采用L2正则化。
331,332行放到代码下面分点介绍。
- batch_size: XXX
- learning_rate: XXX
- learning_method: XXX
- regularization: XXX

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +#######################Network Configuration #############
350-351行都去掉

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +#######################Network Configuration #############
365-366行去掉

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +#######################Network Configuration #############
381-382行去掉

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +I1227 02:58:12.873564   275 Util.cpp:229] copy mlp_mnist.py to ./mlp_mnist_model/pass-00088
这段日志可以精简，保存446行到455行即可（就是保存一个pass）。456行在最新paddle代码中已经不打印了。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +```
此段挪上去。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +图8. softmax回归训练误差图<br/>
图名：softmax回归的误差曲线图。下面两个图名统一改。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +得到的结果类似如下：
评估模型结果如下：（下面两段同样改）

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +从上面过程中可以看到，softmax回归模型分类效果最好的时候是pass-00047，分类准确率为89.49%，而最终的pass-00099的准确率为85.39%。从图中也可以看出，准确率最好的时候并以不定是最后一个pass的模型。
从评估模型的结果可以看到，softmax回归模型的最好分类效果出现在pass-00047，分类准确率为89.49%。从图8中也可以看出，最好的准确率不一定是最后一个pass的模型。（这里简单要说一下原因，为什么最好的准确率不是最后一个模型）

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +从训练日志中我们可以看出，最终训练的准确率为94.95%。这是多层感知器网络分类分类效果，可以看到其相对于softmax回归来说有了显著的分类效果的提升。但是，这还不是最好的分类效果，后面，我们可以看到卷积神经网络对于图像分类能够达到更为惊人的准确率。
从评估模型的结果可以看到，多层感知器网络模型的最好分类准确率为94.95%，相比softmax回归模型有了显著的提升。（后面补充说一下原因，一句话即可）

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +### 训练误差图及评估
下面的三个误差图要把训练误差和测试误差统一放上去，可以参考[图像分类](https://github.com/PaddlePaddle/book/tree/develop/image_classification)的图12，图里面的点就不要画了。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +## 训练模型
重新组织下“训练模型”这节

### 训练命令及日志
1. 通过配置训练脚本 `train.sh` 来执行训练过程：
XXX（放已有的内容411-439行）
2. 用脚本 `plot_error.py` 可以画出训练过程中的误差变化曲线：
464-466行
3. 用脚本 `evaluate.py ` 可以选出最好的Pass训练出来的模型：
477-479行

### Softmax回归的训练结果
### 多层感知器的训练结果
### 卷积神经网络的训练结果

把应用模型的前面大部分拿上来。应用模型那里是要讲如何用模型进行预测，就是保留“预测命令与结果”。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +从训练日志中我们可以看出，最终训练的准确率为99.20%。由此可以看到，对于图像问题而言，卷积神经网络能够比一般全连接网络达到更好的识别效果，而这与卷积层的性质是分不开的。同时，我们可以看到，卷积神经网络在很早的时候就能达到好的效果，说明其训练收敛的速度很快。
从评估模型的结果可以看到，卷积神经网络的最好分类准确率达到惊人的99.20%。由此可以看到，对于图像问题而言，卷积神经网络能够比一般的全连接网络达到更好的识别效果，而这与卷积层的性质（什么性质）是分不开的。同时，从图10中可以看到，卷积神经网络在很早的时候就能达到好的效果，说明其训练的收敛速度非常快。

你再顺一下。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +用脚本  `predict.py` 用训练好的模型进行预测，例如softmax回归中：
脚本`predict.py` 可以对训练好的模型进行预测，例如softmax回归中：

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +```
1. 526行放在522行前面
2. ../data/raw_data 应该是data/raw_data吧，现在脚本都在根目录下了。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +0 0
需要修改下脚本，537行打印出来的两个0前面加上“预测的结果和实际的标签”的英文描述。
Predict number: 0
Actual number: 0
534行前面也写一个：各个数字的生成概率 （Generating probability of each digit）
@Zrachel

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +根据提示，输入需要预测的图片的序号，则分类器能够给出预测的结果和实际的标签。
根据提示，输入需要预测的图片序号，则分类器能够给出各个数字的生成概率、预测的结果（取最大生成概率对应的数字）和实际的标签。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +上面，给出的向量是神经网络输出的十维向量，可以理解为分类为各个数字的概率，实际预测的类即为向量中值最大的一项。如上，代表该分类器接近100%的认为该图片上面的数字为0，而实际标签给出的类也确实如此。
从结果看出，该分类器接近100%地认为第3张图片上面的数字为0，而实际标签给出的类也确实如此。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +### 模型结构
把三个配置合成一个，
```
def softmax()
def mlp()
def lenet5()

data_size = 1 * 28 * 28
label_size = 10
img = data_layer(name='pixel', size=data_size)

predict=softmax(img)
#predict=mlp(img)
#predict=lenet5(img)

if not is_predict:
 +    lbl = data_layer(name="label", size=label_size)
 +    outputs(classification_cost(input=predict, label=lbl))
 +else:
 +    outputs(predict)

```

这些都是一样的。所以只要把不同的地方写成三个def函数。函数名字可以取的更好一点。
介绍的时候，先整体说一下，然后分别介绍三个def函数。

2017-01-13 06:12 UTC, luotao1 commented on recognize_digits/README.md
> +6. http://cs231n.github.io/convolutional-networks/
参考文献需要在文中对应位置标出。第1个和第6个，没有网页名字。

2017-01-13 06:15 UTC, luotao1 commented
README贴出来的代码里面，将现在的英文注释全改成中文注释。源代码里面可以不用改。

2017-01-13 06:26 UTC, dayhaha commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
这个表格是 http://yann.lecun.com/exdb/mnist/ 中的节选部分，因为 @Zrachel  让我说明一下里面表格的内容，但是我看表格太多，就只选了一部分。   然后就没有改表格的内容。

2017-01-13 06:30 UTC, dayhaha commented on recognize_digits/README.md
> +|train-labels-idx1-ubyte|  训练数据标签，60,000条数据 |
这个表格我试了居中不了，有什么办法么？

2017-01-13 06:39 UTC, dayhaha commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
这块是想介绍一下 http://yann.lecun.com/exdb/mnist/  的表格内容，觉得怎么介绍比较好呢？

2017-01-13 06:49 UTC, dayhaha commented on recognize_digits/README.md
> +-     MNIST的每条数据可以分为两部分：手写字符图片和对应的标签。图片是28X28的像素矩阵，而标签则对应着0~9的10个数字，我们随机选取训练集中的10张图片进行绘制，并给出选取图片对应的标签，绘制脚本为 `./data/draw_data.py`。
这块之前加这个脚本本来是想像[mxnet](http://mxnet.io/tutorials/python/mnist.html) 中一样的。
用户在notebook里面直接执行这段脚本，然后可以看到mnist的数据具体是什么样子的图，有一个交互的过程。 现在既然notebook里面不放这些脚本的话，那我就删除掉吧。 

不过其实我觉得mxnet里面那样做挺好的
<img width="942" alt="2017-01-13 2 47 53" src="https://cloud.githubusercontent.com/assets/6861004/21920949/685a9294-d99f-11e6-9d6d-512e5bef3b17.png">

2017-01-13 06:55 UTC, Zrachel commented on recognize_digits/README.md
> +该数据库的提供者Yann  LeCun，早先在手写字符识别上做了很多研究，并在研究过程中提出了卷积神经网络，大幅度地提高了手写字符的识别能力，也因此成为了深度学习领域的奠基人之一。如今的深度学习领域，卷积神经网络占据了至关重要的地位，从最早Yann LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet等。现在的卷积神经网络核心与LeNet类似，但
到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet等
->
到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet等（我们将在[下一章](https://github.com/PaddlePaddle/book/blob/develop/image_classification/README.md)中介绍这两个模型）

2017-01-13 07:01 UTC, luotao1 commented on recognize_digits/README.md
> +-     MNIST的每条数据可以分为两部分：手写字符图片和对应的标签。图片是28X28的像素矩阵，而标签则对应着0~9的10个数字，我们随机选取训练集中的10张图片进行绘制，并给出选取图片对应的标签，绘制脚本为 `./data/draw_data.py`。
@Zrachel 这部分你怎么看

2017-01-13 07:01 UTC, luotao1 commented on recognize_digits/README.md
> +|train-labels-idx1-ubyte|  训练数据标签，60,000条数据 |
@dayhaha 表格就是居中不了，所以不用管了。

2017-01-13 07:02 UTC, luotao1 commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
@Zrachel 这部分表格我觉得还是要翻译一下，不能直接截取过来。还是要稍微加工下。

2017-01-13 07:05 UTC, Zrachel commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
这个表格做得很用心。。。我本意是大概说一下就行，比如：
自从该数据集发布以来，有很多算法进行实验。从1998年，LeCun分别用单层线性分类器、多层感知器（multilayer perceptron, MLP）和 多层卷积神经网络LeNet进行实验，使得测试集上的误差不断下降（加参考文献）。

2017-01-13 07:09 UTC, Zrachel commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
此后，科学家们分别基于K近邻(K-Nearest Neighbors)算法、支持向量机（SVM）、神经网络和Boosting方法在该数据集上做了大量实验（加参考）。

2017-01-13 07:11 UTC, dayhaha commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
好的，那表格还需要么？ 不要的话就删除了？

2017-01-13 07:12 UTC, Zrachel commented on recognize_digits/README.md
> +<td> linear classifier (1-layer NN) </td>
我觉得不需要表格了，这块参考文献大多可share，预处理大家又不关心，所以建议用文本描述。

2017-01-13 07:16 UTC, Zrachel commented on recognize_digits/README.md
> +-     MNIST的每条数据可以分为两部分：手写字符图片和对应的标签。图片是28X28的像素矩阵，而标签则对应着0~9的10个数字，我们随机选取训练集中的10张图片进行绘制，并给出选取图片对应的标签，绘制脚本为 `./data/draw_data.py`。
这个功能可以有，但不是要自己贴图。所以line 260 - line 268建议改为：
 - 用户可以通过以下脚本随机绘制10张图片
```bash
./data/draw_data.py
```

2017-01-13 07:17 UTC, Zrachel commented on recognize_digits/README.md
> +0 0
同意

2017-01-13 07:26 UTC, dayhaha commented
卷积过程比较复杂，我看有几个比较好的展示形式，我们要详细展示这样一个过程么？ @luotao1  @Zrachel 
[mxnet](http://mxnet.io/tutorials/python/mnist.html)
<img width="794" alt="2017-01-13 3 22 14" src="https://cloud.githubusercontent.com/assets/6861004/21921617/4fcceb5a-d9a4-11e6-90a8-9c91c7360a31.png">

[standford cs231n](http://cs231n.github.io/convolutional-networks/) 动态图
<img width="693" alt="2017-01-13 3 25 12" src="https://cloud.githubusercontent.com/assets/6861004/21921639/8cb9161a-d9a4-11e6-89ab-f1ab5278c39d.png">
不过Markdown好像不支持动态图吧？

2017-01-13 07:59 UTC, Zrachel reviewed
背景介绍 修改建议

2017-01-13 07:59 UTC, Zrachel commented on recognize_digits/README.md
> +该数据库的提供者Yann  LeCun，早先在手写字符识别上做了很多研究，并在研究过程中提出了卷积神经网络，大幅度地提高了手写字符的识别能力，也因此成为了深度学习领域的奠基人之一。如今的深度学习领域，卷积神经网络占据了至关重要的地位，从最早Yann LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet等。现在的卷积神经网络核心与LeNet类似，但
第一处"卷积神经网络"->卷积神经网络(Convolutional Neural Network)

2017-01-13 07:59 UTC, Zrachel commented on recognize_digits/README.md
> +该数据库的提供者Yann  LeCun，早先在手写字符识别上做了很多研究，并在研究过程中提出了卷积神经网络，大幅度地提高了手写字符的识别能力，也因此成为了深度学习领域的奠基人之一。如今的深度学习领域，卷积神经网络占据了至关重要的地位，从最早Yann LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet等。现在的卷积神经网络核心与LeNet类似，但
。现在的卷积神经网络核心与LeNet类似，但它们在网络结构上要复杂很多，有了更多的组织技巧，如GoogLeNet的Inception模块、以及为了防止过拟合的正则和BatchNorm等等方法。
->
，人们在图像分类领域，利用卷积神经网络得到了一系列惊人的结果。

PS：背景介绍不要这么高深

2017-01-13 07:59 UTC, Zrachel commented on recognize_digits/README.md
> +事实上，许多人对MNIST手写字符的识别做了研究，除了采用不同的分类器之外，人们还考虑用许多预处理的方法（如deskewing（去除歪曲），noise removal（去噪），blurring（模糊）等等）来提高识别的准确率。 Yann LeCunn关于[MNIST数据库] (http://yann.lecun.com/exdb/mnist/) 的网站中介绍多种分类器加上多种预处理方法对于该数据
line 16~line 97删掉，改成：

自从该数据集发布以来，有很多算法在MNIST上进行实验。从1998年，LeCun分别用单层线性分类器、多层感知器（multilayer perceptron, MLP）和 多层卷积神经网络LeNet进行实验，使得测试集上的误差不断下降（从？？？下降到？？？）。此后，科学家们分别基于K近邻(K-Nearest Neighbors)算法、支持向量机（SVM）、神经网络和Boosting方法在该数据集上做了大量实验（http://yann.lecun.com/exdb/mnist/），并采用多种预处理方法（如deskewing（去除歪曲），noise removal（去噪），blurring（模糊）等等）来提高识别的准确率。

其中括号都用中文括号

@luotao1 你觉得呢？

2017-01-13 09:17 UTC, luotao1 reviewed
模型概览和总结已全部看完了。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +从上面的过程中，我们了解到了softmax回归、多层感知器和卷积神经网络都是最基础的机器学习模型，而复杂的神经网络都是从这些衍生出来的，因此了解了这些基本的东西之后，对于我们之后的学习大有裨益。在这过程中，我们也观察到当我们将模型从简单的Softmax回归到稍微复杂的卷积神经网络的时候，识别准确率有了大幅度的提升，而这与卷积层的加入是密切联系的，这启发我们在之后遇到新的模型的时候，要认识到新模型
本章的softmax回归、多层感知器和卷积神经网络是最基础的深度学习模型，后续章节中复杂的神经网络都是从它们衍生出来的，因此这几个模型对之后的学习大有裨益。同时，我们也观察到从最简单的Softmax回归到稍复杂的卷积神经网络的时候，MNIST数据集上的识别准确率有了大幅度的提升，原因是卷积层（XXX，请补充）。在之后学习新模型的时候，希望大家也要深入到新模型相比原模型带来效果提升的关键之处。此外，本章还介绍了PaddlePaddle模型搭建的基本流程，从dataprovider的编写、网络层的构建，到最后的训练和预测。对这个流程熟悉以后，大家就可以用自己的数据，定义自己的网络模型，并完成自己的训练和预测任务。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +神经网络模型的构建包括网络配置在内，通常有以下几个步骤:
137-145行的第一句话（对于以上步骤4，神经网络的训练采用 `backpropagation` 的形式，其一般会定义一个损失函数（也称目标函数），训练的目的是为了减小目标函数的值。），全部可以删掉了。 @Zrachel 会放到第一章 新手入门中。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +###问题说明：
104行改成 ### 分类问题介绍 （后面冒号不要）

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +基于MNIST数据，我们希望训练一个分类器 $f$，对于每张给定的图片数据 $X$ ，预测结果为 $ Y = f(x) $ ，应该尽可能准确的接近真实标签L。
把112行和114行的第一句话拿到这里（语句重新组织）。在分类问题说明这一节，需要说明y和x到底是什么。因为y和x对三个分类器都是一样的，所以后面三个小节都不用再描述了。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +在该网络层中，我们有输入X($x_i(i=0,1,2,...,n-1)$)，输出标签Y($y_i(i=0,1,2,..9)$)，为了表示方便，以下我们都直接用向量计算来表示。经过第一层网络，我们可以得到：
在softmax回归中，我们采用了最简单的两层神经网络，分别为输入的data层和输出的 softmax层。由于这个模型很简单，其拟合能力也有限，因此为了达到更好的识别效果，我们可以考虑在输入层和输出层的中间加上若干个隐藏层。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +这是一个多分类问题，神经网络中通常使用   `softmax` 函数计算多分类问题中每一类的概率。为了熟悉 `softmax` 函数，我们定义最简单的多分类网络：将输入层经过一个线性映射得到的特征，直接通过 `softmax` 函数进行多分类。
神经网络中通常使用 $softmax$函数计算多分类问题中每一类的概率。这里我们定义最简单的多分类网络：将输入层经过一个线性映射得到的特征，直接通过$softmax$函数进行多分类。

该小节中的`softmax`函数都改为$softmax$函数，下同

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +$$ net_i = \sum_j W_{i,j}x_j + b_i $$
这里不要出现net_i，直接y_i = softmax(\sum_j W_{i,j}x_j + b_i)

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +$$ softmax(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}} $$
其中$softmax(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}}$，120行可以去掉。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +在神经网络中，多分类问题一般用 `softmax` 函数来作为输出。对于有 `N` 个类别的多分类问题，指定 `N` 个输出节点，`N` 维输入特征经过 `softmax` 将归一化为 `N` 个[0,1]范围内的实数值，分别表示该样本属于这N个类别的概率。此处的 $y_i$ 即对应该图片为数字 `i` 的预测概率。
128行第一句话可以删掉。这里所有的`N`都改成$N$

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +注：图中权重用黑线表示，偏置用红线表示，+1代表偏置参数的系数为1
134行移到130行后面

图2为Softmax回归模型的示意图，其中权重用黑线表示，偏置用红线表示，+1代表偏置参数的系数为1。下面两张图也是类似这样描述。（不用在图标题下面写注，因为注这行比图标题长太多了）

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +比如说，$y_i$组成的向量$Y$为[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]，每一维分别代表图像数字预测为0~9的概率。然后，我们用 $label_i$ (向量表示为$L$)来代表预测的输出。输入层的数据X传到 `softmax` 层，在激活操作之前，会乘以相应的权重 $W$ ，并加上偏置变量 $b$ ，具体如下：
$Y=[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]$
这里label用L表示，下面CE那个公式还是用的label

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +事实上，许多人对MNIST手写字符的识别做了研究，除了采用不同的分类器之外，人们还考虑用许多预处理的方法（如deskewing（去除歪曲），noise removal（去噪），blurring（模糊）等等）来提高识别的准确率。 Yann LeCunn关于[MNIST数据库] (http://yann.lecun.com/exdb/mnist/) 的网站中介绍多种分类器加上多种预处理方法对于该数据
这段修改我觉得可以。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +注：上面公式为softmax输出层的交叉熵代价损失函数，CE为cross entropy的简称，y是预测每一类的概率，label是标签，为one-hot向量（事实上，由于label为one-hot向量，上面公式中只有一项不为0）。
这里不要说label是one-hot向量，不然还要解释one-hot向量是什么。label的定义也可以放到“分类问题说明”中

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +上面，`activation` 代表激活函数，其常见的为 `sigmoid` ，`tanh` 或 `ReLU` 等函数。
1. 公式中的activation一般是不是用\theta 表示。 @Zrachel 
2. 161行的激活函数给链接 `[激活函数](#常见激活函数介绍)`，常见的有$sigmoid$ 、$tanh$ 和$ReLU$等。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +- sigmoid激活函数：
221行可以放在219行后面，不用再换行了。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +- ReLU激活函数：
233行放在231行后面

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +- tanh激活函数：
1. 225行放在223行后面，227行和229行连起来
2. $tanh$函数只是规模变化（这是什么意思？规模指什么）的$sigmoid$函数

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +得到的P即为最后的预测结果向量。
171行，得到的P，图里没有p，公式里也没有p

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +#### 卷积层
卷积层等新的更详细描述再看，现在189-193这部分公式看的还是很费劲

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +上面的网络是典型的LeNet结构，从中我们可以看出，从输入的二维图像，经过两次卷积->池化，然后再经过全连接，最后的输出层是 `softmax` 分类层。
1. 为什么这里讲LeNet-5呢，不讲LeNet-1，可以稍微解释下。
2. “上面的网络是典型的LeNet结构”，为什么呢？这段可以换一种表达：
LeNet网络的典型结构是：输入的二维图像，首先经过两次卷积层到池化层，再经过全连接层，最后使用softmax分类作为输出层。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +更详细的关于卷积神经网络的具体知识可以参考 [cs231n] ( http://cs231n.github.io/convolutional-networks/ )
216放到214行后面。参考cs231n，换一个说法。读者不知道cs231n是什么

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +卷积神经网络另外一个重要的概念就是池化层，这是非线性下采样的一种形式。有许多种非线性函数能够完成下采样的功能，而其中用的最多的就是最大池化。如上所示，其用特定大小不重叠的矩形框将输入层分成不同的区域，然后对于每一个矩形框内的数，取最大值来代表这个区域，从而得到输出层。池化层的主要作用是减少网络的参数，从而能够减小计算量，并且能够控制过拟合。通常情况下在卷积层的后面都会加上一个池化层。
池化是非线性下采样（这里要简单介绍非线性下采样，或给链接么 @Zrachel ）的一种形式，主要作用是通过减少网络的参数来减小计算量，并且能够在一定程度上控制过拟合（原来写的太绝对）。通常在卷积层的后面都会加上一个池化层。

池化包括最大池化、平均池化等。其中最大池化是用不重叠的矩形框将输入层分成不同的区域，对于每一个矩形框内的数取最大值作为输出层，如图5所示。

2017-01-13 09:17 UTC, luotao1 commented on recognize_digits/README.md
> +例如，对于图上的矩阵，用二维矩阵X(X的维度为$4\times4$)表示，采用$F=2$的$2\times2$的过滤器（filter）进行最大池化，步长Stride设置为$S=2$，由于$F=S$，该池化为不重叠池化。
204-206行可以去掉了。那个图很容易能看出最大池化。206行如果写了不重叠池化，还得介绍重叠池化。

2017-01-17 07:15 UTC, luotao1 reviewed
背景介绍、数据准备、参考文献三部分意见。
1. 参考文献要在文中有引用
2. 数据准备里的数据格式说明不需要放

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +MNIST数据集作为一个简单的计算机视觉数据集，包含一系列如图1所示的手写数字图片和对应的标签。图片是28x28的像素矩阵，而标签则对应着0~9的10个数字。每张图片都经过了大小归一化和居中处理。
1. ，标签则对应着0~9的10个数字
2. 13行和14行合并，一起放到6行的后面，图1放在14行后面。

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet、ResNet等（我们将在下一章中介绍这三个模型），人们在图像分类领域，利用卷积神经网络得到了一系列惊人的结果。
1. 17,18行合并。
2. 17行开始改成：Yann  LeCun早先在手写字符识别上做了很多研究
3. 我们将在下一章中介绍这三个模型-》请参见[图像分类](放链接)教程

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +自从该数据集发布以来，有很多算法在MNIST上进行实验。1998年，LeCun分别用单层线性分类器、多层感知器（Multilayer Perceptron, MLP）和多层卷积神经网络LeNet进行实验，使得测试集上的误差不断下降（从12%下降到0.7%）。此后，科学家们分别基于K近邻（K-Nearest Neighbors）算法、支持向量机（SVM）、神经网络和Boosting方法在该数据集上
1. 第一句改成：有很多算法在MNIST数据集上进行实验。
2. 科学家们又基于K近邻（K-Nearest Neighbors）算法、支持向量机（SVM）、神经网络和Boosting方法等做了大量实验，并采用多种预处理方法（如去除歪曲、去噪、模糊等）来提高识别的准确率。

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +我们首先下载 [MNIST](http://yann.lecun.com/exdb/mnist/) 数据库,该数据库是手写字符识别常用的数据库。执行以下命令，进行下载并解压缩，并将训练集和测试集的地址分别写入train.list和test.list两个文件，供PaddlePaddle读取。
144行第一句话不用了，在前文已经知道MNIST是常用数据库了。

执行以下命令，下载[MNIST](http://yann.lecun.com/exdb/mnist/)数据库并解压缩，然后将训练集和测试集的地址分别写入`train.list`和`test.list`两个文件，供PaddlePaddle读取。

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +6. http://cs231n.github.io/convolutional-networks/
纯链接的参考文献，比如1/6/7，不用列出来了，在文章中对应的地方加上链接即可。

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +数据是以C array的方式进行存储的，即最后一维的索引变量变化最快。
159-200行的数据格式说明不需要了 @Zrachel

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +用户可以通过以下脚本随机绘制10张图片
用户可以通过以下脚本随机绘制10张图片（可参考图1）：

2017-01-17 07:15 UTC, luotao1 commented on recognize_digits/README.md
> +        yield {"pixel": images[i, :], 'label': labels[i]}
可以在注释里简单说一下magic,n,rows,cols是什么，
`# 读取开头的四个参数，分别是XXX、XXX、行数和列数`

2017-01-17 07:35 UTC, dayhaha commented on recognize_digits/README.md
> +数据是以C array的方式进行存储的，即最后一维的索引变量变化最快。
哦。。  好吧。。

2017-01-17 07:39 UTC, dayhaha commented on recognize_digits/README.md
> +LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet、ResNet等（我们将在下一章中介绍这三个模型），人们在图像分类领域，利用卷积神经网络得到了一系列惊人的结果。
这里的链接就放图像分类在github上的链接？

2017-01-17 07:51 UTC, dayhaha commented on recognize_digits/README.md
> +#### 卷积层
done

2017-01-17 07:51 UTC, dayhaha commented on recognize_digits/README.md
> +- tanh激活函数：
done

2017-01-17 07:51 UTC, dayhaha commented on recognize_digits/README.md
> +        yield {"pixel": images[i, :], 'label': labels[i]}
done

2017-01-17 07:51 UTC, dayhaha commented on recognize_digits/README.md
> +### 模型结构
done

2017-01-17 08:14 UTC, dayhaha commented on recognize_digits/README.md
> +比如说，$y_i$组成的向量$Y$为[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]，每一维分别代表图像数字预测为0~9的概率。然后，我们用 $label_i$ (向量表示为$L$)来代表预测的输出。输入层的数据X传到 `softmax` 层，在激活操作之前，会乘以相应的权重 $W$ ，并加上偏置变量 $b$ ，具体如下：
done

2017-01-17 08:14 UTC, dayhaha commented on recognize_digits/README.md
> +注：上面公式为softmax输出层的交叉熵代价损失函数，CE为cross entropy的简称，y是预测每一类的概率，label是标签，为one-hot向量（事实上，由于label为one-hot向量，上面公式中只有一项不为0）。
done

2017-01-17 08:14 UTC, dayhaha commented on recognize_digits/README.md
> +|train-labels-idx1-ubyte|  训练数据标签，60,000条数据 |
done

2017-01-17 08:14 UTC, dayhaha commented on recognize_digits/README.md
> +比如说，$y_i$组成的向量$Y$为[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]，每一维分别代表图像数字预测为0~9的概率。然后，我们用 $label_i$ (向量表示为$L$)来代表预测的输出。输入层的数据X传到 `softmax` 层，在激活操作之前，会乘以相应的权重 $W$ ，并加上偏置变量 $b$ ，具体如下：
done

2017-01-17 08:14 UTC, dayhaha commented on recognize_digits/README.md
> +注：上面公式为softmax输出层的交叉熵代价损失函数，CE为cross entropy的简称，y是预测每一类的概率，label是标签，为one-hot向量（事实上，由于label为one-hot向量，上面公式中只有一项不为0）。
done

2017-01-17 08:14 UTC, dayhaha commented on recognize_digits/README.md
> +|train-labels-idx1-ubyte|  训练数据标签，60,000条数据 |
done

2017-01-18 09:06 UTC, Zrachel reviewed
before MLP

2017-01-18 09:06 UTC, Zrachel commented on recognize_digits/README.md
> +$Y$和$L$具体含义为：比如说，$y_i$组成的向量$Y$为[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]，每一维分别代表图像数字预测为0~9的概率；而此时$label_i$组成的向量$L$可能为[0,1,0,0,0,0,0,0,0,0]，其代表标签为1，即输入$X$代表图片的数字为1。则$Y$和$L$尽可能接近的意思是$Y$中概率最大的一维为$L$中对应的标签，并且概率越
$Y$和$L$具体含义为：比如说，$y_i$组成的向量$Y$为[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]，每一维分别代表图像数字预测为0~9的概率；
->
$Y$和$L$具体含义为：比如说，预测结果$Y$为[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]，每一维$y_i$分别代表图像数字预测为第$i$类的概率（$i\in[0,9]$）；

2017-01-18 09:06 UTC, Zrachel commented on recognize_digits/README.md
> +下面我们一一介绍本章中使用的三个分类器Softmax回归、多层感知器、卷积神经网络。
三个分类器->三个基本图像分类网络

2017-01-18 09:06 UTC, Zrachel commented on recognize_digits/README.md
> +$Y$和$L$具体含义为：比如说，$y_i$组成的向量$Y$为[0.2,0.3,0,1,0,0.1,0.1,0.1,0.1,0]，每一维分别代表图像数字预测为0~9的概率；而此时$label_i$组成的向量$L$可能为[0,1,0,0,0,0,0,0,0,0]，其代表标签为1，即输入$X$代表图片的数字为1。则$Y$和$L$尽可能接近的意思是$Y$中概率最大的一维为$L$中对应的标签，并且概率越
而图像的真实标签$L$由$label_i$表示表示，其中只有一维为1，其他为0，如[0,1,0,0,0,0,0,0,0,0]，其代表标签为第二类，即标签为0到9中的1。

2017-01-18 09:06 UTC, Zrachel commented on recognize_digits/README.md
> +神经网络的训练采用 `backpropagation` 的形式，其一般会定义一个损失函数（也称目标函数），训练的目的是为了减小目标函数的值。在分类问题中，我们一般采用交叉熵代价损失函数(cross entropy)，其形式如下：
神经网络一般会定义一个损失函数（也称目标函数），训练的过程是通过改变网络参数来最小化这个损失函数，此过程可以采用`backpropagation` 算法。在分类问题中，我们一般采用交叉熵代价损失函数(cross entropy)，其形式如下：

2017-01-18 09:06 UTC, Zrachel commented on recognize_digits/README.md
> +上面公式为softmax输出层的交叉熵代价损失函数，CE为cross entropy的简称，y是预测每一类的概率，label是标签。
y->$y_i$
label->$label_i$

2017-01-18 09:14 UTC, dayhaha commented on recognize_digits/README.md
> +上面公式为softmax输出层的交叉熵代价损失函数，CE为cross entropy的简称，y是预测每一类的概率，label是标签。
这个的话， 后面不是有一个\sum_i么，CE的参数是两个向量。

2017-01-18 09:15 UTC, dayhaha commented on recognize_digits/README.md
> +上面公式为softmax输出层的交叉熵代价损失函数，CE为cross entropy的简称，y是预测每一类的概率，label是标签。
只是后面的文字改一下？   $y_i$是预测每一类的概率，$label_i$是标签。 公式里面的不用吧？

2017-01-18 10:06 UTC, Zrachel reviewed
全文的“线性映射”全改成“全连接层”，不要有“softmax层”的概念，变成”以softmax为激活函数的全连接层“

2017-01-18 10:06 UTC, Zrachel commented on recognize_digits/README.md
> +在该网络层中，我们有输入X($x_i(i=0,1,2,...,n-1)$)，输出标签Y($y_i(i=0,1,2,..9)$)，为了表示方便，以下我们都直接用向量计算来表示。经过第一层网络，我们可以得到：
X, Y上下文统一，要么都用latex，要么都不用。。

2017-01-18 10:06 UTC, Zrachel commented on recognize_digits/README.md
> +神经网络一般会定义一个损失函数（也称目标函数），训练的过程是通过改变网络参数来最小化这个损失函数，此过程可以采用`backpropagation`算法。在分类问题中，我们一般采用交叉熵代价损失函数（cross entropy），其形式如下：
神经网络一般会定义一个损失函数（也称目标函数），训练的过程是通过改变网络参数来最小化这个损失函数，此过程可以采用`backpropagation`算法。

刚看这句第一章有了。。。。还是删了吧

2017-01-18 10:06 UTC, Zrachel commented on recognize_digits/README.md
> +图4. 卷积层图片<br/>
还是用原图吧。。。这图不能动，就和原图没区别了。原图已经重绘过了。描述还是按原图的走。

2017-01-18 12:20 UTC, luotao1 reviewed
除模型概览外，其他部分已review完

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +</p>
把第4行和第6行合并，中间不要空格，图1放到第6行后面吧。

背景这部分看的太纠结了，辛苦修改！

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +有很多算法在MNIST上进行实验。1998年，LeCun分别用单层线性分类器、多层感知器（Multilayer Perceptron, MLP）和多层卷积神经网络LeNet进行实验，使得测试集上的误差不断下降（从12%下降到0.7%）。此后，科学家们又基于K近邻（K-Nearest Neighbors）算法、支持向量机（SVM）、神经网络和Boosting方法等做了大量实验，并采用多种预处理方法
17行参考文献不要用2-13，显得太笼统了，能否在行内标的更具体一点呢。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +## 参考文献
参考文献中，1,14,17,18,19,20都是网站，请不要在参考文献中列出。直接在文中对应位置加网站链接即可。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +实际上，$tanh$ 函数只是规模变化的 $sigmoid$ 函数，将 $sigmoid$函数值放大2倍之后再向下平移1个单位：$ tanh(x) = 2sigmoid(2x) - 1 $
124行缩进

- tanh激活函数： $ f(x) = tanh(x) = \frac{e^x-e^{-x}}{e^x+e^{-x}} $
  
   实际上，$tanh$ 函数是将 $sigmoid$函数值放大2倍之后再向下平移1个单位：$ tanh(x) = 2sigmoid(2x) - 1 $

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +更详细的介绍请参考\[[19](#参考文献)\]
更详细的介绍请参考[维基百科激活函数](https://en.wikipedia.org/wiki/Activation_function)。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +        magic, n, rows, cols = struct.upack(">IIII", f.read(16))        # 读取开头的四个参数，magic代表数据的格式，n代表数据的总量，rows和cols分别代表行数和列数
166行的注释可以分两行写，就是markdown显示的时候，代码部分下面不要有拖动条。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +在模型配置中，定义通过 `define_py_data_sources2` 函数从 `dataprovider` 中读入数据，如果该配置用于预测，则不需要数据定义部分。
。如果XXX

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +然后指定训练相关的参数。
1. 去掉“然后”
2. 203-205行的括号改成中文括号
3. 203行，与网络的收敛速度有关系
4. 采用动量优化器`MomentumOptimizer`，去掉括号

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +
#### 整体结构 （加小标题）

首先通过`data_layer`调用来获取数据，然后调用分类器（这里我们提供了三个不同的分类器）得到分类结果。训练时，对该结果计算其损失函数，分类问题常常选择交叉熵损失函数；而预测时直接输出该结果即可。 @Zrachel 这样写可以么

```
data_size = 1 * 28 * 28
label_size = 10
img = data_layer(name='pixel', size=data_size)

predict = softmax_regression(img) # Softmax回归
#predict = multilayer_perceptron(img) #多层感知器
#predict = convolutional_neural_network(img) #LeNet5卷积神经网络
 
if not is_predict:
    lbl = data_layer(name="label", size=label_size)
    inputs(img, lbl)
    outputs(classification_cost(input=predict, label=lbl))
else:
    outputs(predict)
```
（这部分代码没贴全）

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +定义好 `dataprovider` 之后，就可以通过 `data_layer` 调用来获取数据 `img`，然后通过一层简单的softmax全连接层，得到预测的结果，然后指定训练的损失函数为分类损失( `classification_cost` )，一般分类问题的损失函数为交叉熵损失函数( `cross_entropy` )。通过控制变量 `is_predict` ，该配置脚本也可以在预测时候
只通过一层简单的softmax全连接层，就可以得到分类的结果。
```
def softmax_regression(img):
    predict = fc_layer(input=img, size=10, act=SoftmaxActivation())
    return predict
```

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +    return predict
代码里的注释全改成中文

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +    return predict
代码里的注释改中文

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +以下是一个简单的带有两个隐藏层的多层感知器，也就是全连接网络，两个隐藏层的激活函数均采用 $ReLU$ 函数，最后的输出层用softmax激活函数。
下面代码实现了一个含有两个隐藏层（即全连接层）的多层感知器。其中两个隐藏层的激活函数均采用ReLu，输出层的激活函数用Softmax。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +以下为LeNet-5的网络结构\[[20](#参考文献)\]
249行太简单了，请简单再写几句。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +1.通过配置训练脚本 `train.sh` 来执行训练过程
281行后面加冒号。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +log=softmax_train.log                   # mlp: mlp_train.log            cnn: cnn_train.log
285，286的注释可以去掉

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +- save_dir:  模型存储的位置。
1. 302-310参数意义可以放到代码注释中
2. 304行，每训练，去掉“在”

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +模型训练的日志类似如下：
311行和313行重复，去掉313行。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +3.用脚本 `evaluate.py ` 可以选出最好的Pass训练出来的模型：
可以选出最佳训练的模型：

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +从上面过程中可以看到，softmax回归模型分类效果最好的时候是pass-00013，分类准确率为90.01%，而最终的pass-00099的准确率为89.3%。从图中也可以看出，准确率最好的时候并以不定是最后一个pass的模型（这是因为迭代的中间Pass可能已经收敛达到局部最优值，后面的训练可能是在该局部最优值震荡或者达到另外的低于中间Pass局部最优值的其他局部最优。）
从评估结果可以看到，XXX。从图7中也可以看出，最好的准确率不一定出现在最后一个pass。原因是中间的Pass可能就已经收敛获得局部最优值，后面的Pass只是在该值附近震荡，或者获得更低的局部最优值。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +从训练日志中我们可以看出，最终训练的准确率为94.95%，相比于softmax回归模型有了显著的提升（这是因为softmax回归模型较为简单，无法拟合更为复杂的数据，而加入了隐藏层之后的多层感知器则具有更强的拟合能力）。
从评估结果可以看到，最终训练的准确率为94.95%，相比于softmax回归模型有了显著的提升。原因是softmax回归模型较为简单，无法拟合更为复杂的数据，而加入了隐藏层之后的多层感知器则具有更强的拟合能力。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +从评估模型的结果可以看到，卷积神经网络的最好分类准确率达到惊人的99.20%。由此可以看到，对于图像问题而言，卷积神经网络能够比一般的全连接网络达到更好的识别效果，而这与卷积层具有局部连接和共享权重的特性是分不开的。同时，从图9中可以看到，卷积神经网络在很早的时候就能达到很好的效果，说明其收敛速度非常快。
从评估结果可以看到，XXX。说明对于图像问题而言，XXX。

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +```
代码放在392行前面

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +根据提示，输入需要预测的图片序号，则分类器能够给出各个数字的生成概率、预测的结果（取最大生成概率对应的数字）和实际的标签。
400行去掉“则”

2017-01-18 12:20 UTC, luotao1 commented on recognize_digits/README.md
> +本章的softmax回归、多层感知器和卷积神经网络是最基础的深度学习模型，后续章节中复杂的神经网络都是从它们衍生出来的，因此这几个模型对之后的学习大有裨益。同时，我们也观察到从最简单的softmax回归到稍复杂的卷积神经网络的时候，MNIST数据集上的识别准确率有了大幅度的提升，原因是卷积层局部连接和共享权重的特性。在之后学习新模型的时候，希望大家也要深入到新模型相比原模型带来效果提升的关键之处
1. 从最简单的softmax回归变换到稍复杂的卷积神经网络时，XXX，原因是卷积层具有XXX。
2. 本章都换成本教程
3. 最后加一个“了”，预测任务了。

2017-01-19 06:30 UTC, luotao1 reviewed
模型概览部分：
1. softmax公式的loss公式 @Zrachel 帮忙看下。
2. 卷积层这段描述不用修改， @qingqing01 在帮忙修改
3. 卷积的两个特征，也请 @qingqing01 和 @Zrachel 提点意见

其余部分都根据comment进行修改吧。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +池化包括最大池化、平均池化等。其中最大池化是用不重叠的矩形框将输入层分成不同的区域，对于每个矩形框的数取最大值作为输出层，如图5所示。
1. 通常在卷积层的后面都会加上一个池化层。
2. 去掉101行。这两句都很短，中间不用空一行。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +LeNet-5网络的典型结构是：输入的二维图像，首先经过两次卷积层到池化层，再经过全连接层，最后使用softmax分类作为输出层。\[[20](#参考文献)\]
109-111行：

LeNet-5是一个最简单的卷积神经网络。图6显示了其结构：输入的二维图像，先经过两次卷积层到池化层，再经过全连接层，最后使用softmax分类作为输出层\[[20](#参考文献)\]。卷积的如下三个特性，决定了LeNet-5能比同样使用全连接层的多层感知器更好地识别图像\[[17](#参考文献)\]：

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +图6. 卷积神经网络结构<br/>
图6. LeNet-5卷积神经网络结构<br/>

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +- 神经元的三维特性： 卷积层的神经元在宽度、高度和深度上进行了组织排列。每一层的神经元仅仅与前一层的一块小区域连接，这块小区域被称为感受野。
感受野（加英文）

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +更详细的关于卷积神经网络的具体知识可以参考斯坦福大学公开课 [cs231n]( http://cs231n.github.io/convolutional-networks/ )
更详细的关于卷积神经网络的具体知识可以参考[斯坦福大学公开课]( http://cs231n.github.io/convolutional-networks/ )和[图像分类](https://github.com/PaddlePaddle/book/blob/develop/image_classification/README.md)教程。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +# 手写字符识别教程
标题是 “识别数字”，请和首页目录对应

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +- 局部连接：CNN通过在相邻层的神经元之间实施局部连接模式来利用空间局部相关性。这样的结构保证了学习后的过滤器能够对于局部的输入特征有最强的响应。堆叠许多这样的层导致非线性“过滤器”变得越来越“全局”。这允许网络首先创建输入的小部分的良好表示，然后从它们组合较大区域的表示。
114行的局部连接那里，解释时也用局部连接模式，解释的不是很清楚。

114行和115行， @qingqing01 能提点意见么。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +图3为多层感知器的网络结构图，图中权重用黑线表示，偏置用红线表示，+1代表偏置参数的系数为1
图3为多层感知器的网络结构图，图中权重用黑线表示、偏置用红线表示、+1代表偏置参数的系数为1。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +在该网络层中，我们有输入X($x_i(i=0,1,2,...,n-1)$)，输出标签Y($y_i(i=0,1,2,..9)$)，为了表示方便，以下我们都直接用向量计算来表示。经过第一层网络，我们可以得到：
Softmax回归模型采用了最简单的两层神经网络，即只有输入层和输出层，因此其拟合能力有限。为了达到更好的识别效果，我们考虑在输入层和输出层中间加上若干个隐藏层。\[[15-16](#参考文献)\]

1.  经过第一个隐藏层，可以得到 $$ H_1 = \phi(W_1X + b_1) $$，其中$\phi$代表激活函数，常见的有$sigmoid$、$tanh$或$ReLU$等函数。
2.  经过第二个隐藏层，可以得到 $$ H_2 = \phi(W_2H_1 + b_2) $$。
3.  最后，再经过输出层，得到的$Y=softmax(W_3H_2 + b_3)$，即为最后的分类结果向量。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +上面公式为softmax输出层的交叉熵代价损失函数，CE为cross entropy的简称，$y_i$是预测每一类的概率，$label_i$是标签。
53行可以去掉，这部分在前面全部讲过了。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +神经网络一般会定义一个损失函数（也称目标函数），训练的过程是通过改变网络参数来最小化这个损失函数，此过程可以采用`backpropagation`算法。在分类问题中，我们一般采用交叉熵代价损失函数（cross entropy），其形式如下：
在分类问题中，我们一般采用交叉熵代价损失函数（cross entropy），公式如下：

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +$$  CE(label, y) = -\sum_i label_ilog(y_i) $$
51行里面的CE就用cross_entropy(label,y)，这样也不用说CE是简称了。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +图2为softmax回归的网络图，图中权重用黑线表示，偏置用红线表示，+1代表偏置参数的系数为1。
43行和图2放在本小节的末尾，因为下面一个小节也是把图放在最后的。

43行的标点小修下：
图2为softmax回归的网络图，图中权重用黑线表示、偏置用红线表示、+1代表偏置参数的系数为1。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +神经网络中通常使用softmax函数计算多分类问题中每一类的概率。为了熟悉softmax函数，我们定义最简单的多分类网络：将输入层经过一个线性映射得到的特征，直接通过softmax 函数进行多分类。\[[14](#参考文献)\]
最简单的Softmax回归模型是先将XXX（这里不要用线性映射，按照 @Zrachel 提过的意见改），然后直接通过softmax函数进行多分类\[[14](#参考文献)\]。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +其中 $ softmax(x_i) = \frac{e^{x_i}}{\sum_j e^{x_j}} $
公式 @Zrachel 看下：这里用x_i, y_i，下一个小节中的公式都没有下标，直接是X和Y。所以要统一。

公式变了之后，35行和41行也要对应改变。

2017-01-19 06:30 UTC, luotao1 commented on recognize_digits/README.md
> +## 模型概览
基于MNIST数据训练一个分类器，在介绍本教程使用的三个基本图像分类网络前，我们先给出一些定义：
- $X$是输入：MNIST图片是$28\times28$ 的二维图像，为了进行计算，我们将其转化为$784$维向量，即$X=\left ( x_0, x_1, \dots, x_783 \right )$。
- $Y$是输出：MNIST图片的输出是10类数字（0-9），因此$Y=\left ( y_0, y_1, \dots, y_9 \right )$，每一维$y_i$代表图片分类为第$i$类数字的概率。
- $L$是图片的真实标签：$L=\left ( l_0, l_1, \dots, l_9 \right )$也是10维，但只有一维为1，其他都为0。

2017-01-19 07:12 UTC, dayhaha commented on recognize_digits/README.md
> +池化包括最大池化、平均池化等。其中最大池化是用不重叠的矩形框将输入层分成不同的区域，对于每个矩形框的数取最大值作为输出层，如图5所示。
这里为什么要加个都呢？ 好像有的卷积层后面没有加池化层？

2017-01-19 07:19 UTC, dayhaha commented on recognize_digits/README.md
> +池化包括最大池化、平均池化等。其中最大池化是用不重叠的矩形框将输入层分成不同的区域，对于每个矩形框的数取最大值作为输出层，如图5所示。
哦，意思是前面一句话不要？。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +有很多算法在MNIST上进行实验。1998年，LeCun分别用单层线性分类器、多层感知器（Multilayer Perceptron, MLP）和多层卷积神经网络LeNet进行实验，使得测试集上的误差不断下降（从12%下降到0.7%）。\[[1](#参考文献)\]此后，科学家们又基于K近邻（K-Nearest Neighbors）算法\[[2](#参考文献)\]、支持向量机（SVM）\[[3](
参考文献[1]的位置对么，应该放在句号前面。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +- $Y$是输出：MNIST图片的输出是10类数字（0-9），因此$Y=\left ( y_0, y_1, \dots, y_9 \right )$，每一维$y_i$代表图片分类为第$i$类数字的概率。
$Y$是输出：分类器的输出是10类数字（0-9），即$Y=\left ( y_0, y_1, \dots, y_9 \right )$，每一维$y_i$代表图片分类为第$i$类数字的概率。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +下面我们一一介绍本教程中使用的三个基本图像分类网络Softmax回归、多层感知器、卷积神经网络。
27行去掉，因为22行已经讲了要介绍三个图像分类网络。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
>  Yann LeCun早先在手写字符识别上做了很多研究，并在研究过程中提出了卷积神经网络（Convolutional Neural Network），大幅度地提高了手写字符的识别能力，也因此成为了深度学习领域的奠基人之一。如今的深度学习领域，卷积神经网络占据了至关重要的地位，从最早Yann LeCun提出的简单LeNet，到如今ImageNet大赛上的优胜模型VGGNet、GoogLeNet、Re
请参见[图像分类]教程，加上教程两字。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +最简单的Softmax回归模型是先将输入层经过一个全连接层得到的特征，然后直接通过softmax 函数进行多分类。\[[9](#参考文献)\]
参考文献的位置要放在句号前面。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +Softmax回归模型采用了最简单的两层神经网络，即只有输入层和输出层，因此其拟合能力有限。为了达到更好的识别效果，我们考虑在输入层和输出层中间加上若干个隐藏层。\[[10](#参考文献)\]
参考文献的位置要放在句号前面。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +1.  经过第一个隐藏层，可以得到 $ H_1 = \phi(W_1X + b_1) $，其中$\phi$代表激活函数，常见的有$sigmoid$、$tanh$或$ReLU$等函数。
$sigmoid$、$tanh$或$ReLU$-》sigmoid、tanh或ReLU。这里不用公式

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +  实际上，$tanh$ 函数只是规模变化的 $sigmoid$ 函数，将 $sigmoid$函数值放大2倍之后再向下平移1个单位：$ tanh(x) = 2sigmoid(2x) - 1 $
tanh函数只是规模变化的sigmoid函数，将sigmoid函数

去掉公式格式

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +更详细的介绍请参考[维基百科激活函数](https://en.wikipedia.org/wiki/Activation_function)
108行加句号。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
> +    # 第一个 卷积-池化 层
卷积-池化 前后空格去掉。265行也是。

2017-01-19 08:47 UTC, luotao1 commented on recognize_digits/README.md
>  ## 训练命令及日志
```
## 训练模型
### 训练命令及日志
### softmax回归的训练结果
...
```
这部分的标题`#`不对。

2017-01-19 09:01 UTC, luotao1 approved these changes

2017-01-19 09:08 UTC, schinger approved these changes

2017-01-19 09:09 UTC, Zrachel approved these changes

2017-01-19 09:10 UTC, merged