PR of chapter fit_a_line.
PaddlePaddle/book pull request #28
Opened 2016-12-26 04:33 UTC by zhouxiao-coder

Just a placeholder for now. Contents will be added later.

2016-12-27 09:28 UTC, schinger commented on fit_a_line/README.md
> +## 参考文献
第一章很重要

2016-12-27 09:34 UTC, luotao1 commented on fit_a_line/README.md
> +## 参考文献
第6行和第7行应该是三个###

2017-01-03 03:20 UTC, schinger commented on fit_a_line/README.md
> +作为这部教程的读者，您或许已经从这份文档里学会了如何使用PaddlePaddle训练一个单变量的线性回归模型来拟合一个人造的数据集。这里，让我们更进一步，把线性回归模型应用到一个真实世界的问题上-房价预测。
这章是全书的第一章，之前没有单变量的线性回归的内容

2017-01-03 05:21 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +作为这部教程的读者，您或许已经从这份文档里学会了如何使用PaddlePaddle训练一个单变量的线性回归模型来拟合一个人造的数据集。这里，让我们更进一步，把线性回归模型应用到一个真实世界的问题上-房价预测。
抱歉，这个文档还在改，没有完成。之前commit是为了check下公式的格式。我大概今晚会改一个比较完整的版本再ci，之前先不用review。

2017-01-03 05:24 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +## 参考文献
抱歉，这个文档还在改，没有完成。之前commit是为了check下公式的格式。我大概今晚会改一个比较完整的版本再ci，之前先不用review。

2017-01-04 07:33 UTC, luotao1 requested changes
1. 缺少.gitignore文件，datas目录改名为data
2. travis中的yapf格式化没过，请本地使用yapf 0.13.2版本来格式化
3. 预测可以不用swig么？直接用paddle train行么，因为swig脚本看起来会更复杂点 @Zrachel 你觉得呢

2017-01-04 07:33 UTC, luotao1 commented on README.md
>  # 深度学习入门
README.md应该是merge了老版本的，这里请更新，且不用修改。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +## 参考文献
缺失总结和参考文献。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +让我们从经典的线性回归模型开始这份教程。在这一章里，你将使用真实的数据集建立起一个房价预测模型，并且若干重要的概念。
1. ”并且若干重要的概念“不通
2. 线性回归模型（贴上英文，和wiki链接），最好有参考文献。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +## 模型配置说明
### 数据定义
### 算法配置
### 网络结构

缺少小标题，请依次补充

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +例如，在我们将要建模的房价预测问题里，$x_{ij}$是描述房子$i$的各种属性（比如房间的个数），而 $y_i$是房屋的价格。
比如房价的个数，后面再列一点属性（模型概览里面写了有13个属性），现在只列了一个属性，有点空。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +初看起来，这个假设实在过于简单了，变量间的真实关系很难是线性的。但由于其形式简单、易于建模分析，线性回归模型却在实际问题中得到了大量的应用，多数的统计学习、机器学习书籍也会选择对线性模型独立成章重点讲解。
然而，由于线性回归模型具有形式简单、易于建模分析的有点，因此在实际问题中得到了大量的应用，同时多数的统计学习、机器学习书籍也会对它独立成章重点讲解。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +	图1. 预测值 V.S. 真实值
1. 图太大了，请缩小一点。
2. 图的横轴和纵轴改成，预测值和真实值，不要用predicted和True。
3. 图的标题改为：房价预测模型的效果图。
4. 所以模型预测得越准确XXX

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +在波士顿房价数据集中，和房屋相关的值共有14个：前13个用来描述房屋相关的各种信息，即模型中的 $x_i$；最后一个值为我们要预测的房屋价格的中值，即模型中的 $y_i$。因此，我们的模型就可以表示成：
价格的中位数

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +$$Y\string^ = \omega_1X_{1} + \omega_2X_{2} + ... + \omega_{13}X_{13} + b$$
23行的公式和25行的$Y\string^$显示有问题，请调整格式。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +$Y\string^$ 表示模型的预测，用来和真实值$Y$区分。模型要学习的参数即：$\omega_1, \dot, \omega_{13}, b$。
$\omega_1, \dot, \omega_{13}, b$，显示有问题，请调整格式。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +即对于一个大小为n的测试集，$MSE$是$n$个数据预测结果误差平方的均值。
大小为$n$

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +有了模型表示之后，我们还需要能够度量给定一组参数后，模型表现的好坏。也就是说，我们需要一个损失函数来指导参数的调整。对于线性回归模型来讲，最常见的损失函数就是均方误差（Mean Squared Error， MSE）了，它的形式是：
有了模型表示之后，我们还需要能够度量模型表现好坏。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +cd datas && python prepare_data.py
cd data

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +这段代码将从[UCI Housing Data Set](https://archive.ics.uci.edu/ml/datasets/Housing)下载数据并进行预处理（细节见下节-数据预处理），最后数据将被分为训练集和测试集。
并进行[预处理](#数据预处理)，然后将数据分为训练集和测试集。

预处理后面可以加链接，写法如下：`[预处理](#数据预处理)`

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1,L2正则项，Vector Space Model）都基于这样的假设，即所有的属性取值范围都差不多是以0为均值，范围接近于1的。
1. L1、L2正则项，中间的英文逗号改成中文顿号
2. Vector Space Model有中文么

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +最后，我们将数据按照9:1的比例分割成训练集和测试集，并将保存后的文件路径分别写入 `train.list` 和 `test.list`两个文件中，供PaddlePaddle读取。
为什么按照9:1的比例呢，能稍微说明下么

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +```
70行开始的这段预处理代码不用贴， @Zrachel 你觉得呢

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +#dataprovider.py
98行可以去掉

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +#trainer_config.py
116行去掉

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +# 1. read data. Suppose you saved above python code as dataprovider.py
121行可以去掉，因为后面的注释是中文，这里是英文，不统一

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +#$$Y\string^ = \omega_1X_{1} + \omega_2X_{2} + ... + \omega_{13}X_{13} + b$$
139行可以去掉，显示不出latex公式

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +在对应代码的根目录下执行PaddlePaddle的命令行训练程序。这里指定模型配置文件为`trainer_config.py`，训练30轮，结果保存在`output`路径下。
可以直接执行训练脚本`train.sh`，然后介绍训练脚本的内容。请重新组织下156行。

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/README.md
> +现在来看下如何使用已经训练好的模型进行预测。这里我们指定一个pass保存的模型，并对测试集中的每一条数据进行预测。
预测脚本和下面画图的脚本都不用贴内容，只要告诉用户怎么用这些脚本即可。 @Zrachel 你觉得呢

2017-01-04 07:33 UTC, luotao1 commented on fit_a_line/trainer_config.py
> +
多余空行：29，32，42行都可以去掉

2017-01-04 07:37 UTC, Zrachel commented on fit_a_line/README.md
> +```
同意，不用贴了，直接说执行python x.py进行预处理吧

2017-01-04 07:52 UTC, Zrachel commented on fit_a_line/README.md
> +现在来看下如何使用已经训练好的模型进行预测。这里我们指定一个pass保存的模型，并对测试集中的每一条数据进行预测。
同意

2017-01-05 19:52 UTC, wangkuiyi commented
@zhouxiao-coder 我看到这个PR的TravisCI test没有过。从[log](https://travis-ci.org/PaddlePaddle/book/builds/188735890)看，是因为有些Python代码的格式不符合标准，没有通过yapf的检查。可以在本机运行一下 pre-commit -a run 命令，来自动修正代码的排版格式，随后 git push 一下，应该就解决了。

2017-01-06 07:09 UTC, Zrachel requested changes
全文修改建议

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +例如，在我们将要建模的房价预测问题里，$x_{ij}$是描述房子$i$的各种属性（比如房间的个数），而 $y_i$是房屋的价格。
这句话提前，插入到背景介绍下的第一句中

其中$x{i1}, ... x_{id}$是$d$个属性上的取值，如描述房子$i$的各种属性（比如房间的个数、周围学校和医院的个数、房屋所在楼层等）

y也这么写

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +	图1. 预测值 V.S. 真实值
横纵轴需要标明单位，比如$million，还有前面说明图上表示每平米还是房屋出售值这么多钱

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +$Y\string^$ 表示模型的预测，用来和真实值$Y$区分。模型要学习的参数即：$\omega_1, \dot, \omega_{13}, b$。
表示模型的预测
->
 表示模型的预测结果

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +有了模型表示之后，我们还需要能够度量给定一组参数后，模型表现的好坏。也就是说，我们需要一个损失函数来指导参数的调整。对于线性回归模型来讲，最常见的损失函数就是均方误差（Mean Squared Error， MSE）了，它的形式是：
有了模型表示之后，我们还需要能够度量给定一组参数后，模型表现的好坏。
->
建立模型后，我们需要给模型一个优化目标，使得学到的参数能够让预测值$Y\string^$尽可能地接近真实值$Y$。这里我们引入损失函数[reference]这个概念。 损失函数（loss function，或cost function）将一组含参数的表达式……（怎么说请参考具体文献）

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1,L2正则项，Vector Space Model）都基于这样的假设，即所有的属性取值范围都差不多是以0为均值，范围接近于1的。
2. 向量空间模型

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +观察一下数据，我们的第一个发现是：所有的13维属性中，有12维的连续值和1维的离散值（CHAS）。离散值虽然也常使用类似0、1、2这样的数字表示，但是其含义与连续值是不同的，因为这里的差值没有实际意义。例如，我们用0、1、2来分别表示红色、绿色和蓝色的话，我们并不能因此说“蓝色和红色”比“绿色和红色”的距离更远。所以通常对一个有$d$ 个可能取值的离散属性，我们会将它们转为 $d$ 个取值为0或
上面加：
`#### 连续值与离散值`

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +另外一个稍加观察即可发现的事实是，各维属性的取值范围差别很大。例如，属性B的取值范围是[0.32, 396.90]，而属性NOX的取值范围是[0.3850, 0.8170]。这里就要用到一个常见的操作-归一化（normalization）了。归一化的目标是把各位属性的取值范围放缩到差不多的区间，例如[-0.5,0.5]。下面的代码展示了一种最简便的操作方法：减掉均值，然后除以原取值范围。
上面加：
`#### 特征归一化`

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1,L2正则项，Vector Space Model）都基于这样的假设，即所有的属性取值范围都差不多是以0为均值，范围接近于1的。
这句话的出处，加引用

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +最后，我们将数据按照9:1的比例分割成训练集和测试集，并将保存后的文件路径分别写入 `train.list` 和 `test.list`两个文件中，供PaddlePaddle读取。
上面加：
`#### 整理训练集与测试集`

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +        f.write('datas/' + train_data + '\n')
datas全部改成data，source code中同

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +    maximums, minimums, avgs = data.max(axis=0), data.min(axis=0), data.sum(axis=0)/data.shape[0]
上一行加注释 # 归一化

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +最后使用`fc_layer`和`LinearActivation`来表示线性回归的模型本身。
表示-实现

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +    args={})
删掉args={}这一行

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +    #计算在测试集上的MSE，大概在8.92左右
“大概在8.92左右”  写在 代码外面，说下执行了多少个pass，得到8.92结果这种。

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +    # draw a scatter plot
一个函数要写在一个代码段里，这样写到时候执行会出语法错误。

另外，这段其实没必要显式给出，放到另一个文件import进来或者再单独调用吧，不要显示了。

2017-01-06 07:09 UTC, Zrachel commented on fit_a_line/README.md
> +    #计算在测试集上的MSE，大概在8.92左右
结果希望再加一个图，13个feature的scale画出来，xlabel 标明13个feature，y为这13个feature的value

2017-01-08 16:54 UTC, zhouxiao-coder commented on README.md
>  # 深度学习入门
done

2017-01-08 16:54 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +让我们从经典的线性回归模型开始这份教程。在这一章里，你将使用真实的数据集建立起一个房价预测模型，并且若干重要的概念。
done

2017-01-08 16:55 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +例如，在我们将要建模的房价预测问题里，$x_{ij}$是描述房子$i$的各种属性（比如房间的个数），而 $y_i$是房屋的价格。
done

2017-01-08 16:55 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +初看起来，这个假设实在过于简单了，变量间的真实关系很难是线性的。但由于其形式简单、易于建模分析，线性回归模型却在实际问题中得到了大量的应用，多数的统计学习、机器学习书籍也会选择对线性模型独立成章重点讲解。
done

2017-01-08 17:07 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +	图1. 预测值 V.S. 真实值
1. 之前的图片和新增图片都调成了宽480 pixel的
2. 关于图片的中文问题，我暂时没有改。原因是因为图是直接放在代码里用matplotlib画的，如果要正确显示中文的话需要有中文字体文件。我在paddle的docker image上找了下（`fc-list :lang=zh`） 没看到支持中文的字体。我参考了下 @Zrachel 的word2vec 的图片以及我们的撰写标准，决定不改图片，而是在正文中增加了描述。
3. 关于@Zrachel的问题，修改了这里的表述和图片坐标label。这里数据集中的 "Y" 是符合 “X” 描述的一类房屋价格的中位数，而不是单个房屋，希望这里描述清楚了。

2017-01-08 17:07 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +在波士顿房价数据集中，和房屋相关的值共有14个：前13个用来描述房屋相关的各种信息，即模型中的 $x_i$；最后一个值为我们要预测的房屋价格的中值，即模型中的 $y_i$。因此，我们的模型就可以表示成：
done

2017-01-08 17:08 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +$$Y\string^ = \omega_1X_{1} + \omega_2X_{2} + ... + \omega_{13}X_{13} + b$$
done

2017-01-08 17:08 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +$Y\string^$ 表示模型的预测，用来和真实值$Y$区分。模型要学习的参数即：$\omega_1, \dot, \omega_{13}, b$。
done

2017-01-08 17:08 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +有了模型表示之后，我们还需要能够度量给定一组参数后，模型表现的好坏。也就是说，我们需要一个损失函数来指导参数的调整。对于线性回归模型来讲，最常见的损失函数就是均方误差（Mean Squared Error， MSE）了，它的形式是：
这部分按照睿卿另外一个的建议重写了一下。

2017-01-08 17:08 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +即对于一个大小为n的测试集，$MSE$是$n$个数据预测结果误差平方的均值。
done

2017-01-08 17:08 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +cd datas && python prepare_data.py
所有datas都改为data了。done。

2017-01-08 17:09 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +这段代码将从[UCI Housing Data Set](https://archive.ics.uci.edu/ml/datasets/Housing)下载数据并进行预处理（细节见下节-数据预处理），最后数据将被分为训练集和测试集。
done

2017-01-08 17:09 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1,L2正则项，Vector Space Model）都基于这样的假设，即所有的属性取值范围都差不多是以0为均值，范围接近于1的。
done

2017-01-08 17:13 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +最后，我们将数据按照9:1的比例分割成训练集和测试集，并将保存后的文件路径分别写入 `train.list` 和 `test.list`两个文件中，供PaddlePaddle读取。
数据集分割的问题我展开写了下，代码页进行了响应的修改，改动包括：

- 两个数据集的用途，点出 训练误差和测试误差
- 分割数据改为default 8:2，但接受其他比例，可以参数传入
- 扩展介绍了验证集的用途。

原来用9:1单纯是为了与sklearn的一篇教程保持一致。 （http://scikit-learn.org/stable/auto_examples/ensemble/plot_gradient_boosting_regression.html）。一般rule of thumb是8:2，工业数据集更高的比例也很常见。

2017-01-08 17:13 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +#dataprovider.py
done

2017-01-08 17:17 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +## 模型配置说明
done

2017-01-08 17:17 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +#trainer_config.py
done

2017-01-08 17:17 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +# 1. read data. Suppose you saved above python code as dataprovider.py
done

2017-01-08 17:17 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +#$$Y\string^ = \omega_1X_{1} + \omega_2X_{2} + ... + \omega_{13}X_{13} + b$$
done

2017-01-08 17:17 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +在对应代码的根目录下执行PaddlePaddle的命令行训练程序。这里指定模型配置文件为`trainer_config.py`，训练30轮，结果保存在`output`路径下。
done

2017-01-08 17:17 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +现在来看下如何使用已经训练好的模型进行预测。这里我们指定一个pass保存的模型，并对测试集中的每一条数据进行预测。
done

2017-01-08 17:18 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +## 参考文献
done

2017-01-08 17:21 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +例如，在我们将要建模的房价预测问题里，$x_{ij}$是描述房子$i$的各种属性（比如房间的个数），而 $y_i$是房屋的价格。
- x 和 y 的介绍我改了，增加了举例。
- 位置调整是说要把这里的 “例如，xxx” 调整到前面 "$y_i$是待预测的目标" 后面么？我觉得这样不太好。前面是用数学语言比较严格定义线性回归模型的过程，不易割裂开。如果读者不习惯看公式的话，下面的举例离得也很近，应该不会造成困扰。周志华老师和李航老师的书里都是类似的处理方法。

2017-01-08 17:22 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +$Y\string^$ 表示模型的预测，用来和真实值$Y$区分。模型要学习的参数即：$\omega_1, \dot, \omega_{13}, b$。
done

2017-01-08 17:22 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +有了模型表示之后，我们还需要能够度量给定一组参数后，模型表现的好坏。也就是说，我们需要一个损失函数来指导参数的调整。对于线性回归模型来讲，最常见的损失函数就是均方误差（Mean Squared Error， MSE）了，它的形式是：
done

2017-01-08 17:22 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +观察一下数据，我们的第一个发现是：所有的13维属性中，有12维的连续值和1维的离散值（CHAS）。离散值虽然也常使用类似0、1、2这样的数字表示，但是其含义与连续值是不同的，因为这里的差值没有实际意义。例如，我们用0、1、2来分别表示红色、绿色和蓝色的话，我们并不能因此说“蓝色和红色”比“绿色和红色”的距离更远。所以通常对一个有$d$ 个可能取值的离散属性，我们会将它们转为 $d$ 个取值为0或
done

2017-01-08 17:22 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +另外一个稍加观察即可发现的事实是，各维属性的取值范围差别很大。例如，属性B的取值范围是[0.32, 396.90]，而属性NOX的取值范围是[0.3850, 0.8170]。这里就要用到一个常见的操作-归一化（normalization）了。归一化的目标是把各位属性的取值范围放缩到差不多的区间，例如[-0.5,0.5]。下面的代码展示了一种最简便的操作方法：减掉均值，然后除以原取值范围。
done

2017-01-08 17:24 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1,L2正则项，Vector Space Model）都基于这样的假设，即所有的属性取值范围都差不多是以0为均值，范围接近于1的。
- 这一段介绍做归一化的理由，是我自己总结的，没有统一出处。这里如果觉得有事实性错误的话，我们可以讨论下~
- 第三点我引了下sklearn对应的normalization部分介绍。

2017-01-08 17:25 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +最后，我们将数据按照9:1的比例分割成训练集和测试集，并将保存后的文件路径分别写入 `train.list` 和 `test.list`两个文件中，供PaddlePaddle读取。
done

2017-01-08 17:25 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +        f.write('datas/' + train_data + '\n')
done

2017-01-08 17:25 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +    maximums, minimums, avgs = data.max(axis=0), data.min(axis=0), data.sum(axis=0)/data.shape[0]
这部分代码按照你和@luotao1 的意见，已经都删到了。

2017-01-08 17:25 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +    args={})
done

2017-01-08 17:25 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +最后使用`fc_layer`和`LinearActivation`来表示线性回归的模型本身。
done

2017-01-08 17:26 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +    #计算在测试集上的MSE，大概在8.92左右
删掉了，原因见上面comment

2017-01-08 17:26 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +    #计算在测试集上的MSE，大概在8.92左右
图补在了预处理一节。done。

2017-01-08 17:26 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +    # draw a scatter plot
删掉了。

2017-01-11 09:44 UTC, luotao1 reviewed
还有一些小问题需要修改。

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +让我们从经典的线性回归（Linear Regression [1]）模型开始这份教程。在这一章里，你将使用真实的数据集建立起一个房价预测模型，并且了解到机器学习中的若干重要概念。
`\[[1](#参考文献)\]`，这样可以跳转。全文参考文献引用处都要修改。

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +给定一个大小为$n$的数据集  ${\\{y_{i}, x_{i1}, ..., x_{id}\\}}\_{i=1}\^{n}$，其中$x_{i1}, \ldots, x_{id}$是$d$个属性上的取值，$y_i$是待预测的目标。线性回归模型假设目标$y_i$可以被属性间的线性组合描述，即
${\\{y_{i}, x_{i1}, ..., x_{id}\\}}\_{i=1}\^{n}$ 这个公式没有正确显示，
![default](https://cloud.githubusercontent.com/assets/6836917/21841647/175aef06-d81e-11e6-9989-fd3eb376db86.PNG)

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +$$MSE=\frac{1}{n}\sum\_{i=1}\^{n}{(\hat{Y_i}-Y_i)}^2$$
31行公式显示不对
![default](https://cloud.githubusercontent.com/assets/6836917/21841848/0a6f600a-d81f-11e6-8009-cee2930a9fb3.PNG)

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +| B | 1000(Bk - 0.63)^2，其中BK为黑人占比 | 连续值 |
57行，Bk，BK，K一个大写一个小写，请统一

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +观察一下数据，我们的第一个发现是：所有的13维属性中，有12维的连续值和1维的离散值（CHAS）。离散值虽然也常使用类似0、1、2这样的数字表示，但是其含义与连续值是不同的，因为这里的差值没有实际意义。例如，我们用0、1、2来分别表示红色、绿色和蓝色的话，我们并不能因此说“蓝色和红色”比“绿色和红色”的距离更远。所以通常对一个有$d$ 个可能取值的离散属性，我们会将它们转为 $d$ 个取值为0或
$d$前后的空格可以去掉

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +另外一个稍加观察即可发现的事实是，各维属性的取值范围差别很大（如图2所示）。例如，属性B的取值范围是[0.32, 396.90]，而属性NOX的取值范围是[0.3850, 0.8170]。这里就要用到一个常见的操作-归一化（normalization）了。归一化的目标是把各位属性的取值范围放缩到差不多的区间，例如[-0.5,0.5]。下面的代码展示了一种最简便的操作方法：减掉均值，然后除以原取值
下面的代码，现在没有代码了。这句话改一下。我们的预处理脚本XXX使用一种最简便的操作方法：减掉均值，然后除以原取值范围。

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1，L2正则项，向量空间模型）都基于这样的假设，即所有的属性取值都差不多是以0为均值且取值范围相近的 [7]。
1. 71行中基于什么假设？是指基于70行中的假设么
2. L1、L2正则项（逗号改顿号），向量空间模型Vector Space Model（原来的英语不要去掉）

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +最后，我们将数据集分割为两份：一份用于调整模型的参数，即进行模型的训练，模型在这份数据集上的误差被称为**训练误差**；另外一份被用来测试，模型在这份数据集上的误差被称为**测试误差**。我们训练模型的目的是为了通过从训练数据中找到规律来预测未知的新数据，所以测试误差是更能反映模型表现的指标。分割数据的比例要考虑到两个因素：更多的训练数据会降低参数估计的方差，从而得到更可信的模型；而更多的测试数
1. “最后，”去掉
2. 最后一句换行，并改：执行如下命令可以分割数据集，并将训练集和测试集的地址分别写入`train.list` 和 `test.list`两个文件中，供PaddlePaddle读取。

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +在更复杂的模型训练过程中，我们还往往还会多使用一种数据集：验证集。复杂的模型中常常还有一些超参数（Hyperparameter [8]）需要调节，所以我们会尝试多种超参数的组合来分别训练多个模型，然后对比它们在验证集上的表现选择相对最好的一组超参数，最后才使用这组参数下训练的模型在测试集上评估测试误差。由于本章训练的模型比较简单，我们暂且忽略掉这个过程。
1. 我们往往还会多使用一种，多了一个“还”
2. 因为复杂的XXX

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +#dataprovider.py
一行一行地

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +#### 数据定义
###，多了一个#，下面的两个小标题也是

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +接着指定模型优化算法的细节。由于线性回归模型比较简单，我们只要设置基本的`batch_size`即可，它指定每次更新参数的时候使用多少条数据计算梯度信息。
接着，（因为前面首先后面加了逗号，这里要保持统一）

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +最后使用`fc_layer`和`LinearActivation`来表示线性回归的模型本身。
最后，

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +我们通过一个模型配置文件来定义模型相关的各种细节。
104行可以删掉，因为后面训练模型那节讲了是trainer_config.py

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +bash train.sh
./train.sh

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +在这章里，我们借助波士顿房价这一数据集介绍了线性回归模型的基本概念以及如何使用PaddlePaddle实现训练和测试的过程。很多的模型和技巧都是从简单的线性回归模型演化而来，因此弄清线性模型的原理和局限非常重要。
在这章里，我们借助波士顿房价这一数据集，介绍了线性回归模型的基本概念，以及如何使用PaddlePaddle实现训练和测试的过程。很多的模型和技巧都是从简单的线性回归模型演化而来，因此弄清楚线性模型的原理和局限非常重要。

2017-01-11 09:44 UTC, luotao1 commented on fit_a_line/README.md
> +8. https://en.wikipedia.org/wiki/Hyperparameter_optimization
5,6,7,8直接在对应的文字里面加超链接即可，不用再列出参考文献了。

2017-01-11 10:24 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +$$MSE=\frac{1}{n}\sum\_{i=1}\^{n}{(\hat{Y_i}-Y_i)}^2$$
公式的语法是不是不太一致？你这里显示的是我多写了一个转义，但我用之前大家推荐的github latex插件看，这里和上面都是正确的。

<img width="921" alt="2017-01-11 6 23 05" src="https://cloud.githubusercontent.com/assets/22702369/21844861/3f389534-d82b-11e6-9290-268e210685eb.png">

2017-01-11 10:37 UTC, luotao1 commented on fit_a_line/README.md
> +$$MSE=\frac{1}{n}\sum\_{i=1}\^{n}{(\hat{Y_i}-Y_i)}^2$$
我也是用github latex插件看，http://latex.codecogs.com/eqneditor/editor.php， 你可以用这个网站看。现在你的公式在这个网站上是显示不了的。把转义符号去掉吧

2017-01-12 03:09 UTC, Zrachel commented on fit_a_line/README.md
> +$$MSE=\frac{1}{n}\sum\_{i=1}\^{n}{(\hat{Y_i}-Y_i)}^2$$
我这里也是luotao显示的样子，改一下吧~

2017-01-12 03:09 UTC, Zrachel commented on fit_a_line/README.md
> +| CHAS | 是否临近 Charles River  | 离散值，1=邻近；0=不邻近 |
临近 -> 邻近

2017-01-12 03:09 UTC, Zrachel commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1，L2正则项，向量空间模型）都基于这样的假设，即所有的属性取值都差不多是以0为均值且取值范围相近的 [7]。
引用https://en.wikipedia.org/wiki/Normalization_(statistics) 吧

[7]是sklearn里的用法，还是不太好。描述也对应改一下吧

2017-01-12 03:10 UTC, Zrachel commented on fit_a_line/README.md
> +8. https://en.wikipedia.org/wiki/Hyperparameter_optimization
参考文献里2,3,4都没有用到？

2017-01-12 13:58 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1，L2正则项，向量空间模型）都基于这样的假设，即所有的属性取值都差不多是以0为均值且取值范围相近的 [7]。
改过了。不过没用这个wiki，这个链接对应的是统计里的概念，我用了这个 https://en.wikipedia.org/wiki/Feature_scaling

2017-01-12 13:58 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +| CHAS | 是否临近 Charles River  | 离散值，1=邻近；0=不邻近 |
done

2017-01-12 13:59 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +8. https://en.wikipedia.org/wiki/Hyperparameter_optimization
@luotao1 done
@Zrachel 2,3,4在背景介绍部分提到了，最后一句

2017-01-12 13:59 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +在这章里，我们借助波士顿房价这一数据集介绍了线性回归模型的基本概念以及如何使用PaddlePaddle实现训练和测试的过程。很多的模型和技巧都是从简单的线性回归模型演化而来，因此弄清线性模型的原理和局限非常重要。
done

2017-01-12 13:59 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +bash train.sh
done

2017-01-12 13:59 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +最后使用`fc_layer`和`LinearActivation`来表示线性回归的模型本身。
done

2017-01-12 13:59 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +接着指定模型优化算法的细节。由于线性回归模型比较简单，我们只要设置基本的`batch_size`即可，它指定每次更新参数的时候使用多少条数据计算梯度信息。
done

2017-01-12 14:00 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +#### 数据定义
done

2017-01-12 14:00 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +我们通过一个模型配置文件来定义模型相关的各种细节。
done

2017-01-12 14:00 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +在更复杂的模型训练过程中，我们还往往还会多使用一种数据集：验证集。复杂的模型中常常还有一些超参数（Hyperparameter [8]）需要调节，所以我们会尝试多种超参数的组合来分别训练多个模型，然后对比它们在验证集上的表现选择相对最好的一组超参数，最后才使用这组参数下训练的模型在测试集上评估测试误差。由于本章训练的模型比较简单，我们暂且忽略掉这个过程。
done

2017-01-12 14:00 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +最后，我们将数据集分割为两份：一份用于调整模型的参数，即进行模型的训练，模型在这份数据集上的误差被称为**训练误差**；另外一份被用来测试，模型在这份数据集上的误差被称为**测试误差**。我们训练模型的目的是为了通过从训练数据中找到规律来预测未知的新数据，所以测试误差是更能反映模型表现的指标。分割数据的比例要考虑到两个因素：更多的训练数据会降低参数估计的方差，从而得到更可信的模型；而更多的测试数
done

2017-01-12 14:00 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +- 很多的机器学习技巧/模型（例如L1，L2正则项，向量空间模型）都基于这样的假设，即所有的属性取值都差不多是以0为均值且取值范围相近的 [7]。
done

2017-01-12 14:00 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +另外一个稍加观察即可发现的事实是，各维属性的取值范围差别很大（如图2所示）。例如，属性B的取值范围是[0.32, 396.90]，而属性NOX的取值范围是[0.3850, 0.8170]。这里就要用到一个常见的操作-归一化（normalization）了。归一化的目标是把各位属性的取值范围放缩到差不多的区间，例如[-0.5,0.5]。下面的代码展示了一种最简便的操作方法：减掉均值，然后除以原取值
done

2017-01-12 14:03 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +观察一下数据，我们的第一个发现是：所有的13维属性中，有12维的连续值和1维的离散值（CHAS）。离散值虽然也常使用类似0、1、2这样的数字表示，但是其含义与连续值是不同的，因为这里的差值没有实际意义。例如，我们用0、1、2来分别表示红色、绿色和蓝色的话，我们并不能因此说“蓝色和红色”比“绿色和红色”的距离更远。所以通常对一个有$d$ 个可能取值的离散属性，我们会将它们转为 $d$ 个取值为0或
done

2017-01-12 14:03 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +| B | 1000(Bk - 0.63)^2，其中BK为黑人占比 | 连续值 |
done

2017-01-12 14:04 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +$$MSE=\frac{1}{n}\sum\_{i=1}\^{n}{(\hat{Y_i}-Y_i)}^2$$
我用 @luotao1  给的地址改了下公式显示，麻烦再帮忙check下

2017-01-12 14:05 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +给定一个大小为$n$的数据集  ${\\{y_{i}, x_{i1}, ..., x_{id}\\}}\_{i=1}\^{n}$，其中$x_{i1}, \ldots, x_{id}$是$d$个属性上的取值，$y_i$是待预测的目标。线性回归模型假设目标$y_i$可以被属性间的线性组合描述，即
done

2017-01-12 14:05 UTC, zhouxiao-coder commented on fit_a_line/README.md
> +让我们从经典的线性回归（Linear Regression [1]）模型开始这份教程。在这一章里，你将使用真实的数据集建立起一个房价预测模型，并且了解到机器学习中的若干重要概念。
done

2017-01-13 03:25 UTC, luotao1 approved these changes

2017-01-13 06:25 UTC, Zrachel reviewed
需小修

2017-01-13 06:25 UTC, Zrachel commented on fit_a_line/README.md
> +给定一个大小为$n$的数据集  ${\{y_{i}, x_{i1}, ..., x_{id}\}}_{i=1}^{n}$，其中$x_{i1}, \ldots, x_{id}$是$d$个属性上的取值，$y_i$是待预测的目标。线性回归模型假设目标$y_i$可以被属性间的线性组合描述，即
其中$x_{i1}, \ldots, x_{id}$是$d$个属性上的取值，$y_i$是待预测的目标。
->
其中$x_{i1}, \ldots, x_{id}$是第$i$个样本$d$个属性上的取值，$y_i$是该样本待预测的目标。

2017-01-13 06:25 UTC, Zrachel commented on fit_a_line/README.md
> +我们使用从[UCI Housing Data Set](https://archive.ics.uci.edu/ml/datasets/Housing)获得的波士顿房价数据集进行模型的训练和预测。下面的散点图展示了使用模型对部分房屋价格进行的预测。其中，横轴展示了该类房屋价格的中位数，纵轴为模型的预测结果，当二者值完全相等的时候就会落在虚线上。所以模型预测得越准确，则点离虚线越近。
其中，横轴展示了该类房屋价格的中位数，纵轴为模型的预测结果
->
其中，每个点的横坐标表示同一类房屋真实价格的中位数，纵坐标表示线性回归模型根据特征预测的结果

2017-01-13 06:25 UTC, Zrachel commented on fit_a_line/README.md
> +这份数据集共506行，每行包含了波士顿郊区的一类房屋的相关信息及价格的中位数。其各维属性的意义如下：
价格的中位数
-》
该类房屋价格的中位数

2017-01-13 06:25 UTC, Zrachel commented on fit_a_line/README.md
> +| MEDV | 房屋价格的中位数 | 连续值 |
房屋价格的中位数
->
同类房屋价格的中位数

2017-01-13 06:25 UTC, Zrachel commented on fit_a_line/README.md
> +观察一下数据，我们的第一个发现是：所有的13维属性中，有12维的连续值和1维的离散值（CHAS）。离散值虽然也常使用类似0、1、2这样的数字表示，但是其含义与连续值是不同的，因为这里的差值没有实际意义。例如，我们用0、1、2来分别表示红色、绿色和蓝色的话，我们并不能因此说“蓝色和红色”比“绿色和红色”的距离更远。所以通常对一个有$d$个可能取值的离散属性，我们会将它们转为$d$个取值为0或1的二
为0或1的二值属性
->
为0或1的二值属性或者将每个可能取值映射为一个多维向量

2017-01-13 08:22 UTC, Zrachel approved these changes

2017-01-13 08:22 UTC, merged