Image Classification Tutorial
PaddlePaddle/book pull request #29
Opened 2016-12-26 05:59 UTC by qingqing01

resolve #5 

Not finished yet.

2016-12-27 06:41 UTC, Zrachel reviewed
已有部分改进需求

2016-12-27 06:41 UTC, Zrachel commented on image_classification/README.md
> +## 模型概览
模型概览中加一点图像分类历史吧，比如12年前，大家怎么做的，然后VGG和ResNet中间加个googlenet吧? issue里忘记说了

2016-12-27 06:41 UTC, Zrachel commented on image_classification/README.md
> +### 数据提供器
就”提供数据给PaddlePaddle“吧，不用翻译了

2016-12-27 06:41 UTC, Zrachel commented on image_classification/README.md
> +### CNN
CNN用 - ，不要用###，因为和VGG/RESNET不是平行关系

2016-12-27 06:41 UTC, Zrachel commented on image_classification/README.md
> +## 模型概览
模型概览里说一下图像分类的loss是多类交叉熵吧，提一下就好，之前有一章讲用MLP分类MNIST，会详细讲到softmax

2016-12-27 06:41 UTC, Zrachel commented on image_classification/README.md
> +下图是训练的分类错误率曲线图：
图片需要缩小

2016-12-27 06:41 UTC, Zrachel commented on image_classification/README.md
> +## 模型应用
模型应用中加上如果需要用比如resnet的图像feature怎么做吧

2016-12-29 09:31 UTC, luotao1 requested changes

2016-12-29 09:31 UTC, luotao1 commented on image_classification/data/cifar10.py
> +import os
缺copyright

2016-12-29 09:31 UTC, luotao1 commented on image_classification/README.md
> +图像相比文字能够提供更加生动、容易理解、有趣及更具艺术感的信息，是人们转递与交换信息的总要来源。在本教程中，我们专注于图像识别领域的重要问题之一 - 图像分类。
1. 图像相比文字能够提供更加生动有趣、容易理解及更具艺术感的信息
2. 我们专注于图像识别领域的一个重要问题，即图像分类问题。

2016-12-29 09:31 UTC, luotao1 commented on image_classification/README.md
> +图像分类在很多领域有广泛应用，包括安防领域的人脸识别、智能视频分析等，交通领域的交通场景识别，互联网领域基于内容的图像检索、相册自动归类，医学领域图像识别等。
8行和10行可以合并成一段。包括安防领域的人脸识别和智能视频分析，交通领域的交通场景识别，互联网领域的基于内容的图像检索和相册自动归类，医学领域的图像识别等。

2016-12-29 09:31 UTC, luotao1 commented on image_classification/README.md
> +而基于深度学习的图像分类方法，其基本思想是通过有监督或无监督的方式学习层次化的特征描述，来对物体进行从底层到高层的描述。深度学习模型之一 — 卷积神经网络(CNN)近年来在图像领域取得了惊人的成绩，CNN直接利用图像像素信息作为输入，最大程度上保留了输入图像的所有信息，通过卷积操作进行特征的提取和高层抽象，模型输出直接是图像识别的结果。这种基于"输入-输出"直接端到端学习方法取了非常好的效果，得
深度学习模型中的卷积神经网络

2016-12-29 09:31 UTC, luotao1 commented on image_classification/README.md
> +图3. CIFAR10数据集
图标号错误。

2017-01-02 01:23 UTC, qingqing01 commented on image_classification/README.md
> +## 模型概览
Done，增加了传统方法和GoogleNet的介绍。

2017-01-02 01:24 UTC, qingqing01 commented on image_classification/README.md
> +## 模型概览
Done

2017-01-02 01:24 UTC, qingqing01 commented on image_classification/README.md
> +### CNN
Done

2017-01-02 01:24 UTC, qingqing01 commented on image_classification/README.md
> +### 数据提供器
Done

2017-01-02 01:25 UTC, qingqing01 commented on image_classification/data/cifar10.py
> +import os
Done

2017-01-02 01:25 UTC, qingqing01 commented on image_classification/README.md
> +图像相比文字能够提供更加生动、容易理解、有趣及更具艺术感的信息，是人们转递与交换信息的总要来源。在本教程中，我们专注于图像识别领域的重要问题之一 - 图像分类。
Done

2017-01-02 01:25 UTC, qingqing01 commented on image_classification/README.md
> +图像分类在很多领域有广泛应用，包括安防领域的人脸识别、智能视频分析等，交通领域的交通场景识别，互联网领域基于内容的图像检索、相册自动归类，医学领域图像识别等。
Done

2017-01-02 01:25 UTC, qingqing01 commented on image_classification/README.md
> +而基于深度学习的图像分类方法，其基本思想是通过有监督或无监督的方式学习层次化的特征描述，来对物体进行从底层到高层的描述。深度学习模型之一 — 卷积神经网络(CNN)近年来在图像领域取得了惊人的成绩，CNN直接利用图像像素信息作为输入，最大程度上保留了输入图像的所有信息，通过卷积操作进行特征的提取和高层抽象，模型输出直接是图像识别的结果。这种基于"输入-输出"直接端到端学习方法取了非常好的效果，得
Done

2017-01-02 01:25 UTC, qingqing01 commented on image_classification/README.md
> +图3. CIFAR10数据集
Done

2017-01-02 01:26 UTC, qingqing01 commented on image_classification/README.md
> +## 模型应用
模型应用增加了预测和提取特征示例，并提供了一张特征可视化的图。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +一般来说，图像分类通过手工特征或特征学习方法对整个图像进行全部描述，然后使用分类器判别物体类别，因此如何提取图像的特征至关重要。在深度学习算法之前使用较多的是基于词包模型的物体分类方法，词包模型的基本框架包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。
词包->词袋，第一处加”(Bag of Words)“

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +一般来说，图像分类通过手工特征或特征学习方法对整个图像进行全部描述，然后使用分类器判别物体类别，因此如何提取图像的特征至关重要。在深度学习算法之前使用较多的是基于词包模型的物体分类方法，词包模型的基本框架包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。
词包模型的基本框架包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。
->
词袋方法从自然语言处理中引入，即一句话可以用一个装了词的袋子表示其特征，袋子中的词为句子中的单词、短语或字。对于图像而言，词袋方法需要构建字典。最简单的词袋模型可以这样设计：

1. 底层特征抽取：提取图像局部特征（可以用局部特征描述子，如SIFT）
2. 特征编码：将提取到的底层特征聚类，得到特征字典。并将底层特征映射到这些类，得到Bag of words(features)特征编码。
3. 分类器设计：选择不同分类器（如支持向量机、朴素贝叶斯等）对上面编码得到的特征进行分类。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +而基于深度学习的图像分类方法，其基本思想是通过有监督或无监督的方式学习层次化的特征描述，来对物体进行从底层到高层的描述。深度学习模型中的卷积神经网络(Convolution Neural Network, CNN)近年来在图像领域取得了惊人的成绩，CNN直接利用图像像素信息作为输入，最大程度上保留了输入图像的所有信息，通过卷积操作进行特征的提取和高层抽象，模型输出直接是图像识别的结果。这种基于"
而基于深度学习的图像分类方法，其基本思想是通过有监督或无监督的方式学习层次化的特征描述
->
而基于深度学习的图像分类方法可以通过有监督或无监督的方式学习层次化的特征描述，从而取代了手工设计或选择图像特征的工作

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +图像识别领域大量的研究成果都是建立在[PASCAL VOC](http://host.robots.ox.ac.uk/pascal/VOC/)、[ImageNet](http://image-net.org/)等公开的数据集上，这些数据集通常作为图像识别的基准测试。PASCAL VOC是2005建立的一个视觉挑战赛，ImageNet是2010年建立的大规模视觉识别竞赛(ILSVRC)的数据集，我
这些数据集通常作为图像识别的基准测试-》很多图像识别算法通常在这些数据集上进行测试和比较

“我们围绕这两个数据集一些论文介绍图像分类的模型。”不通顺

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +一般来说，图像分类通过手工特征或特征学习方法对整个图像进行全部描述，然后使用分类器判别物体类别，因此如何提取图像的特征至关重要。在深度学习算法之前使用较多的是基于词包模型的物体分类方法，词包模型的基本框架包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。
把“基本框架包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段”放到模型概述的“在2012年之前的传统图像分类模型中，”后面，适当组织语言。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +在2012年之前的传统图像分类模型中，底层特征提取是第一步，通常从图像中按照固定步长、尺度提取大量局部特征描述，通常采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、HOG(Histogram of Oriented Gradient, 方向梯度直方图) \[[2](#参考文献)\]、LBP(Loc
底层特征提取
特征编码
空间特征约束
特征汇聚
分类器

这段中，以上几个词语首次出现处用粗体着重。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +在2012年之前的传统图像分类模型中，底层特征提取是第一步，通常从图像中按照固定步长、尺度提取大量局部特征描述，通常采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、HOG(Histogram of Oriented Gradient, 方向梯度直方图) \[[2](#参考文献)\]、LBP(Loc
第一句：2012年之前的传统图像分类模型可以用 背景描述（#背景描述）
中提到的三步完成，但通常完整地建立图像识别模型一般包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +在2012年之前的传统图像分类模型中，底层特征提取是第一步，通常从图像中按照固定步长、尺度提取大量局部特征描述，通常采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、HOG(Histogram of Oriented Gradient, 方向梯度直方图) \[[2](#参考文献)\]、LBP(Loc
一种常用的特征聚会方法即金字塔特征匹配提出将图像均匀分块，再分块内做特征汇聚。
->
一种常用的特征汇聚方法即金字塔特征匹配, 其中提出将图像均匀分块，在分块内做特征汇聚。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +在2012年之前的传统图像分类模型中，底层特征提取是第一步，通常从图像中按照固定步长、尺度提取大量局部特征描述，通常采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、HOG(Histogram of Oriented Gradient, 方向梯度直方图) \[[2](#参考文献)\]、LBP(Loc
特征汇聚是对每一维特征取最大值或者平均值
->
特征汇聚是指在一个空间范围内，对每一维特征取最大值或者平均值

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +在2012年之前的传统图像分类模型中，底层特征提取是第一步，通常从图像中按照固定步长、尺度提取大量局部特征描述，通常采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、HOG(Histogram of Oriented Gradient, 方向梯度直方图) \[[2](#参考文献)\]、LBP(Loc
“例如ILSVRC 2010年挑战者 ” 
写上挑战者的名字吧。。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +
这里加上### 卷积神经网络

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +- 池化层: 是一种降采样操作，通过取卷积得到特征图中局部区块的最大值(Max-Pooling)或平均值(Avg-Pooling)来达到降采样的目的，并在做这个过程中获得一定的不变性。
池化(pooling)层

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +图8. 基于ImageNet的VGG16模型
Inception模块

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +NIN模型中引入了多层感知卷积网络(Multi-Layer Perceptron Convolution, MLPconv)代替一层线性卷积网络。所谓的MLPconv是一个微小的多层卷积网络，即在线性卷积后面增加1x1的卷积，1x1的卷积等价于全连接层，这样利用MLPconv提取高度非线性特征。另外，传统的CNN最后几层一般都是全连接层，参数较多，NIN中采用全局均值池化(Avg-Pooling
“1x1的卷积等价于全连接层”？ 不等价吧。。。1*1的卷积作用是在多通道上降维，从而降低运算复杂度，使得更深的网络成为可能。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +NIN模型中引入了多层感知卷积网络(Multi-Layer Perceptron Convolution, MLPconv)代替一层线性卷积网络。所谓的MLPconv是一个微小的多层卷积网络，即在线性卷积后面增加1x1的卷积，1x1的卷积等价于全连接层，这样利用MLPconv提取高度非线性特征。另外，传统的CNN最后几层一般都是全连接层，参数较多，NIN中采用全局均值池化(Avg-Pooling
为了使得最后一个卷积层获得的每一个特征图能够对应于一个输出类别
->
并保证最后一个卷积层得到的每一个特征图（feature map）都能够对应到一个输出类别。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +GoogleNet模型是由多组Inception模块堆积组成，Inception模块如下图8所示，高层输出是4组不同卷积核大小的特征连接起来，3个黄色1x1卷积是降维的作用，所谓的降维是减少了通道数。引入1x1卷积的原因是如果去掉这几层，会发现Max-Pooling不会改变特征通道数的大小，这样3个蓝色卷积和Max-Pooling特征连接后会导致特征的通道数较大，经过几层这样的模块堆积会导致通常
所以在中间层添加了两个辅助分类器
之后加
整个网络的损失函数（loss）是这三个分类器的loss之和

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +
方便加上googlenet横放的图吗？

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
ImageNet 分类定位、检测
->
ImageNet 图像分类、图像物体定位和图像物体检测

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
ImageNet 分类定位、检测
->
ImageNet 图像分类、图像物体定位和图像物体检测

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
针对训练卷积神经网络时加深网络导致准确度下降的问题，ResNet提出了采用残差学习。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
50-152
->
50, 101, 152

写一下，如图所示，不同层数的网络区别在于。。。（模块重复次数）

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
速度也较VGG有所提升

速度有没有和GoogleNet的比较呢？如果有也加上吧~

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +图像识别领域大量的研究成果都是建立在[PASCAL VOC](http://host.robots.ox.ac.uk/pascal/VOC/)、[ImageNet](http://image-net.org/)等公开的数据集上，这些数据集通常作为图像识别的基准测试。PASCAL VOC是2005建立的一个视觉挑战赛，ImageNet是2010年建立的大规模视觉识别竞赛(ILSVRC)的数据集，我
找到适当的地方介绍一下ImageNet吧，训练数据、测试数据多大，多少类分类，每类样本数在多少范围内什么的。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +执行下面命令下载数据，同时，会基于训练集计算图像均值，在训练阶段，输入数据会基于该均值做预处理，再传输给系统。
执行下面命令下载数据，同时，会基于训练集计算图像均值，在训练阶段，输入数据会基于该均值做预处理，再传输给系统。
->
执行下面命令下载数据，同时基于训练集计算图像均值，用于在网络训练前，基于该均值对输入数据做预处理。

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +在模型配置中，定义通过 `define_py_data_sources2` 从 dataprovider 中读入数据， 其中 args 指定均值文件的路径。如果改配置文件用于预测，则不需要数据定义部分。
如果改配置文件用于预测，则不需要数据定义部分。

预测的时候不需要相同的mean文件吗？

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +在模型配置中，通过 `seetings` 设置训练使用的优化算法，这里指定batch size 、初始学习率、momentum以及L2正则。
`settings`
这里指定->并指定

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +    learning_rate_decay_a=0.1,
learning_rate_decay_a,b注释一下或者外面解释一下含义吧

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +2.1. 首先定义了一组卷积网络，即conv_block。卷积核为3x3，Pooling窗口为2x2，窗口滑动大小为2，groups 决定每组VGG模块是几次连续的卷积操作，dropouts 指定Droupout操作的概率。 所使用的`img_conv_group`是在模块`paddle.trainer_config_helpers`中预定义的模块，由若干组 `Conv->BN->Relu->D
2.1. 首先定义了一组卷积网络，即`conv_block`，其中卷积核大小为3x3，Pooling窗口大小为2x2，窗口滑动大小为2，groups 决定每组VGG模块中有几次连续的卷积操作，……

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +resnet_cifar10的底层输入连接一层 `conv_bn_layer`，即卷积层、BN层、ReLu激活函数。 然后连接3组参数模块即下面配置3组 `layer_warp` ，每组采用图 9 左边残差模块组成，即由2层3x3卷积，各自连接BN层，然后再接ReLu激活函数，每组由若干残差模块堆积而成。最后对网络做Avg-Pooling并返回该层。 返回的网络在第3步接一层全连接层，因此，除过
`resnet_cifar10`

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +resnet_cifar10的底层输入连接一层 `conv_bn_layer`，即卷积层、BN层、ReLu激活函数。 然后连接3组参数模块即下面配置3组 `layer_warp` ，每组采用图 9 左边残差模块组成，即由2层3x3卷积，各自连接BN层，然后再接ReLu激活函数，每组由若干残差模块堆积而成。最后对网络做Avg-Pooling并返回该层。 返回的网络在第3步接一层全连接层，因此，除过
即卷积层、BN层、ReLu激活函数
->
即带Batch normalization的卷积层

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +resnet_cifar10的底层输入连接一层 `conv_bn_layer`，即卷积层、BN层、ReLu激活函数。 然后连接3组参数模块即下面配置3组 `layer_warp` ，每组采用图 9 左边残差模块组成，即由2层3x3卷积，各自连接BN层，然后再接ReLu激活函数，每组由若干残差模块堆积而成。最后对网络做Avg-Pooling并返回该层。 返回的网络在第3步接一层全连接层，因此，除过
2层3x3卷积
->
两层3x3卷积

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +def conv_bn_layer(input,
每个函数后面写下简单注释吧

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +执行脚本 train.sh 进行模型训练， 其中指定配置文件、设备类型、线程个数、总共训练的轮数、模型存储路径等。
移到代码上面

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +
图中可见，运行到xxx个pass收敛，最终得到测试集上准确率达到xxx

2017-01-04 02:40 UTC, Zrachel commented on image_classification/README.md
> +## 参考文献
都加一下链接吧

2017-01-05 08:51 UTC, luotao1 requested changes

2017-01-05 08:51 UTC, luotao1 commented on image_classification/models/resnet.py
> +    tmp = img_conv_layer(
层名不要都用tmp，换更直观一点的，如44行用img_conv就行。请修改resnet.py和vgg.py中所有用tmp的地方，这样文档中解释起来也方便。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +图像分类包括通用图像分类、细粒度图像分类等。下图展示了通用图像分类效果，即模型可以正确识别图像上的主要物体。
图1展示了XXX

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +下图展示了细粒度图像分类-花卉识别的效果，要求模型可以正确识别花的类别。
图2展示了XXX

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +一个好的模型即要对不同类别识别正确，同时也应该能够对不同视角、光照、背景、变形或部分遮挡的图像正确识别(这里我们统一称作图像扰动)，下图展示了一些图像的扰动，较好的模型会像聪明的人类一样能够正确识别。
1. 既要对XXX
2. 。图3展示了XXX

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +在2012年之前的传统图像分类模型中，底层特征提取是第一步，通常从图像中按照固定步长、尺度提取大量局部特征描述，通常采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、HOG(Histogram of Oriented Gradient, 方向梯度直方图) \[[2](#参考文献)\]、LBP(Loc
这一段按照 @Zrachel 的意见。在每一个步骤前再加编号。
2012年之前的传统图像分类模型通常含有以下几步：1）XXX。2）XXX。这样比较清楚。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +Alex Krizhevsky在2012年ILSVRC提出的CNN模型 \[[9](#参考文献)\] 取得了历史性的突破，效果大幅度超越传统方法，获得了ILSVRC 2012冠军，该模型被称作AlexNet，这也是首次将深度学习用于大规模图像分类中，并使用GPU加速模型训练。从此，涌现了一系列CNN模型，不断的在ImageNet上刷新成绩，如图4展示。随着模型变得越来越深以及精妙的结构设计，To
1. 。（逗号改句号）该模型被称作AlexNet，这也是首次将深度学习用于大规模图像分类中，“并使用GPU加速模型训练”这句和前面连起来不通。
2. 从AlexNet之后，XXX
3. 。（逗号改句号）而在同样的ImageNetXXX

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +- 池化层: 是一种降采样操作，通过取卷积得到特征图中局部区块的最大值(Max-Pooling)或平均值(Avg-Pooling)来达到降采样的目的，并在做这个过程中获得一定的不变性。
每一层后面用括号说一下对应的英文名字

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +- 非线性变化: 卷积层、全连层之后一般都会接非线性变化层，例如Sigmoid、Tanh、ReLu等来增强网络的表达能力，在CNN里最常用的为ReLu激活函数。
全连接层，少了一个连字

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +- 卷积层: 通过卷积操作提取底层到高层的特征，发掘出了图片局部关联性质和空间不变性质。
以此发掘出图片XXX

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +，一定程度上防止过拟合。
67,68行连一块

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +
1. 传统CNN包含卷积层、全连接层等组件，并采用softmax多类别分类器和多类交叉熵损失函数。一个典型的CNN如图5所示。
2. 图5放在63-68行之后

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +传统CNN包含卷积层、全连接层等组件，采用softmax多类别分类器和多类交叉熵损失函数。另一个非常值得一提是2015年提出的Batch Normalization(BN)算法 \[[14](#参考文献)\]，作者指出在训练过程中由于每层参数不断更新，会导致下一次输入分布发生变化，这样导致训练过程需要精心设计超参数。而BN算法是每个batch对网络中的每一层的特征做归一化，使得每层分布相对稳定，
第一句话可以去掉了。

另外，在训练过程中由于每层参数不断更新，会导致下一次输入分布发生变化，这样导致训练过程需要精心设计超参数。2015年提出的Batch Normalization(BN)算法 \[[14](#参考文献)\]是每个batch对网络中的每一层特征都做归一化，使得每层分布相对稳定，起到一定的正则作用，同时也弱化了超参数的设计。经过实验证明，BN加速了训练过程，并在后来较深的模型中被广泛使用。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +牛津大学VGG(Visual Geometry Group)组在2014年ILSVRC提出的模型被称作VGG模型 \[[11](#参考文献)\] 。该模型相比以往模型进一步加宽和加深了网络结构，它的核心是五组卷积操作，每两组之间做Max-Pooling空间降维。同一组内采用多次连续的3X3卷积，卷积核的数目由较浅组的64增多到最深组的512，同一组内的卷积核数目是一样的。卷积之后接两层全连接层，
最后一句后面要补充点什么吗，感觉中止的有点快。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +图6. 基于ImageNet的VGG16模型
图6的width可以调大一点，可以和页面同宽，现在图里面的字看不太清楚。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +NIN模型中引入了多层感知卷积网络(Multi-Layer Perceptron Convolution, MLPconv)代替一层线性卷积网络。所谓的MLPconv是一个微小的多层卷积网络，即在线性卷积后面增加1x1的卷积，1x1的卷积等价于全连接层，这样利用MLPconv提取高度非线性特征。另外，传统的CNN最后几层一般都是全连接层，参数较多，NIN中采用全局均值池化(Avg-Pooling
这样可以利用MLPconv提取高度非线性特征

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +
图8的标题错了。图8可以放大一点，现在里面的字太小了。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +上面介绍的是GoogleNet第一版模型(称作GoogleNet-v1)，GoogleNet-v2 \[[14](#参考文献)\] 引入BN层。GoogleNet-v3 \[[16](#参考文献)\] 对一些卷积层做了分解，进一步加深网络非线性能力和加深网络，GoogleNet-v4 \[[17](#参考文献)\] 引入下面要讲的ResNet设计思路，每一版的改进准确度都有所提升，这里不再详细介
上面介绍的是GoogleNet第一版模型(称作GoogleNet-v1)。GoogleNet-v2 \[[14](#参考文献)\] 引入BN层；GoogleNet-v3 \[[16](#参考文献)\] 对一些卷积层做了分解，进一步加深了网络的非线性能力；GoogleNet-v4 \[[17](#参考文献)\] 引入下面要讲的ResNet设计思路。从v1-v4每一版的改进都会带来准确度的提升，介于篇幅，这里不再详细介绍v2-v4结构。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +图8. 基于ImageNet的VGG16模型
89行整段请重新组织。第一句话应该放现在的最后一句话。然后分点介绍。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
残差请在括号中放一下英文

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +图11. CIFAR10数据集
图11太大了

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +`process` 函数将数据逐条传输给系统，在图像分类做可以完整数据扰动操作，再传输给PaddlePaddle。这里将原始图片减去均值后传输给系统。
- 136行
- 138行

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +在模型配置中，定义通过 `define_py_data_sources2` 从 dataprovider 中读入数据， 其中 args 指定均值文件的路径。如果改配置文件用于预测，则不需要数据定义部分。
通过 `define_py_data_sources2` 函数

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +首先介绍VGG模型结构，在CIFAR10数据集上，卷积部分引入了BN和Dropout操作。
这一行可以去掉。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +1. 定义数据输入及其维度
这里的1,2,3,4,5,6在显示中都是1，请调整格式。每一点后面都要加标点。

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +网络输入定义 `data_layer` (数据层)，在图像分类中即为图像像素信息，CIFRAR10是RGB 3通道32x32大小的彩色图，因此输入数据大小为3072(3x32x32)，类别大小为10。
CIFRAR10前面的逗号改句号

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +    tmp = conv_block(input, 64, 2, [0.3, 0], num_channels)
能否不用tmp，换个名字

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +在有监督训练中需要输入图像对应的类别信息，同样，通过`data_layer`来定义。训练中采用多类交叉熵作为损失函数并作为网络的输出，预测阶段定义网络的输出为分类器得到的概率信息。
同样通过`data_layer`来定义

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +ResNet模型的第1、3、4步和VGG模型相同，这里不在介绍。主要介绍第2步即CIFAR10数据集上ResNet核心模块。
不再介绍

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +resnet_cifar10的底层输入连接一层 `conv_bn_layer`，即卷积层、BN层、ReLu激活函数。 然后连接3组参数模块即下面配置3组 `layer_warp` ，每组采用图 9 左边残差模块组成，即由2层3x3卷积，各自连接BN层，然后再接ReLu激活函数，每组由若干残差模块堆积而成。最后对网络做Avg-Pooling并返回该层。 返回的网络在第3步接一层全连接层，因此，除过
这段介绍请根据resnet_cifar10的def，按顺序介绍吧。把tmp名字换掉，介绍起来更清楚。介绍的时候可以用 · 。另外，可以先介绍resnet_cifar10的def，再在每一点中介绍其他的def

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +
图12的标题不对，请修改。CIFAR10数据集上XXX模型的分类错误率

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +在训练完成后，模型会保存在路径 `output/pass-%05d` 下，例如第300个pass的模型会保存在路径 `output/pass-00299`。 脚本 `classify.py` 可以使用模型对图片进行预测或提取特征，注意该脚本默认使用模型配置为 `models/vgg.py`，
可以使用脚本 `classify.py` 对图片进行预测或提取特征

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +图13. CIFAR10数据集
图13太大了，且标题也不对

2017-01-05 08:51 UTC, luotao1 commented on image_classification/README.md
> +可以按照下面方式对图片提取特征，和预测使用方式不同的是指定job类型为extract，并需要指定提取的层。`classify.py` 默认已第一层卷积特征为例提取特征，并给出了可视化图，如图10所示，VGG模型的第一层卷积有64个通道，图 13 展示的为每个通道的灰度图。
1. 默认以
2. 如图10所示，不对吧。
3. 图13展示了每个通道的灰度图

2017-01-08 13:07 UTC, qingqing01 commented on image_classification/README.md
> +    learning_rate_decay_a=0.1,
下面解释了这些参数，并给出了计算公式。

2017-01-08 13:07 UTC, qingqing01 commented on image_classification/README.md
> +## 参考文献
Done

2017-01-08 13:11 UTC, qingqing01 commented on image_classification/README.md
> +一般来说，图像分类通过手工特征或特征学习方法对整个图像进行全部描述，然后使用分类器判别物体类别，因此如何提取图像的特征至关重要。在深度学习算法之前使用较多的是基于词包模型的物体分类方法，词包模型的基本框架包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。
这块没有大改，只在背景介绍中简单了提下传统方法的步骤，没有过多详细介绍，具体介绍在模型概览中。

2017-01-08 13:12 UTC, qingqing01 commented on image_classification/README.md
> +一般来说，图像分类通过手工特征或特征学习方法对整个图像进行全部描述，然后使用分类器判别物体类别，因此如何提取图像的特征至关重要。在深度学习算法之前使用较多的是基于词包模型的物体分类方法，词包模型的基本框架包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。
Done~

2017-01-08 13:13 UTC, qingqing01 commented on image_classification/README.md
> +图像识别领域大量的研究成果都是建立在[PASCAL VOC](http://host.robots.ox.ac.uk/pascal/VOC/)、[ImageNet](http://image-net.org/)等公开的数据集上，这些数据集通常作为图像识别的基准测试。PASCAL VOC是2005建立的一个视觉挑战赛，ImageNet是2010年建立的大规模视觉识别竞赛(ILSVRC)的数据集，我
数据介绍那章中中提了多个数据集，介绍了下ImageNet。

2017-01-08 13:13 UTC, qingqing01 commented on image_classification/README.md
> +在2012年之前的传统图像分类模型中，底层特征提取是第一步，通常从图像中按照固定步长、尺度提取大量局部特征描述，通常采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、HOG(Histogram of Oriented Gradient, 方向梯度直方图) \[[2](#参考文献)\]、LBP(Loc
Done~

2017-01-08 13:19 UTC, qingqing01 commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
这里把和VGG模型速度对比去掉了，也没有加和GoogleNet对比，暂时不加了，以免不准确。

2017-01-08 13:19 UTC, qingqing01 commented on image_classification/README.md
> +ResNet \[[15](#参考文献)\] 是2015年ImageNet分类定位、检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到三次卷积操作得到该特征的残差，最后再将两条路径上的特征相加。残差模块如
这里把和VGG模型速度对比去掉了，也没有加和GoogleNet对比，暂时不加了，以免不准确。

2017-01-08 13:20 UTC, qingqing01 commented on image_classification/README.md
> +def conv_bn_layer(input,
没有在代码中写注释( 不太确定是写英文还是中文)，单独列出了一段，对这几个函数做了解释。

2017-01-08 13:22 UTC, qingqing01 commented on image_classification/models/resnet.py
> +    tmp = img_conv_layer(
vgg.py中的tmp都改了， resnet.py中只改了`def resnet_cifar10`中的，因为感觉代码中通常都用同一个名字写起来比较方便。

2017-01-08 13:28 UTC, qingqing01 commented
@Zrachel @luotao1 按照comments已经都作了修改。

2017-01-09 01:53 UTC, qingqing01 commented on image_classification/README.md
> +在模型配置中，定义通过 `define_py_data_sources2` 从 dataprovider 中读入数据， 其中 args 指定均值文件的路径。如果改配置文件用于预测，则不需要数据定义部分。
预测使用的Python API，python里会加载mean文件，不再需要define_py_data_sources2。

2017-01-09 01:54 UTC, qingqing01 commented on image_classification/README.md
> +resnet_cifar10的底层输入连接一层 `conv_bn_layer`，即卷积层、BN层、ReLu激活函数。 然后连接3组参数模块即下面配置3组 `layer_warp` ，每组采用图 9 左边残差模块组成，即由2层3x3卷积，各自连接BN层，然后再接ReLu激活函数，每组由若干残差模块堆积而成。最后对网络做Avg-Pooling并返回该层。 返回的网络在第3步接一层全连接层，因此，除过
@luotao1 这块重新组织了下。

2017-01-11 07:44 UTC, luotao1 reviewed
还有一些小问题

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +一般来说，图像分类通过手工特征或特征学习方法对整个图像进行全部描述，然后使用分类器判别物体类别，因此如何提取图像的特征至关重要。在深度学习算法之前使用较多的是基于词袋(Bag of Words)模型的物体分类方法，词袋方法从自然语言处理中引入，即一句话可以用一个装了词的袋子表示其特征，袋子中的词为句子中的单词、短语或字。对于图像而言，词袋方法需要构建字典。最简单的词袋模型框架可以设计为**底层特
词袋方法前面的逗号改句号。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +而基于深度学习的图像分类方法可以通过有监督或无监督的方式**学习**层次化的特征描述，从而带取代了手工设计或选择图像特征的工作。深度学习模型中的卷积神经网络(Convolution Neural Network, CNN)近年来在图像领域取得了惊人的成绩，CNN直接利用图像像素信息作为输入，最大程度上保留了输入图像的所有信息，通过卷积操作进行特征的提取和高层抽象，模型输出直接是图像识别的结果。这
1. 而基于深度学习的图像分类方法，（加逗号）
2. 从而取代，多了一个“带”
3. 直接端到端的学习方法

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +一个好的模型既要对不同类别识别正确，同时也应该能够对不同视角、光照、背景、变形或部分遮挡的图像正确识别(这里我们统一称作图像扰动)，图3展示了一些图像的扰动，较好的模型会像聪明的人类一样能够正确识别。
图3前面的逗号改句号。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +在2012年之前的传统图像分类方法可以用背景描述中提到的三步完成，但通常完整建立图像识别模型一般包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。1). **底层特征提取**，通常从图像中按照固定步长、尺度提取大量局部特征描述，采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、H
这段太长了，1234改为如下：
- 底层特征提取：通常从图像中按照固定步长、尺度提取大量局部特征描述。原文的逗号改成句号。
- 特征编码：
- 空间特征约束：再分块内做特征汇聚-》再在分块内做特征汇聚
- 分类器分类：。通常使用的分类器包括SVM。（这句前面和后面的逗号都改句号）

[NEC实验室](http://www.nec-labs.com/)在ILSVRC2010中通过采用SIFT和LBP特征、两个非线性编码器以及SVM分类器获得图像分类的冠军 \[[8](#参考文献)\]。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +Alex Krizhevsky在2012年ILSVRC提出的CNN模型 \[[9](#参考文献)\] 取得了历史性的突破，效果大幅度超越传统方法，获得了ILSVRC2012冠军，该模型被称作AlexNet。这也是首次将深度学习用于大规模图像分类中。从AlexNet之后，涌现了一系列CNN模型，不断的在ImageNet上刷新成绩，如图 4 展示。随着模型变得越来越深以及精妙的结构设计，Top-5的
1. 涌现了一系列CNN模型，不断地在
2. 如图4展示，4前后的空格去掉

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +传统CNN包含卷积层、全连接层等组件，并采用softmax多类别分类器和多类交叉熵损失函数，一个典型的神经网络如下图5所示，我们首先了解CNN网络结构的一些基本组件。
。一个典型的XX

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +- 非线性变化: 卷积层、全连接层后面一般都会接非线性变化层，例如Sigmoid、Tanh、ReLu等来增强网络的表达能力，在CNN里最常用的为ReLu激活函数。
非线性变化层：XXX，在CNN里最常使用ReLu激活函数。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +- Droupout \[[10](#参考文献)\] : 在模型训练阶段随机让一些隐层节点权重不工作，提高网络的泛化能力，一定程度上防止过拟合。
Dropout拼错了，另外有对应的中文么

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +另外，在训练过程中由于每层参数不断更新，会导致下一次输入分布发生变化，这样导致训练过程需要精心设计超参数。2015年Sergey Ioffe和Christian Szegedy提出的Batch Normalization(BN)算法 \[[14](#参考文献)\]，BN算法是每个batch对网络中的每一层的特征做归一化，使得每层分布相对稳定，起到一定的正则作用，同时也弱化了超参数的设计。经过实验
2015年Sergey Ioffe和Christian Szegedy提出的Batch Normalization(BN)算法 \[[14](#参考文献)\]，是每个batch对网络中每一层的特征都做归一化，使得每层分布相对稳定。BN算法不仅起到正则作用，而且时也弱化了超参数的设计。经过实验证明，BN算法XXX

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +牛津大学VGG(Visual Geometry Group)组在2014年ILSVRC提出的模型被称作VGG模型 \[[11](#参考文献)\] 。该模型相比以往模型进一步加宽和加深了网络结构，它的核心是五组卷积操作，每两组之间做Max-Pooling空间降维。同一组内采用多次连续的3X3卷积，卷积核的数目由较浅组的64增多到最深组的512，同一组内的卷积核数目是一样的。卷积之后接两层全连接层，
` \[[19](#参考文献)\]`

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +<img src="image/vgg16.png" width="600" ><br/>
还可以再宽

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +NIN模型中引入了多层感知卷积网络(Multi-Layer Perceptron Convolution, MLPconv)代替一层线性卷积网络。所谓的MLPconv是一个微小的多层卷积网络，即在线性卷积后面增加若干层1x1的卷积，这样可利用MLPconv提取高度非线性特征。另外，传统的CNN最后几层一般都是全连接层，参数较多。而NIN最后一层卷积层包含类别维度大小的特征图，然后采用全局均值池化
区别于传统CNN，NIN模型有以下两个特点：1）引入了多层感知卷积网络(Multi-Layer Perceptron Convolution, MLPconv)来代替一层线性卷积网络。MLPconv是一个微小的多层卷积网络，即在线性卷积后面增加若干层1x1的卷积。这样NIN模型就可以提取高度非线性特征。2）传统CNN的最后几层一般都是全连接层，参数较多。而由于NIN模型的最后一个卷积层包含了类别维度大小的特征图，所以可采用全局均值池化(Avg-Pooling)层来替代全连接层，从而得到类别维度大小的向量（直接连“进行分类”不是很通，你再顺一下），大大减少了参数。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +GoogleNet整体网络结构是：开始由3层普通的卷积组成；接下来由三组子网络组成，第一组子网络包含2个Inception模块，第二组包含5个Inception模块，第三组包含2个Inception模块；然后接Avg-Pooling、全连接层，总共22层网络。
GoogleNet整体网络结构如图9所示，一共有22层：XXX；然后接平均值池化层和全连接层。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +GoogleNet模型是由多组Inception模块堆积组成，Inception模块如下图8所示，高层输出是4组不同卷积核大小的特征连接起来，3个黄色1x1卷积是降维的作用，所谓的降维就是减少了通道数。引入1x1卷积的原因是如果去掉这几层，会发现Max-Pooling不会改变特征通道数的大小，这样3个蓝色卷积和Max-Pooling特征连接后会导致特征的通道数较大，经过几层这样的模块堆积会导致通
1. 90、97、99行中的max-pooling和avg-pooling全部用中文，因为别的层都用中文了。
2. 90行还需要组织下，根据图，要么从上到下介绍，要么从下到上介绍。现在写的不够清晰。第一句的前半句不要，“Inception模块如图8所示XXX”

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +通用图像分类公开的标准数据集常用的有[CIFAR](<https://www.cs.toronto.edu/~kriz/cifar.html)、[ImageNet](http://image-net.org/)、[COCO](http://mscoco.org/)等，常用的细粒度图像分类数据集包括[CUB-200-2011](http://www.vision.caltech.edu/visip
1. 如[模型概览](#模型概览)
2. 常用的是ImageNet-2012数据集，该数据集包含1000个类别：训练集有1,281,167张图片，每个类别的图片有732至1300张不等；验证集包含50,000张图片，平均每个类别50张图片。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +由于ImageNet数据集较大，下载和训练较慢，为了方便大家学习，我们使用[CIFAR10](<https://www.cs.toronto.edu/~kriz/cifar.html>)数据集。CIFAR10数据集包含60,000张32x32的彩色图片，10个类别，每个类包含6,000张。其中50,000张图片作为训练集，10000张作为测试集。图 12 从每个类别中随机抽取了10张图片，展示了
图12前后空格去掉。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +执行下面命令下载数据，同时基于训练集计算图像均值，用于在网络输入前，基于该均值对输入数据做预处理。
下面命令用于下载数据和基于训练集计算图像均值：

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +- `process` 函数将数据逐条传输给系统，在图像分类做可以完成数据扰动操作，再传输给PaddlePaddle。这里对训练集做随机左右翻转，并将原始图片减去均值后传输给系统。
“在图像分类做可以完成数据扰动操作”这句不通。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +$$  lr = learning\_rate * learning\_rate\_decay\_a^ {\lfloor \frac{num\_samples\_processed}{ learning\_rate\_decay\_b}\rfloor} $$
用一个变量来代替\lfloor \frac{num\_samples\_processed}{ learning\_rate\_decay\_b}\rfloor，然后再定义这个变量。现在上标看不清楚。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +本教程中我们提供了VGG 和 ResNet两个模型的配置。
删掉本行中多余的空格。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +	2.1. 首先定义了一组卷积网络，即conv_block。卷积核大小为3x3，Pooling窗口大小为2x2，窗口滑动大小为2，groups 决定每组VGG模块是几次连续的卷积操作，dropouts 指定Droupout操作的概率。所使用的`img_conv_group`是在模块`paddle.trainer_config_helpers`中预定义的模块，由若干组 `Conv->BN->Rel
所使用的`img_conv_group`是在`paddle.trainer_config_helpers`中预定义的模块，由若干组`Conv->BN->Relu->Dropout` 和一组 `Pooling` 组成。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +	在有监督训练中需要输入图像对应的类别信息，同样通过`data_layer`来定义。训练中采用多类交叉熵作为损失函数并作为网络的输出，预测阶段定义网络的输出为分类器得到的概率信息。
训练中采用多类交叉熵作为损失函数，并作为网络的输出；预测阶段定义网络的输出为分类器得到的概率信息。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +- `shortcut` : 残差模块的"直连"路径，"直连"实际分两种形式，一种是残差模块输入和输出特征通道数不等时，采用1x1卷积的升维操作。另一种是残差模块输入和输出通道相等时，采用直连操作。
"直连"实际分两种形式：输入和输出特征通道数不等时，采用1x1卷积的升维操作；输入和输出通道相等时，采用直连操作。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +- `layer_warp` : 一组残差模块，由若干残差模块堆积而成。每组中第一残差模块滑动窗口大小与其他可以不同，用来减少特征图在垂直和水平方向的大小。
每组中第一残差模块滑动窗口大小可以与其他的不同，以用来减少特征图在垂直和水平方向的大小。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +`resnet_cifar10` 完整的定义如下，先介绍几个基本函数。
1. 先介绍`resnet_cifar10`的一些基本函数
2.  再`介绍resnet_cifar10`的连接过程
     把371行def resnet_cifar10(ipt, depth=56)开始，挪到第2步里面，即挪到396或398行后面。

重新调整下缩进格式。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +2. 然后连接3组残差模块即下面配置3组 `layer_warp` ，每组采用图 10 左边残差模块组成。
图10前后空格去掉。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +除过第一层卷积层和最后一层全连接层这2层外，要求3组 `layer_warp` 总的含参层数能够6 整除，即 `resnet_cifar10` 的 depth 要满足 $(depth - 2）% 6 == 0$ 。
注意：除第一层卷积层和最后一层全连接层外，要求三组 `layer_warp` 总的含参层数能够被6整除，即 `resnet_cifar10` 的 depth 要满足$(depth - 2)% 6 == 0$。 

depth右边的括号是中文的，导致公式没显示对。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +可以按照下面方式对图片提取特征，和预测使用方式不同的是指定job类型为extract，并需要指定提取的层。`classify.py` 默认以第一层卷积特征为例提取特征，并给出了可视化图，如图 14 所示，VGG模型的第一层卷积有64个通道，图 14 展示了每个通道的灰度图。
并会画出了类似图14的可视化图。VGG模型的第一层卷积有64个通道，图14展示了每个通道的灰度图。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
>  ## 总结
本文我们首先介绍VGG、GoogleNet、ResNet三个经典的模型；然后基于CIFAR10数据集，介绍如何使用PaddlePaddle配置和训练CNN模型，尤其是VGG和ResNet模型；最后介绍如何使用PaddlePaddle的API接口对图片进行预测和特征提取。对于其他数据集比如ImageNet，配置和训练流程是同样的，大家可以自行进行实验。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
>  GoogleNet \[[12](#参考文献)\] 在2014年ILSVRC的获得了冠军，在介绍该模型之前我们先来了解NIN(Network in Network)模型 \[[13](#参考文献)\]，因为GoogleNet模型借鉴了NIN的一些思想。
在介绍该模型之前我们先来了解NIN(Network in Network)模型 \[[13](#参考文献)\]和Inception模块，因为GoogleNet模型借鉴了NIN的一些思想，并由多组Inception模块组成。

Inception有中文么

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +另外，GoogleNet在网络最后也没有采用传统的多层全连接层，而是像NIN网络一样采用了Avg-Pooling，与NIN不同的是，Avg-Pooling后面接了一层到类别数映射的全连接层。除了Inception模块和Avg-Pooling外，由于网络中间层特征也很有判别性，所以在中间层添加了两个辅助分类器，在后向传播中增强梯度并且增强正则化，而整个网络的损失函数是这个三个分类器的损失加权求和。
97行放在99行后面介绍。注意：1）GoogleNet在网络最后没有采用传统的多层全连接层，而是像NIN一样采用了平均池化层。但与NIN不同的是，平均池化层后面又接了一层到类别数映射的全连接层。2）网络中间层（中间层是什么？）

97行再顺一下。看下是直接连在99行后面好，还是另起一行好。

2017-01-11 07:44 UTC, luotao1 commented on image_classification/README.md
> +ResNet(Residual Network) \[[15](#参考文献)\] 是2015年ImageNet图像分类、图像物体定位和图像物体检测比赛的冠军。针对训练卷积神经网络时加深网络导致准确度下降的问题，ResNet提出了采用残差学习。在已有设计思路(BN, 小卷积核，全卷积网络)的基础上，引入了残差模块。每个残差模块包含两条路径，其中一条路径是输入特征的直连通路，另一条路径对该特征做两到
另起一行：残差模块如图10所示，左边是基本模块连接方式，右边是瓶颈模块（Bottleneck）连接方式，瓶颈模块多用于较深的网络中。图11展示了50、101、152层网络连接示意图，这三个网络的区别在于每组中残差模块的重复次数不同（见图右上角）。由于ResNet训练收敛较快，因此成功地训练了上百乃至近千层的卷积神经网络。

2017-01-11 09:48 UTC, Zrachel reviewed
需要修改小问题

2017-01-11 09:48 UTC, Zrachel commented on image_classification/README.md
> +图3. 扰动图片展示
所有图片，如果不是自己的，要加来源注释

2017-01-11 09:48 UTC, Zrachel commented on image_classification/README.md
> +在2012年之前的传统图像分类方法可以用背景描述中提到的三步完成，但通常完整建立图像识别模型一般包括底层特征学习、特征编码、空间约束、分类器设计、模型融合等几个阶段。1). **底层特征提取**，通常从图像中按照固定步长、尺度提取大量局部特征描述，采用的局部特征包括SIFT(Scale-Invariant Feature Transform, 尺度不变特征转换) \[[1](#参考文献)\]、H
再分块内做特征汇聚-》再在分块内取最大值或平均值

2017-01-11 09:48 UTC, Zrachel commented on image_classification/README.md
> +另外，在训练过程中由于每层参数不断更新，会导致下一次输入分布发生变化，这样导致训练过程需要精心设计超参数。2015年Sergey Ioffe和Christian Szegedy提出的Batch Normalization(BN)算法 \[[14](#参考文献)\]，BN算法是每个batch对网络中的每一层的特征做归一化，使得每层分布相对稳定，起到一定的正则作用，同时也弱化了超参数的设计。经过实验
2015年Sergey Ioffe和Christian Szegedy提出的Batch Normalization(BN)算法 \[[14](#参考文献)\]，BN算法是每个batch对网络中的每一层的特征做归一化，
->
如2015年Sergey Ioffe和Christian Szegedy提出的Batch Normalization(BN)算法 \[[14](#参考文献)\]中，对每个batch对网络中的每一层的特征做归一化，

2017-01-11 11:38 UTC, qingqing01 commented
@luotao1 @Zrachel 已按照comments逐一修改 :）

2017-01-11 13:09 UTC, Zrachel commented
@qingqing01 是的，paper中能不到的图加url来源，也放在参考文献里，以[\[5\]](#参考文献)形式写在图几的描述后面

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +- 非线性变化: 卷积层、全连接层后面一般都会接非线性变化层，例如Sigmoid、Tanh、ReLu等来增强网络的表达能力，在CNN里最常使用的为ReLu激活函数。
ReLu ==> ReLU

另外可以加一个连接 https://en.wikipedia.org/wiki/Rectifier_(neural_networks)

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +接下来我们主要介绍VGG，GooleNet和ResNet网络结构。
GooleNet ==> GoogleNet

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +传统CNN包含卷积层、全连接层等组件，并采用softmax多类别分类器和多类交叉熵损失函数，一个典型的卷积神经网络如图5所示，我们首先了解CNN网络结构的一些基本组件。
> 我们首先了解CNN网络结构的一些基本组件

是不是改成

> 我们先介绍用来构造CNN的常见组件

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +- 卷积(Convolution)层: 通过卷积操作提取底层到高层的特征，发掘出图片局部关联性质和空间不变性质。
如果写

> 卷积层（convolution layer）：执行[卷积](https://en.wikipedia.org/wiki/Convolution)操作，从输入中提取高阶特征。卷积是一种在图像处理领域广泛使用了多年的操作，它能利用图片的局部关联和空间不变性。

能否更清晰一些？

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +- 池化(Pooling)层: 是一种降采样操作，通过取卷积得到特征图中局部区块的最大值(Max-Pooling)或平均值(Avg-Pooling)来达到降采样的目的，并在做这个过程中获得一定的不变性。
如果写

> 池化层（pooling layer）：执行降采样（downsample）操作。通常取卷积层的输出图像中的局部区块的最大值（max-pooling）或者均值（avg-pooling）。降采样也是图像处理中常见的一种操作，可以帮助我们滤掉对分类不那么重要的高频信息。

不知道能否更清晰一点？

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +- 全连接(Fully-Connected, 简称FC)层: 输入层到隐藏层的神经元是全部连接的。
如果写

> 全连接层（fully-connected layer，或者 fc-layer）：执行一种输入到输出的变化，其中每个输出值都是用所有输入值计算得到的。全连接层是deep learning中常见的一种组件，通常其输出体现输入信息中的一些隐含但重要的因素。

不知道可否更清晰一点？

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +另外，在训练过程中由于每层参数不断更新，会导致下一次输入分布发生变化，这样导致训练过程需要精心设计超参数。如2015年Sergey Ioffe和Christian Szegedy提出了Batch Normalization(BN)算法 \[[14](#参考文献)\]中，每个batch对网络中的每一层特征都做归一化，使得每层分布相对稳定。BN算法不仅起到一定的正则作用，而且弱化了超参数的设计。经过
如果我们用英语括号，那么"Batch Normalization"和"(BN)“之间应该有一个空格；如果我们用中文括号，则不需要。

2017-01-11 21:32 UTC, wangkuiyi commented on image_classification/README.md
> +另外，在训练过程中由于每层参数不断更新，会导致下一次输入分布发生变化，这样导致训练过程需要精心设计超参数。如2015年Sergey Ioffe和Christian Szegedy提出了Batch Normalization(BN)算法 \[[14](#参考文献)\]中，每个batch对网络中的每一层特征都做归一化，使得每层分布相对稳定。BN算法不仅起到一定的正则作用，而且弱化了超参数的设计。经过
这里

> 弱化了超参数的设计

是不是想说

> 弱化了对刁钻的超参数设计的依赖

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +  - 4). **通过分类器分类**，经过前面步骤之后一张图像可以用一个固定维度的向量进行描述，接下来就是经过分类器对图像进行分类。通常使用的分类器包括SVM(Support Vector Machine, 支持向量机)、随机森林等。而使用核方法的SVM是最为广泛的分类器，在传统图像分类任务上性能很好。
如果有点的话，"1)."这些是不是不要了，**底层特征提取**后面加冒号，其他也是类似修改。

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +这种方法在PASCAL VOC竞赛中的图像分类算法中被广泛使用[18]。[NEC实验室](http://www.nec-labs.com/)在ILSVRC2010中采用SIFT和LBP特征，两个非线性编码器以及SVM分类器获得图像分类的冠军 \[[8](#参考文献)\]。
[18]参考文献没跳转

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +<img src="image/vgg16.png" width="700" ><br/>
图可以拉宽点

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +Inception模块如下图7所示，图(a)是最简单的设计，输出是3个卷积层和一个池化层的特征拼接，这样设计的缺点是池化层不会改变特征通道数，拼接后会导致特征的通道数较大，经过几层这样的模块堆积会导致通道数越来越大，参数和计算量随之增大。为了改善这个缺点，图(b)引入3个1x1卷积层进行降维，所谓的降维就是减少通道数，同时如NIN模型中提到的1x1卷积也可以修正线性特征。
一些小修：

Inception模块如下图7所示。图(a)是最简单的设计，输出是3个卷积层和一个池化层的特征拼接。图(a)的缺点是池化层不会改变特征通道数，拼接后会导致这个通道数较大，经过几层这样的模块堆积后，这个通道数会越来越大，导致参数和计算量也随之增大。为了改善这个缺点，图(b)引入3个1x1卷积层进行降维，所谓的降维就是减少通道数。

最后一句话中线性特征是啥？

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +GoogleNet由多组Inception模块堆积而成，另外，在网络最后也没有采用传统的多层全连接层，而是像NIN网络一样采用了均值池化层，与NIN不同的是，池化层后面接了一层到类别数映射的全连接层。除了这两个特点之外，由于网络中间层特征也很有判别性，GoogleNet在中间层添加了两个辅助分类器，在后向传播中增强梯度并且增强正则化，而整个网络的损失函数是这个三个分类器的损失加权求和。
一些小修：

+GoogleNet由多组Inception模块堆积而成。另外，在网络最后也没有采用传统的多层全连接层，而是像NIN网络一样采用了均值池化层；但与NIN不同的是，池化层后面接了一层到类别数映射的全连接层。除了这两个特点之外，由于网络中间层特征也很有判别性，因此GoogleNet在中间层添加了两个辅助分类器，并在后向传播中增强梯度和正则化，整个网络的损失函数就是这个三个分类器的损失加权求和。

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +图8. GoogleNet[12]
图中的参考文献无法跳转

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +残差模块如图9所示，左边是基本模块连接方式，由两个输出通道数相同的3x3卷积组成。右边是瓶颈模块(Bottleneck)连接方式，之所以称为瓶颈，是因为上面的1x1卷积用来降维(图示例即256->64)，下面的1x1卷积用来升维(图示例即64->256)，这样中间3x3卷积的输入和输出通道数都较小(图示例即64->64)。图10展示了50、101、152层网络连接示意图，所使用是瓶颈模块。这三个
1. 从图10开始的几句话，放在图9后面介绍。
2. 所使用是瓶颈模块，这句话不通。

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +通过 `learning_rate_decay_a` (简写a） 、`learning_rate_decay_b` (简写b) 和 `learning_rate_schedule ` 指定学习率调整策略，这里采用离散指数的方式调节学习率，计算公式如下， `n` 代表已经处理过的累计总样本数，$lr_{0}$ 即为 `settings` 里设置的 `learning_rate`。
因为下面是公式，所以228行中的a,b,n都用$a$,$b$,$n$来表示

2017-01-12 07:48 UTC, luotao1 commented on image_classification/README.md
> +`resnet_cifar10` 的连接结构主要由以下几个过程。
主要有，笔误

2017-01-12 09:19 UTC, luotao1 approved these changes

2017-01-12 09:27 UTC, merged