translate Chapter 7 (machine translation)
PaddlePaddle/book pull request #91
Opened 2017-03-01 05:35 UTC by Haichao-Zhang

Translation of Chapter 7 (machine translation) of the PaddlePaddle book.

2017-03-02 22:54 UTC, wangkuiyi requested changes

2017-03-02 22:54 UTC, wangkuiyi commented on machine_translation/README.en.md
> +Figure 1. Neural Network based Machine Translation
Do we have Chinese text in this figure? If so, could you please list necessary translations here? This applies to all figures. Thanks!

2017-03-02 22:54 UTC, wangkuiyi commented on machine_translation/README.en.md
> +这些 是 希望 的 曙光 和 解脱 的 迹象 .
Should we also translate this Chinese sentence into English?

2017-03-02 23:57 UTC, Haichao-Zhang commented on machine_translation/README.en.md
> +这些 是 希望 的 曙光 和 解脱 的 迹象 .
I guess not. As we are doing machine translation and the translated results  for this sentence are provided in the line immediately below it.

2017-03-02 23:57 UTC, Haichao-Zhang commented on machine_translation/README.en.md
> +Figure 1. Neural Network based Machine Translation
Word translations added.

2017-03-03 01:16 UTC, wangkuiyi approved these changes

2017-03-03 01:16 UTC, merged