Add image_classification api v2
PaddlePaddle/book pull request #97
Opened 2017-03-02 09:05 UTC by gangliao

2017-03-02 22:21 UTC, wangkuiyi requested changes
请问，这个PR里新增的三个文件，其中哪些是应该放进README.md或者README.en.md里，并且加以说明的呢？

2017-03-06 03:52 UTC, gangliao commented
@wangkuiyi 求review..

2017-03-07 01:05 UTC, helinwang commented on image_classification/README.md
> +reader=paddle.reader.batched(
这个需要改成paddle.batch

2017-03-07 01:07 UTC, helinwang approved these changes
Have one comment, LGTM after fixing it.

2017-03-07 02:16 UTC, qingqing01 commented on image_classification/README.md
> +根据网络拓扑结构和模型参数来构造出trainer用来训练，在构造时还需指定优化方法，这里使用最基本的SGD方法(momentum设置为0)，同时设定了学习率、正则等。
"这里使用最基本的SGD方法(momentum设置为0)"  -> 这里使用Momentum方法

2017-03-07 02:16 UTC, qingqing01 commented on image_classification/README.md
> +reader_dict={'image': 0,
reader_dict -> feeding， 代码文档都需要统一改下

2017-03-07 04:03 UTC, gangliao commented on image_classification/README.md
> +reader_dict={'image': 0,
Done

2017-03-07 04:03 UTC, gangliao commented on image_classification/README.md
> +根据网络拓扑结构和模型参数来构造出trainer用来训练，在构造时还需指定优化方法，这里使用最基本的SGD方法(momentum设置为0)，同时设定了学习率、正则等。
DOne

2017-03-07 04:03 UTC, gangliao commented on image_classification/README.md
> +reader=paddle.reader.batched(
Done

2017-03-07 04:59 UTC, wangkuiyi approved these changes

2017-03-07 05:00 UTC, merged