V2 API Train
PaddlePaddle/book pull request #98
Opened 2017-03-02 10:24 UTC by reyoung

2017-03-02 22:16 UTC, wangkuiyi reviewed
感谢这个PR！

但是有个问题：

- 很早之前我们就说我们不直接编辑ipynb文件，因为没法在code review的时候逐行comment，讨论不便。
- 现在IDL-US和AI Lab的同事们已经在翻译README.md 到README.en.md。所以我们期待的 .ipynb 文件最好是从 README.{md,en.md} 通过一个工具自动生成 .ipynb 文件。

如果我们暂时没时间写这个工具，那么这个版本可能就还是得发行 html 文件，而不是 .pynb 文件了。

不管如何，我赞同merge这个PR，至少增加一个中文版的 .pynb 文件。

2017-03-02 22:16 UTC, wangkuiyi commented on recommender_system/.gitignore
> +params.pkl
Jupyter server不一定运行在本地，不一定有权限读写本地文件系统，所以暂时不需要考虑parameters的save/load了。也不需要存在 params.pkl 这个文件，源码里也不需要 cPickle。

可以下下周再考虑参数的save/load。

2017-03-02 22:16 UTC, wangkuiyi commented on recommender_system/.gitignore
> +params.pkl
api_train.ipynb ==> recommender_system.ipynb 或者 README.ipynb

2017-03-02 22:20 UTC, wangkuiyi commented
关于book里的PR，有几个问题：

1. 因为很早之前我们就说我们不直接编辑ipynb文件（当时考虑没法在code review的时候逐行comment，讨论不便），所以，现在IDL-US和AI Lab的同事们已经在翻译README.md 到README.en.md。
1. 所以我们期待的 .ipynb 文件最好是从 README.{md,en.md} 通过一个工具自动生成 .ipynb 文件。

希望大家的PR不是新增.pynb 文件，而是修改 README.md 文件。确保用我们现有的工具，可以从 README.md 生成 README.index（或者从 README.en.md 可以生成 README.en.index）

2017-03-02 22:22 UTC, wangkuiyi requested changes
关于book里的PR，有几个问题：

1. 因为很早之前我们就说我们不直接编辑ipynb文件（当时考虑没法在code review的时候逐行comment，讨论不便），所以，现在IDL-US和AI Lab的同事们已经在翻译README.md 到README.en.md。
1. 所以我们期待的 .ipynb 文件最好是从 README.{md,en.md} 通过一个工具自动生成 .ipynb 文件。

希望大家的PR不是新增.pynb 文件，而是修改 README.md 文件。确保用我们现有的工具，可以从 README.md 生成 README.index（或者从 README.en.md 可以生成 README.en.index）

2017-03-06 09:29 UTC, reyoung commented on recommender_system/.gitignore
> +params.pkl
Done.

2017-03-06 09:29 UTC, reyoung commented
Add README.md and README.ipynb both.

2017-03-07 01:23 UTC, helinwang commented on recommender_system/README.md
> +import cPickle
cPickle 还需要吗？我下面没看到用cPickle的地方。

2017-03-07 01:26 UTC, helinwang approved these changes
赞。有一个评论，otherwise LGTM。
关于ipynb文件的讨论：我觉得既然以.md为数据源，可以考虑只check in .md文件，有脚本 ／ traivis CI来生成ipynb文件放在其他地方。（现在html也是checkin到了github，可能也需要这样）

2017-03-07 19:32 UTC, wangkuiyi approved these changes

2017-03-07 19:33 UTC, merged